### ISSUE TITLE
Scrolling view with middle mouse button

### ISSUE THREAD

**Issue by mardy** [leozide/leocad#1]
Hi Leo! Thanks for the excellent application! I hope this is the right place to report bugs (the `login` link in Trac links to a file listing, and the mailing list gives a 503 error at the moment).

This is a feature request: could we use the middle mouse button (MMB) to rotate the view, in a similar way like Blender does?
I would suggest:
- if the cursor moves left/right/up/down while the MMB is pressed, rotate the view left/right/up/down around the selected object (or the center)
- if the shift key is also pressed, do pan instead

Let me know if you agree with the change, I might volunteer to implement it myself.

**Comment by leozide** [comment]
I'm trying to move the site from Trac to here so I disabled the login there.

You can do that already, it defaults to Maya style controls (Alt + Mouse buttons) and it's configurable in the Mouse tab of the Preferences Dialog so you can have Blender shortcuts if you want.
