### ISSUE TITLE
Anti-aliasing not applied on "Save Image..."

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#101]
![Save image ignore AA](http://hnng.moe/f/TJS)

**Comment by Symbian9** [comment]
@leozide, this issue still reproducable for me!

LeoCAD version: 18.01
OS: MX Linux MX-17 (Debian 9 "Stretch"), x86_64 (64-bit)

**Comment by leozide** [comment]
This requires OpenGL 3.2

**Comment by Symbian9** [comment]
So, no any workarounds for OpenGL 1.x/2.x?
