### ISSUE TITLE
www.leocad.org website serves content over plain HTTP

### ISSUE THREAD

**Issue by janisozaur** [leozide/leocad#102]
Steps to reproduce:
1. Go to http://www.leocad.org

Expected results:
* Get redirected to https://www.leocad.org

Actual results:
* Content is served over plain HTTP

Additionally, forcing HTTPS by visiting https://www.leocad.org reports:

```
www.leocad.org uses an invalid security certificate.

The certificate is only valid for the following names: www.github.com, *.github.com, github.com,
*.github.io, github.io, *.githubusercontent.com, githubusercontent.com

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by Symbian9** [comment]
NO! No need this f*cking https/ssl!

I don't like this idea, because then LeoCAD website would be full depend from SSL certifacte owners and in any time it could stop it.

**Comment by Symbian9** [comment]
For example, Unicode website also work without HTTPS/SSL

* http://unicode.org

**Comment by leozide** [comment]
Unfortunately Github doesn't support https for custom domains.

**Comment by leozide** [comment]
It's https://leozide.github.io/leocad but that redirects automatically.

I can't find anything on the docs for disabling the redirect: https://help.github.com/articles/custom-domain-redirects-for-github-pages-sites/
