### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [leozide/leocad#103]
Please provide the AppImage for download on GitHub Releases, thanks.
Possibly you might be interested in https://github.com/probonopd/uploadtool which simplifies this.

Reference:
AppImage/AppImageHub#15

**Comment by Symbian9** [comment]
Related

* https://github.com/leozide/leocad/issues/75

**Comment by leozide** [comment]
@probonopd I've created a script to build an appimage with the latest parts library but at run-time the app can't find the library file, even though it's in the appimage. How can I load a file inside the appimage? Where does it get mounted?

Basically I need to add something like "-l $APPIMAGE/usr/share/lib/leocad/library.bin" to the command line

**Comment by probonopd** [comment]
Load the files relative from the application directory, e.g., using `QString QCoreApplication::applicationDirPath()`.
