### ISSUE TITLE
3DS export optimizations

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#105]
Not sure if this is a valid request/issue as I do not know what the 3ds export library permits but:

Could the export feature either benefit from a dialog to enable model smoothing and optimizations or by default, make the model as smooth and as clean as possible?

I currently post-process the 3ds files into blender after exporting from leocad to optimize them, removing double geometries (vertices etc) and smoothing surfaces, sadly forfeiting transparency for certain colors in the process.

see attached for comparison

3DS at https://sketchfab.com/models/a577c00b1a8b4276b59e6bab77ab8e8e
Blend at https://sketchfab.com/models/0c2597e3dab64aaeab5c358c444cd1d2

3DS
![screenshot from 2017-08-23 11-28-37](https://user-images.githubusercontent.com/5674757/29624221-8133503e-87f6-11e7-9b55-ecd87f3a55d2.png)

Blend
![screenshot from 2017-08-23 11-30-21](https://user-images.githubusercontent.com/5674757/29624225-8309b1b4-87f6-11e7-8e58-61259eb6f1cb.png)

**Comment by leozide** [comment]
Have you tried the collada exporter?

**Comment by leozide** [comment]
I took another look and the 3ds format doesn't support normals, they have smoothing groups but then it's up to the importer what to do with those groups. I'd rather not spend time on this terrible format, it has several issues.

There shouldn't be any duplicate vertices, maybe it's the Blender importer converting from indexed triangles to a triangle list.

My recommendation to use collada still stands, it's a new exporter so there could be some bugs (please report them) but the format supports more features.

**Comment by nathaneltitane** [comment]
Is the collada exporter integrated into the newer leocad?


Nathanel Titane,

*TND*esigns | Industrial + Graphic Design Solutions

Resume <https://www.dropbox.com/s/kbceyu8x5dspv3v/resume-en.pdf> | About
<http://nathaneltitane.com/about> | Portfolio <http://nathaneltitane.com> |
Blog <http://legolinux.com/> | Linkedin
<http://www.linkedin.com/in/nathaneltitane>

514 . 583 . 7386

**Comment by leozide** [comment]
You need to compile your own

**Comment by nathaneltitane** [comment]
Yeah, will do - I meant latest commit, my bad :)


Nathanel Titane,

*TND*esigns | Industrial + Graphic Design Solutions

Resume <https://www.dropbox.com/s/kbceyu8x5dspv3v/resume-en.pdf> | About
<http://nathaneltitane.com/about> | Portfolio <http://nathaneltitane.com> |
Blog <http://legolinux.com/> | Linkedin
<http://www.linkedin.com/in/nathaneltitane>

514 . 583 . 7386

**Comment by nathaneltitane** [comment]
I just compiled it, models do parse/render properly...

![screenshot from 2017-08-24 17-25-00](https://user-images.githubusercontent.com/5674757/29689453-39cf444a-88f1-11e7-909e-72de380c61a2.png)

**Comment by leozide** [comment]
Can you try the latest fix?

**Comment by leozide** [comment]
I've checked in another fix.

**Comment by nathaneltitane** [comment]
Seems to be working fine now, exported collada as well without crash.

**Comment by nathaneltitane** [comment]
So going back to the original request, any way to add pre-export settings to collada (or others) to fine tune the exported file output?

**Comment by leozide** [comment]
Do you still see the original issues you reported when you load the collada file?

**Comment by nathaneltitane** [comment]
Yes, some edges which should look sharp on some parts seem to render with a rounded aspect (the phong/smoothing values might be off)

See import, look at the arms and shins:

![screenshot from 2017-08-24 18-45-49](https://user-images.githubusercontent.com/5674757/29692126-7f57c932-88fc-11e7-974a-00783673e6db.png)

**Comment by nathaneltitane** [comment]
link to model export for you to judge:

https://skfb.ly/6t7WC

**Comment by leozide** [comment]
1- I can definitely change the material settings, I picked somewhat arbitrary values for the specular. I can use your material settings if you have something that looks good. The collada file is just xml if you want to look at what I'm using.

2&3 could be LeoCAD's normal calculation, how do they look in the app? What are the part numbers for those parts that don't have edges?

**Comment by nathaneltitane** [comment]
For comparison, a 3DS that's been optimized using blender post-export and uploaded.

In the app, all the parts render just fine.

currently, parts that are seemingly affected are from the Slopes and Wedges groups:
3300.dat
85984.dat
47759.dat
43713.dat

and similar parts...

**Comment by leozide** [comment]
They don't display correctly in app, the top edge is flat:

![image](https://user-images.githubusercontent.com/9685066/29693539-24656982-88eb-11e7-8041-dc71124b43be.png)

Looking at the mesh in Blender you can see the normals are being merged:

![image](https://user-images.githubusercontent.com/9685066/29693516-f72b626e-88ea-11e7-95fd-2bc978fc63ba.png)

**Comment by nathaneltitane** [comment]
I'm on ubuntu linux and lighting/shading does not work in LEOCAD. My bad.

**Comment by leozide** [comment]
That screenshot is from Ubuntu, did you enable lighting on the preferences? What error do you get?

I reduced the normal merging angle, now the edges are visible on those parts:

![image](https://user-images.githubusercontent.com/9685066/29693850-d6cb60d0-88ec-11e7-86d6-c527d7bca758.png)

Can you try re-exporting with the latest change?

**Comment by nathaneltitane** [comment]
Oh my, I had no idea it was fixed!! Building now.

**Comment by nathaneltitane** [comment]
Ok, so lighting is enabled :)

Here is what i see in LeoCad


![screenshot from 2017-08-24 20-16-37](https://user-images.githubusercontent.com/5674757/29694393-f071a05e-8909-11e7-8d36-b15ca72d8601.png)

and seems like the edges are much sharper as well with hte collada export. you can visit sketchfab model link to assess
