### ISSUE TITLE
OBS builds not use latest 'master' branch

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#111]
I check every OBS builds as DEB-packages for xUbuntu 16.04 and detect that since 1st August it not based on latest 'master' branch.

* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb

When I look inside this DEB as in archive file see that all files inside it dated on 31st July, but builds on OBS repo showed as updated few hours ago (look on date)

* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/

Cast @pbartfai

**Comment by Symbian9** [comment]
@pbartfai, its look like something wrong with main OBS mirror.

When I try download using next links...
* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb
* http://widehat.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb

... them give me build from 31 July 2017 (size of DEB-file 696 Kbyte)

But, when I try use another mirrors...
* http://ftp.gwdg.de/pub/opensuse/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb
* http://anorien.csc.warwick.ac.uk/mirrors/download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb

... then I got latest builds (size of current DEB-file 709 Kbyte).

What's going on here?

P.S.: "Details"
* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb.mirrorlist

**Comment by Symbian9** [comment]
@pbartfai, just check other mirrors...
* http://ftp.gwdg.de/pub/opensuse/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb
* http://anorien.csc.warwick.ac.uk/mirrors/download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb

... and its look like them also not apdated after 26 August 2017.

"Details"
instead describe that all builds must be updated
* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb.mirrorlist

Something wrong with OBS?

**Comment by Symbian9** [comment]
@pbartfai, @leozide, please, check OBS! Still work incorrectly!
* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb.mirrorlist

I highly recommend clear cashed builds and rebuild it again
* http://download.opensuse.org/repositories/home:/pbartfai/

**Comment by pbartfai** [comment]
Seems that OBS support team noticed the issue. See recent announcements on https://build.opensuse.org/

Feel free to add more info for my bug report:
https://bugzilla.novell.com/show_bug.cgi?id=1052751

**Comment by Symbian9** [comment]
> But it is present in:

@pbartfai, please, look inside each DEB from all mirrors - and you will see that all of them are outdated and not corelated with info about build!

**Comment by pbartfai** [comment]
Is the content of files outdated or only timestamp?

**Comment by Symbian9** [comment]
Those DEB's outdated (main mirror updated on 31 July; other two mirrors updated on 26 August)

But inside mirrors list file timestamp is 8 September for all builds

**Comment by Symbian9** [comment]
Well, its look like OBS download links now work correctly (I hope)

Data inside packages now same as noted inside build info
* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb.mirrorlist
