### ISSUE TITLE
Crash on Mac OS X 10.12.6

### ISSUE THREAD

**Issue by fpalluy** [leozide/leocad#112]
The app do not start....

Process:               leocad [4618]
Path:                  /Applications/LeoCAD.app/Contents/MacOS/leocad
Identifier:            com.leozide.leocad
Version:               17.07
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           leocad [4618]
User ID:               501

Date/Time:             2017-08-26 09:43:23.920 +0200
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        5409095C-0E5E-AF65-6FAE-15A4ED26359E

Time Awake Since Boot: 3500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

**Comment by leozide** [comment]
Can you see if this is the same as bug #62?

**Comment by fpalluy** [comment]
Yes, sorry, it's the same issue.

**Comment by leozide** [comment]
I've disabled update checks on macOS until Qt fixes their bug so the next version won't have this crash.

The workaround for the current version is to disable "Auto proxy discovery", then either keep it disabled or turn off automatic update checks in the app and enable proxy discovery again.
