### ISSUE TITLE
Latest LeoCad build not correctly referencing mpd submodels

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#116]
I was testeing the collada exporter to upload to my sketchfab gallery and noticed that some models (many of them) were not only partial:

The submodel references made in the model file are not read correctly: the file's path is being referenced rather than it's import data into the mpd for some reason.

Here is the visual of the mpd model files when opened on the latest build:

![screenshot from 2017-08-28 21-26-27](https://user-images.githubusercontent.com/5674757/29800407-e801302a-8c37-11e7-9de2-183d66b6ddc5.png)

![screenshot from 2017-08-28 21-26-34](https://user-images.githubusercontent.com/5674757/29800408-e9bccd84-8c37-11e7-9091-16e76589209f.png)

Export and upload result here:

https://sketchfab.com/models/e10b5a55de3e4401a8b1b29508dbbdff

Expected result - since they are based on the same master file:

![screenshot from 2017-08-28 21-30-15](https://user-images.githubusercontent.com/5674757/29800435-26da38dc-8c38-11e7-8601-7a8737073e2a.png)

![screenshot from 2017-08-28 21-30-23](https://user-images.githubusercontent.com/5674757/29800437-27fe9e88-8c38-11e7-858b-2a1e2db6a2bf.png)

**Comment by leozide** [comment]
Do you have a file with the submodel name in the same folder as the mpd file?

**Comment by nathaneltitane** [comment]
Yes, always.

**Comment by nathaneltitane** [comment]
But even so, the data is imported using a merge from an individual ldr into the mpd... it shouldn't refer to the external path afaik.

**Comment by nathaneltitane** [comment]
Here'S another instance of it happening while editing the latest model i'm upgrading...

During edit:
![screenshot from 2017-08-28 23-39-45](https://user-images.githubusercontent.com/5674757/29803499-567ef700-8c4a-11e7-8d33-9c8565a2f8e5.png)

After reopening file:
![screenshot from 2017-08-28 23-39-59](https://user-images.githubusercontent.com/5674757/29803503-5bf9066c-8c4a-11e7-88aa-06c15fde5b36.png)

Model file directory:
![screenshot from 2017-08-28 23-41-17](https://user-images.githubusercontent.com/5674757/29803510-67f26d96-8c4a-11e7-893a-d98910766a4f.png)

Model file for inspection:
https://www.dropbox.com/s/ey6kz6o0kh9mes1/00-xxxg-00w0-wing-zero-custom.mpd

**Comment by leozide** [comment]
I think the bug is that it's loading the loose files instead of the files inside the mpd. I'll take a look.

**Comment by leozide** [comment]
I think I fixed this, couldn't really repro with your file.

**Comment by nathaneltitane** [comment]
Confirmed, all good now - thanks!
