### ISSUE TITLE
Cannot export piece 3811 (32 x 32 baseplate) as .3ds

### ISSUE THREAD

**Issue by AlexGustafsson** [leozide/leocad#118]
I've stumbled upon a pretty weird issue. Whenever I export a model containing the piece or simply the piece itself it ends up being missing from the resulting 3D file. Exporting as .obj works.

To replicate:

1. Open a new file
2. Add piece 3811 (32 x 32 baseplate)
3. Export as .3ds

Following the above steps results in a .3ds file containing only 32kB.

**Comment by leozide** [comment]
This is a limitation of the 3ds format, it only supports meshes with up to 65535 vertices but a few of the bigger baseplates have more than that so they aren't exported. I recommend exporting as Collada, it has other advantages over 3ds as well.
