### ISSUE TITLE
Voxel featurues (ideas)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#121]
Some ideas for implementing "voxel" features into  LeoCAD

* [ ] Import 2D image as 3D model
consisted from bricks
  * [ ] import 2D heightmap
as 3D model of surface
    * http://en.wikipedia.org/wiki/Heightmap
    * https://github.com/esimov/legoizer
    * https://github.com/myrtleTree33/lego-mosaic
    * http://sailorhg.github.io/legoizer/
    * https://github.com/hryniuk/legolize
    * https://github.com/roliveira/legofy
  * ...
* [ ] Import voxel file formats
as 3D model consisted from bricks
  * https://en.wikipedia.org/wiki/DICOM
  * https://github.com/aliekens/m2legovoxels
  * https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt
  * https://docs.blender.org/manual/ko/dev/render/blender_render/textures/types/volume/voxel_data.html
  * https://abfab3d.com/svx-format/
  * https://www.reddit.com/r/3Dprinting/comments/642nwq/voxelbased_file_formats/
  * ...
* [ ] Import polygonal 3D mesh as voxel-like 3D model consisted from bricks
  * https://code.google.com/archive/p/lsculpt/
    * https://github.com/LEGOUniverseArchive/lsculpt
  * https://github.com/kunalagrawal1995/Legolizer
  * https://github.com/AaronMorais/TheParallaxProject
  * ...
* [ ] Export 3D model consisted from bricks into voxel formats
  * ...

**REFERENCE**

* https://en.wikipedia.org/wiki/Voxel
* http://lego.bldesign.org/LSculpt/lambrecht_legovoxels.pdf
* https://github.com/BijoySingh/Legolization-Computer-Graphics
* https://github.com/fehy/legolize
* http://susanevans.org/blog/lego-human-anatomy/
* https://upperplayground.com/blogs/news-upperplayground/lego-sculptures-by-nathan-sawaya
* http://www.ericharshbarger.org/lego/heart.html
* http://www.inspirefusion.com/lego-heart/

**Comment by posfan12** [comment]
What do people use voxels for outside of LEGO and Minecraft? Is it a popular method of doing 3D?

**Comment by j6t** [comment]
A list of links is not very helpful: not everybody knows what Voxels are and how they can help a Lego build. Can you please be a bit more specific what you actually want? Otherwise, I would suggest to close this issue.
