### ISSUE TITLE
Remove "Shading Mode" from "Preferences..." dialog

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#122]
Since menu entry "View -> Shading" now work much better than same option in "View -> Peferences..." dialog.

Menu entry "View -> Shading" is much faster way for change shading mode, so no need duplicate this option in different dialogs

**Comment by leozide** [comment]
They serve different purposes, the Preferences Dialog changes the default mode next time you start the app, while the menu is for temporary changes during the current session only.

**Comment by Symbian9** [comment]
> Preferences Dialog changes the default mode next time you start the app,

Not true, some of options change look in main window immediatly.

Also, especially for "Shadow Mode" option - it applied immediatly in main window, but in parts window previews of first few parts keept as previouse mode work - if scroll down in parts window you will see what I mean

**Comment by leozide** [comment]
Preferences Dialog changes both the current instance and future instances when possible.

I've fixed the shading mode not applying to the preview immediately.
