### ISSUE TITLE
Some of builds not include "Set Inventory..." import entry

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#123]
I just tested few builds based on commit `be388d1` produced by Travicls CI autobuild

* In `LeoCAD-git.be388d1.qt48-x86_64.AppImage` menu entry *"File -> Import -> Set Inventory..."* **not exist!**
* In `LeoCAD-git.be388d1.qt57-x86_64.AppImage` menu entry *"File -> Import -> Set Inventory..."* exist.

**Comment by leozide** [comment]
It needs Qt5

**Comment by Symbian9** [comment]
> It needs Qt5

@pbartfai, could you setup OBS for producing Qt4 and Qt5 builds?

For example, if for Xenial Qt5.5 is default version, please, build next packages

1. [ ] http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_qt48_amd64.deb
2. [ ] http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_qt55_amd64.deb

**Comment by pbartfai** [comment]
It is not easy to build both Qt 4.x and 5.x. It would be easier to create another project leocad-qt5. I did the same for LDView.

**Comment by leozide** [comment]
Wouldn't it make more sense to have the default be Qt5 and create a leocad-qt4 instead?
