### ISSUE TITLE
Qt3D framework (Qt5.9+)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#124]
https://github.com/MidoriYakumo/learnopengl-qt3d

![Qt3D](https://raw.githubusercontent.com/MidoriYakumo/learnopengl-qt3d/master/doc/img/ss-qml.png)

### REFERENCE
* http://blog.qt.io/blog/2016/06/16/introducing-qt-3d/
* https://wiki.qt.io/Qt3D
* https://doc.qt.io/qt-5/qt3d-overview.html

**Comment by leozide** [comment]
This doesn't bring any useful features and I don't want to require Qt 5.9
