### ISSUE TITLE
Sphere generator

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#126]
Is it possible add it in LeoCAD?
* https://github.com/nathanbain314/sphere-generator

Cast @nathanbain314

![Type 2](https://camo.githubusercontent.com/dd36e3aaab2014880d6af126b27e838407fa0b22/687474703a2f2f6e617468616e6261696e2e636f6d2f636769742f7370686572652d67656e657261746f722e6769742f706c61696e2f6578616d706c65732f54797065322e706e67)
![Type 5](https://camo.githubusercontent.com/990d540a66b79d5dc63cefc76c81fce23ee643a9/687474703a2f2f6e617468616e6261696e2e636f6d2f636769742f7370686572652d67656e657261746f722e6769742f706c61696e2f6578616d706c65732f54797065352e706e67)

**Comment by j6t** [comment]
This is such a special application. Does it have to be in LeoCAD? Do you want to hold on to your suggestion or can this be closed?
