### ISSUE TITLE
Properties dialog popups out of boundary

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#129]
I've recently noticed that the popups (specifically the color palette) tends to show out of bounds. When the window is maximized, the right hand sde of it (in my case) is completely cut-off and inaccessible.

Can it be fixed?

Please see attached image for detail

![screenshot from 2017-11-03 12-13-55](https://user-images.githubusercontent.com/5674757/32385487-ba554be8-c094-11e7-9f4a-603f8cc6680b.png)

**Comment by leozide** [comment]
Are you talking about the popup or the tooltip? I don't have control over the tooltip, it's displayed by Qt.

This works correctly for me, what version of Qt are you using?

**Comment by nathaneltitane** [comment]
Built on the latest Qt4.x on Ubuntu 17.10 Wayland session.

Actually, you're right, it's behaving weird: it does not reproduce on the attached monitor...
