### ISSUE TITLE
Is it possible to have the last version of Leocad for Debian Jessie stable ?

### ISSUE THREAD

**Issue by openelearning** [leozide/leocad#13]
Hello,
I just discovered LeoCad and I love it, thanks for this beautiful tools.
I'm using Debian Jessie, and the version in the depot is the 0.80.3
Someone know how can I have easily a recent version ? (ie : using appImage, Snapd, an extra depot, building it from the sources...)
Thanks a lot

**Comment by leozide** [comment]
You can build from source with something like:
wget https://github.com/leozide/leocad/archive/v0.83.2.tar.gz
tar zxf v0.83.2.tar.gz leocad
cd leocad
qmake leocad.pro
make

See http://www.leocad.org/docs/compiling.html

**Comment by probonopd** [comment]
I have generated an [AppImage](http://appimage.org/):
https://bintray.com/probono/AppImages/LeoCAD#files

**Comment by openelearning** [comment]
Thanks a lot guys for your help, i tried the Appimage, it works very fine :)
