### ISSUE TITLE
Add option for switch Qt5 themes in "Settings" dialog

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#131]
When I try autobuilds produced by Travis CI sew that there is some issue with Qt themes
* Qt48 build built with predefined "GTK+" theme
* Qt57 build built with predefined "Windows" theme

As for me it would be much better set Qt57 build to use "Fusion" theme by default.
* http://blog.qt.io/blog/2012/10/30/cleaning-up-styles-in-qt5-and-adding-fusion/
* http://doc.qt.io/qt-5/gallery-fusion.html
* https://bbs.archlinux.org/viewtopic.php?id=160206

So, add possibilty for user choose any of this theme throw settings dialog.

P.S.: cheating way
* https://askubuntu.com/questions/716714/change-qt5-theme
* https://www.pcsuggest.com/qt5ct-change-qt5-application-style/

**Comment by leozide** [comment]
You can just run 'leocad -style fusion'.

**Comment by Symbian9** [comment]
> You can just run 'leocad -style fusion'.

Well, it also work for AppImage...
```
$ ./LeoCAD-*.AppImage -style fusion
```

... but command line options not good for kids.

Anyway, it would be much better set "Fusion" theme as default for all Qt builds before next release. "Fusion" is look much better than other Qt themes.

**Comment by Symbian9** [comment]
Reviewed & extended feature request moved to https://github.com/leozide/leocad/issues/396
