### ISSUE TITLE
Force Z axis alignment when using part or assembly as placement reference

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#132]
When selecting a part or assembly as reference to place another part or assembly within a model, the new element being placed often ends up being put at an infinite cross axis rather than being placed directly over or at the reference component's coordinates.

Can be reproduced easily if using the left or right viewpoints while placing something in after having selected a part as placement reference.

Can that be fixed?

**Comment by leozide** [comment]
I don't undestand this, can you give me an example?

**Comment by nathaneltitane** [comment]
Step 1: open a complex model
Step 2: set Ortho view and use right or left viewpoint
Step 3: select a part on the model as a reference (blue)
Step 4: drag new part from list onto reference for placement

Expected result: New part will appear to be directly on top of reference, although t may actually be situated at x or y infinity rather than directly over with a slight z offset

**Comment by leozide** [comment]
This works for me, if I add a 1x1 brick and then drag another one on top it gets added at the right position.

**Comment by nathaneltitane** [comment]
@leozide it does, and works fine for simple assemblies. Not for super complex ones involving some of my builds though...

Oh well. I'll deal :)

**Comment by leozide** [comment]
Send me an example and I'll fix.
