### ISSUE TITLE
Clean up wireframe view

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#133]
Is there any chance or possibility of having LeoCAD only render the essential primitive lines when using wireframe view?

Here's an example i'm currently dealing with and it looks pretty intense.

Removing the conditionals could make it more digest.

![screenshot from 2017-11-10 12-27-36](https://user-images.githubusercontent.com/5674757/32670826-015f3c00-c613-11e7-9986-1fd0d004dd1a.png)

**Comment by nathaneltitane** [comment]
@leozide, what do you say?

**Comment by leozide** [comment]
I was planning to draw edges only, haven't had time to work on it.

**Comment by nathaneltitane** [comment]
Thank you Leo.
