### ISSUE TITLE
[suggest] select partsID and find file

### ISSUE THREAD

**Issue by wazazazak** [leozide/leocad#138]
I would like the parts ID to be selected when I search with parts selected. I tried to add it myself, but I need to create too many functions to get the currently selected Parts ID, so I will suggest it as an issue first.

**Comment by leozide** [comment]
I'm not sure I understand what you want but see if  3a055a4 works like you're suggesting. It will use the currently selected part for the first search and also has a few small improvements to that dialog.

**Comment by nathaneltitane** [comment]
I was about to open another ticket concerning part search and selection.
The current find/find previous/find next is interesting although somewhat lacking:
It would be nice to have the actual part ID (and not description) listed, or rather, add the part ID to visually confirm the selection.

I personally often refer to the actual par ID (ex.: 4286.dat - Slope brick 33 3x1) For purchases and model updates to new part specifications.
At best, the description is indicative of what you are looking for but does not ascertain the selection IMO.

Also, it would be interesting, in that same manner, to create a 'Select by part' dialog that would enable selecting and editing all parts with the same ID as the currently selected part (w/o dialog).

**Comment by leozide** [comment]
I think you want something like LDD has, where you can select by part and/or color.

**Comment by nathaneltitane** [comment]
Interesting, never used LDD: MLCAD had it. But yeah, essentially that would be great!

**Comment by leozide** [comment]
I've added the new selection mode, if there are any issues with it then let's start a new issue to avoid hijacking this one.

I believe the Search Dialog is now working better. If there are still any issues with it then please reopen this ticket.
