### ISSUE TITLE
Improvement: Deselect part feature

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#140]
There currently exists a variety of selection tools in under the edit menu bu no single part deselect option/feature. It would also be wise to enable that selection in the view port right-click context menu to deselect active part on the file.

This is especially helpful when reordering or organising selections and prevents unwanted deselection of a group by going to the parts timeline to look for it.

Thank you!

**Comment by leozide** [comment]
I've added shift+click for deselect.
