### ISSUE TITLE
Bug: Snap increment switch not possible while part is selcted

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#141]
If a part or assembly is selected (blue), one cannot switch the snap increment using keyboard shortcuts to adjust movement steps and placment of said selection.

How to reproduce:
1 - have multiple parts in model
2 - Select part (blue) for rotation or translation
3 - use assigned keyboard shortcut to change snap stepping
>>>Stepping does not change and will only do so upon full deselection.

**Comment by leozide** [comment]
I added 2 1x1 bricks, pressed the 1..9 keys to change snap and the selected part moved correctly.

**Comment by nathaneltitane** [comment]
Not with more complex combinations.

I have Ctrl+number for rotation increment and Shift+number for Z axis increment, those do not work upon selection or function differrently than from previous builds.

**Comment by leozide** [comment]
I tried Ctrl+number, Shift+Number and Ctrl+Shift+Number and they all work. Is this model specific? Can you repro with a new model with just a few bricks?

**Comment by nathaneltitane** [comment]
it was an mpd. don't know if it has any leverage in the matter. Doesn't seem to reproduce anymore, ldr or mpd.. strange :(

**Comment by nathaneltitane** [comment]
Here is the model assembly, main mpd file and ldrs
See if you can figure it out, if not the no biggie.

[xxxg-01sr2-sandrock-custom.zip](https://github.com/leozide/leocad/files/1493254/xxxg-01sr2-sandrock-custom.zip)
