### ISSUE TITLE
Bug: View roll/pan/rotate viewport issue

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#142]
The Roll/pan/rotate POV tool that is usually overlayed on the model when triggering the roll view tool does not appear and makes the POV placement imposiible.

Please fix.

Please see attached

![screenshot from 2017-11-21 16-17-01](https://user-images.githubusercontent.com/5674757/33097414-1e57c8e0-ced8-11e7-96b5-5cc9b3d983a4.png)

**Comment by leozide** [comment]
I'm not sure I understand what the problem is, do you mean the toolbar is not visible? If that's it then you can show it from the view menu and the app will remember it next time you launch it.

The view tools are working as far as I can tell.

**Comment by nathaneltitane** [comment]
No. Usually there is a circular overlay with handles that is drawn on the viewport (possibly camera handle?) to roll the view according to the circle's quandrants.

I'm sure it was present up until the most recent commits.

**Comment by leozide** [comment]
It's working for me, but in your screenshot you have the roll tool selected, the rotate camera is the one that shows the squares for rotating.

![image](https://user-images.githubusercontent.com/9685066/33099526-01621158-cec6-11e7-8d97-fef1196d54d5.png)

**Comment by nathaneltitane** [comment]
um, very strange again, none would show earlier, with that same mpd i was working on. dammit. i look like a fool, seems to function now....

**Comment by leozide** [comment]
There could be a combination of things (shading, selection, etc) that make it not show up. Let me know if you can get it to happen again.
