### ISSUE TITLE
Timeline panel is not displayed

### ISSUE THREAD

**Issue by laspic** [leozide/leocad#144]
Hello,

I'm just testing Leocad which seems to works fine on my computer (Ubuntu 16.04). However one thing is strange : I've no timepanel like the one we can see on the tutorial screenshots. I also precise that it doesn't appear it the View > Toolbar menu. Here is a screenshot.

Note that the timeline toolbar is well displayed and seems to works well for its part

What do I miss ? What happens ?

![capture d ecran_2017-11-26_15-25-15](https://user-images.githubusercontent.com/3339204/33240873-122763fc-d2be-11e7-9cf8-e976eb07682d.png)

**Comment by leozide** [comment]
Looks like the version you're using is a few years old. Check Help ->About, the current version is 17.07. 

You can download the latest from https://github.com/leozide/leocad/releases/latest

**Comment by laspic** [comment]
Oh, sorry. I didn't thought the repository version should be so much outdated. :-/
Thank you for your quick response.
