### ISSUE TITLE
HTML export from command line, parametrised

### ISSUE THREAD

**Issue by mirabilos** [leozide/leocad#145]
Hi,

would you accept upstream a patch to export as HTML from the command line, with anti-aliasing enabled, and the other options such as size being parametrised via command line parameters?

I’ve not yet created the patch, merely seen that, while viable, it’s going to be a bit of work.

**Comment by leozide** [comment]
Sure, this should be simple:

- Change lcApplication::Initialize to parse the new arguments
- Make Project::ExportHTML take a const lcHTMLDialogOptions& parameter, move the top of the function (up to the first QDir line) into a new function (say, lcMainWindow::ExportHTML) and update HandleCommand to call it instead.

Note that AA isn't working when saving images, there's already a bug for that.

**Comment by mirabilos** [comment]
Hi Leonardo,

>Sure

thanks! I’ll likely invest a bit in the following weeks
(also having to write a script parsing the HTML output
and creating LaTeX from it, hence the need for relatively
large bitmaps).

>this should be simple:
>
>- Change lcApplication::Initialize to parse the new arguments
>- Make Project::ExportHTML take a const lcHTMLDialogOptions&
>  parameter, move the top of the function (up to the first QDir line)
>  into a new function (say, lcMainWindow::ExportHTML) and update
>  HandleCommand to call it instead.

That’s about what I concluded as well, thanks.

>Note that AA isn't working when saving images, there's already a bug for that.

Okay, but it won’t hurt to set the flag when leocad is called with
the export parameter, right?

I’d prefer to not require the user to manually start leocad and set
that just to be able to convert files in an automated manner.

Thanks,
//mirabilos
-- 
FWIW, I'm quite impressed with mksh interactively. I thought it was much
*much* more bare bones. But it turns out it beats the living hell out of
ksh93 in that respect. I'd even consider it for my daily use if I hadn't
wasted half my life on my zsh setup. :-) -- Frank Terbeck in #!/bin/mksh

**Comment by nathaneltitane** [comment]
@leozide where's the cli html flag?

**Comment by leozide** [comment]
-html

**Comment by leozide** [comment]
I didn't know people actually used the html exporter, I've been thinking about removing it.

**Comment by nathaneltitane** [comment]
just built, not there....

![screenshot from 2017-12-11 16-58-59](https://user-images.githubusercontent.com/5674757/33855958-9dba6194-de94-11e7-9f9c-0a7eefd3ae51.png)

**Comment by leozide** [comment]
I've added it now

**Comment by mirabilos** [comment]
> I didn't know people actually used the html exporter, I've been thinking about removing it.

HTML is the **only** leocad export format that allows us to get the individual steps. We’re attempting to create a Free construction manual for NXT robots, so we’re trying to get leocad to output something that we can convert, using shell scripts and separately-kept instructions for each steps, into PDF via LaTeX.

**Comment by nathaneltitane** [comment]
@mirabilos sounds like a nightmare - steer away from latex

**Comment by leozide** [comment]
> HTML is the only leocad export format that allows us to get the individual steps. We’re attempting to create a Free construction manual for NXT robots, so we’re trying to get leocad to output something that we can convert, using shell scripts and separately-kept instructions for each steps, into PDF via LaTeX.

My comment was more about how ugly the html output is, and that I really need to update it.

You can save PDF files directly from LeoCAD (Print as PDF), or are you making other changes to the pages? If you only need images then you don't need to go through the html export, you can save them for each step directly from the command line.

I'll look into adding the requested options to the command line when I get a chance.

**Comment by mirabilos** [comment]
Nathanel Titane dixit:

>@mirabilos sounds like a nightmare - steer away from latex

The Teχ part is not giving us any problems. We’ve got tons of Free
material (*real* Open Educational Ressources) in LaTeX, complete
with a style for public materials from our charity that includes
header, footer, logo, licence annotations, helpful macros, and
all that.


Leonardo Zide dixit:

>> HTML is the only leocad export format that allows us to get the
>> individual steps. We’re attempting to create a Free construction
>> manual for NXT robots, so we’re trying to get leocad to output
>> something that we can convert, using shell scripts and
>> separately-kept instructions for each steps, into PDF via LaTeX.
>
>My comment was more about how ugly the html output is, and that I

Indeed it’s ugly, but it’s there, and…

>really need to update it.

… changing the output now would mean more effort for our project
because we transform it algorithmically.

If you think nobody’s using it (as-is), keep it as-is.

>You can save PDF files directly from LeoCAD (Print as PDF), or are you
>making other changes to the pages? If you only need images then you
>don't need to go through the html export, you can save them for each
>step directly from the command line.

Well, we *are* adding descriptions to the steps and putting it into
the public material template I mentioned above.

We need a list of steps, the images for each, and the HTML part list
because the image part list is also too low-resolution. (Also, we
don’t distinguish between parts of different colours in our part
lists because we don’t have enough parts (or, we have too many work‐
shop participants ☺) to be picky about colours.)

Also, I’ve not found out how I could get each step from the command
line. (At the current point in time, we need our HTML→Teχ process to
be compatible with leocad 0.83.1-1 from Debian stable, in case that
matters; we’re using manual GUI-induced HTML export for now.)

>I'll look into adding the requested options to the command line when I
>get a chance.

Thanks. My initial request was just for asking whether you’d take a
patch — then I’d have hacked it, so you already did more than asked.

**Comment by leozide** [comment]
> If you think nobody’s using it (as-is), keep it as-is.

There were some small changes to the html output since 0.83, from what I remember I only added support for a BOM-style parts list image at the end of a model so it probably won't break you.

> Also, I’ve not found out how I could get each step from the command line.

You can only get the images (using -from and -to) so it won't work for you.
