### ISSUE TITLE
Import Catia, AutoCad model?

### ISSUE THREAD

**Issue by CalaVerra** [leozide/leocad#148]
Hi everyone,

I'm new to GitHub and I was looking for a software that allows me to import a Catia or an Autocad projects and transforme one of these project in a Lego model. Did you know a application that can do that? Or maybe LeoCad is already able to do it? 

In advance thanks for your answers. :)

**Comment by leozide** [comment]
You can try LSculpt: http://lego.bldesign.org/LSculpt/index_old.html
