### ISSUE TITLE
Image out AA/render options

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#149]
Current image output does not offer AA/Rendering options, thus resulting in a render depending on whichever setting (minus AA) is enabled in the config.

See attached for comparison.

![screenshot from 2017-12-13 13-02-32](https://user-images.githubusercontent.com/5674757/33954316-ed91d022-e005-11e7-992a-b67d35326cd4.png)

**Comment by leozide** [comment]
Duplicate of #101

**Comment by nathaneltitane** [comment]
Any fix?
