### ISSUE TITLE
Make all tool panels dockable/stackable on any side of main window

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#15]
Please enable all panels (specifically properties and timeline) to dock on all sides of main LeoCad window, just like Parts, Colors, etc.

Another cool feature would be to enable split panel functionality, where, when put together on any side, each panel would automatically split the overall width or height of the window side preview into 1/n 

3 tool panels = 1/3 of view for each panel (width or height)

Thanks

**Comment by leozide** [comment]
I've enabled docking anywhere but I don't have a way to automatically split panels.
