### ISSUE TITLE
Submodel update issue

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#150]
Been updating some submodels in certain mpd files: the submodel entry gets rendered as the latest iteration, but all referencing submodels keep the old entry somehow...

see attached for details (same mpd, shin entry is new, shin reference in foreleg hinge is old - model file is also attached) 

![screenshot from 2017-12-15 11-00-52](https://user-images.githubusercontent.com/5674757/34050081-932d597a-e187-11e7-94ff-93106b9bf192.png)
![screenshot from 2017-12-15 11-01-00](https://user-images.githubusercontent.com/5674757/34050082-933946e0-e187-11e7-8a8a-c7f7025a5d06.png)

Model:
[gat-x103-buster.zip](https://github.com/leozide/leocad/files/1563254/gat-x103-buster.zip)

**Comment by leozide** [comment]
It looks like there are 2 submodels called 02-shin.ldr inside that mpd. The spec isn't clear about duplicate files and search order but I don't think they should be allowed and internally LeoCAD can't handle this well. Can you just rename the old submodel?

**Comment by nathaneltitane** [comment]
OMG wow.. i have no idea how that happened, there's a whole duplicate of the model inside the mpd. Sorry about that
