### ISSUE TITLE
Trying to compile leocad for armhf under ubuntu 16.10 (chroot CrOS)

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#16]
Getting this error on initial stages of build process:

g++ -pipe -std=c++11 -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DLC_INSTALL_PREFIX=\"/usr\" -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -Iqt -Icommon -I/usr/X11R6/include -Ibuild/release/.moc -Ibuild/release/.ui -x c++-header -c common/lc_global.h -o build/release/.obj/leocad.gch/c++
In file included from common/lc_global.h:15:0:
common/lc_glext.h:468:19: error: conflicting declaration 'typedef ptrdiff_t GLsizeiptr'
 typedef ptrdiff_t GLsizeiptr;
                   ^~~~~~~~~~
In file included from /usr/include/qt4/QtOpenGL/qgl.h:79:0,
                 from /usr/include/qt4/QtOpenGL/QtOpenGL:5,
                 from common/lc_global.h:6:
/usr/include/GLES2/gl2.h:69:25: note: previous declaration as 'typedef khronos_ssize_t GLsizeiptr'
 typedef khronos_ssize_t GLsizeiptr;
                         ^~~~~~~~~~
In file included from common/lc_global.h:15:0:
common/lc_glext.h:469:19: error: conflicting declaration 'typedef ptrdiff_t GLintptr'
 typedef ptrdiff_t GLintptr;
                   ^~~~~~~~
In file included from /usr/include/qt4/QtOpenGL/qgl.h:79:0,
                 from /usr/include/qt4/QtOpenGL/QtOpenGL:5,
                 from common/lc_global.h:6:
/usr/include/GLES2/gl2.h:70:26: note: previous declaration as 'typedef khronos_intptr_t GLintptr'
 typedef khronos_intptr_t GLintptr;
                          ^~~~~~~~
In file included from common/lc_global.h:15:0:
common/lc_glext.h:6452:51: error: typedef 'PFNGLDEPTHBOUNDSEXTPROC' is initialized (use decltype instead)
 typedef void (APIENTRYP PFNGLDEPTHBOUNDSEXTPROC) (GLclampd zmin, GLclampd zmax);
                                                   ^~~~~~~~
common/lc_glext.h:6452:51: error: 'GLclampd' was not declared in this scope
common/lc_glext.h:6452:66: error: 'GLclampd' was not declared in this scope
 typedef void (APIENTRYP PFNGLDEPTHBOUNDSEXTPROC) (GLclampd zmin, GLclampd zmax);
                                                                  ^~~~~~~~
Makefile:340: recipe for target 'build/release/.obj/leocad.gch/c++' failed
make: *** [build/release/.obj/leocad.gch/c++] Error 1

Can it be fixed?

**Comment by leozide** [comment]
Can you give me instructions on how to repro this?

**Comment by nathaneltitane** [comment]
Hey Leo!

I set up an Ubuntu ARMHF chroot using the crouton project on my chromebook.

Once the environment and session are loaded and done setting up, I simply went through and downloaded the necessary packages and source to start compiling.

I'm pasting the contents of the compilation script I use to do so, which normally produces the binary I normally use under x86_64 builds.

BEGIN SCRIPT___

#!/bin/bash

set -e

# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016

shopt -s extglob globstar nullglob

# leocad build #

black= red= green= yellow= blue= magenta= cyan= white= reset=

if [[ -t 1 ]]
then
	black=$(tput setaf 0)
	red=$(tput setaf 1)
	green=$(tput setaf 2)
	yellow=$(tput setaf 3)
	blue=$(tput setaf 4)
	magenta=$(tput setaf 5)
	cyan=$(tput setaf 6)
	white=$(tput setaf 7)
	reset=$(tput sgr0)
fi

version="19-10-2016"

source="https://github.com/leozide/leocad.git"

directory=$(mktemp -d)
trap 'rm -rf "$directory"' EXIT

binary_directory="/usr/bin"
tree_directory="$directory/git"
build_directory="$tree_directory/leocad"
ldraw_applications_directory="/media/Disk/Dropbox/Lego"
source_binary_directory="$build_directory/build/release"
ldraw_binary_directory="/media/Disk/Dropbox/Lego/leocad"

home="/home/${SUDO_USER:-$USER}"
configuration_directory="$home/.config/"

echo "${cyan}Adding QT system config (trolltech)...${reset}"

cat > "$configuration_directory"/Trolltech.conf << 'FILE'
[Qt]

style=GTK+
FILE

# Link QT configuration file for newer build setups

ln -s -f "$configuration_directory"/Trolltech.conf "$configuration_directory"/gtk-3.0/Trolltech.conf

if [[ "$directory" ]]
then
	: # pass
elif [[ ! "$directory" ]]
then
	echo "${yellow}Warning: No base directory specified. Please select a directory in which the build process will be carried out.${reset}"

	# Specify directory location or exit on 'Cancel'

	directory=$(zenity --directory --file-selection  --multiple --separator=$'\n' --title="Select a Directory") || exit
else
	echo "${red}No directory specified. Aborting...${reset}"

	exit 1
fi

if [[ ! -d "$tree_directory" ]]
then
	mkdir -p "$tree_directory"
fi

if [[ "$ldraw_binary_directory" ]]
then
	: # pass
elif [[ ! "$ldraw_binary_directory" ]]
then
	echo "${yellow}Warning: No base system directory specified for binary operation. Please select a directory in which the built binary will be copied to to be run.${reset}"

	# Specify directory location or exit on 'Cancel'

	ldraw_binary_directory=$(zenity --directory --file-selection  --multiple --separator=$'\n' --title="Select a Directory") || exit
else
	echo "${red}No directory specified. Aborting...${reset}"

	exit 1
fi

echo "${cyan}Verifying build dependencies...${reset}"

packages=(
	git
	g++
	qt4-dev-tools
	zlib1g-dev
	)

for package in ${packages[@]}
do
	sudo apt-get -y install "$package"
done

echo "${cyan}Fetching updated source tree from $source...${reset}"

if [ -d "$build_$directory" ]
then
	rm -rf "$build_directory"
	wait
fi

cd "$tree_directory" || exit

git clone "$source" "$build_directory"

echo "${cyan}Building updated binary (make)...${reset}"

cd "$build_directory" || exit

qmake-qt4
make

echo "${cyan}Copying updated binary (leocad)...${reset}"

cd "$source_binary_directory" || exit

if [ -e "$ldraw_binary_directory/leocad" ]
then
	rm -rf "$ldraw_binary_directory/leocad"

	cp "$source_binary_directory/leocad" "$ldraw_binary_directory/leocad"
else
	cp "$source_binary_directory/leocad" "$ldraw_binary_directory/leocad"
fi

if [ "$(which leocad)" != "" ]
then
	rm -rf "$(which leocad)"

	ln -s -f "$ldraw_binary_directory/leocad" "$binary_directory/leocad"
fi

echo "${cyan}Done.${reset}"

END SCRIPT___

**Comment by leozide** [comment]
I don't have a chromebook so I can't duplicate your setup but looks like the problem is caused because it has GLES instead of regular OpenGL, so even if it compiles there are probably more things that need to be fixed to get it to work.

I'll look for a way to get GLES headers and libs and that may be enough to get you running.

**Comment by nathaneltitane** [comment]
Cool! Thank you :)

**Comment by leozide** [comment]
Post a new error log if it's still not compiling.
