### ISSUE TITLE
POV-Ray fails to render model

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#160]
Running under Ubuntu Linux,
POV-ray binary installed and located under /usr/bin/

Added location to preferences
 When Selecting the maon model and requesting a render using 512x512px and low resolution, no output is created and preview canvas disappears.

**Comment by leozide** [comment]
Are you sure you have db7c0f8edf8dafb71e98601a679a8649639c579c?
What version of povray do you have?

**Comment by nathaneltitane** [comment]
povray --version
POV-Ray 3.7.0.unofficial

**Comment by Symbian9** [comment]
@nathaneltitane, what OS you use? (Linux, Windows, macOS)

>  no output is created and preview canvas disappears.

Did you set path to POV-Ray binary? Here is how it look like on Linux:
![LeoCAD POV-Ray path](http://pasteall.org/pic/show.php?id=126068)

I just test https://github.com/leozide/leocad/commit/5ac11506b0d876d291b28dd2ad2dc046341a62a3 builds on Linux, and can get preview...

![LeoCAD POV-Ray test](http://pasteall.org/pic/show.php?id=126069)

... *but there no any output saved and I can't save it as image in file! After clicking `Save` button nothing happened!*
![LeoCAD POV-Ray has no any output!](http://pasteall.org/pic/show.php?id=126070)

Also, there no any errors in terminal output

```$ ./LeoCAD-git.5ac1150.qt57-x86_64.AppImage

```

@leozide, so it's look like a bug on rendering output saving!

**Comment by nathaneltitane** [comment]
I always use Linux, and yes, I've set the path to the installed binary as shown (I'm no novice :) to POV)

I just didn't get any output in the window... Could it be model related? I tried with an mpd.

**Comment by leozide** [comment]
@nathaneltitane Can you try rendering a 1x1 brick? It looks like povray found an error but I don't print the error messages, I'll have to check something in.

**Comment by nathaneltitane** [comment]
@leozide so eversince filing the bug, i've switched back to fedora (27) - did a clean install of everything and i can confirm that POVRay functions on both ldr and mpd - although, when selecting the save path, no file gets put in the selected directory and the initial povray dialog also cuts off the render combo dialog and options boxes... it only gets resized upon pixel size regen for the output preview (see attached)

ldr:

![screenshot from 2018-02-08 20-58-20](https://user-images.githubusercontent.com/5674757/36007941-cf029562-0d12-11e8-8711-ac5db2b45a20.png)

mpd:

![screenshot from 2018-02-08 20-59-44](https://user-images.githubusercontent.com/5674757/36007982-063e34b4-0d13-11e8-913c-6bab21811bdd.png)

dialog cutoff:

![screenshot from 2018-02-08 20-57-50](https://user-images.githubusercontent.com/5674757/36007929-be35d7bc-0d12-11e8-8c29-2733ed426a18.png)

**Comment by Symbian9** [comment]
@leozide, are there any news?

Because still can't save rendered image to file on Linux.

**Comment by tcuje** [comment]
Same issue here on Linux. The rendered image is not saved, since the code is excluded by the precompiler. I can fix it, but I can't test it on Windows afterwards.
