### ISSUE TITLE
Pan mode stops working when zoomed in very far

### ISSUE THREAD

**Issue by posfan12** [leozide/leocad#161]
I am working on Datsville. When I zoom in real close, the "pan" mode stops working and I am unable to pan the camera up and down or side-to-side. If I zoom out it starts working again. "Rotate view" mode seems unaffected.

**Comment by leozide** [comment]
I've had other people complain about this same problem, but I can't get this to happen for me so I can't fix it. Can you post exact steps to get this to happen?

**Comment by Symbian9** [comment]
Confirmed. Reproducable issue for me too.

1. Run LeoCAD;
2. Switch to "View -> Viewpoints -> Home <key>H</key>"
3. Zoom in deeply (I roll mouse wheel up to 11 clicks)
4. Choose "Tool -> Pan";
5. Try pan in main window -- NOT WORK!
6. Chose "Tool -> Rotate View" -- work well;
7. Choose "Tool -> Roll" -- work well;
8. Zoom out one step;
9. Choose "Tool -> Pan" again;
10. Try pan in main window -- work well.

**Comment by leozide** [comment]
Thanks for the steps, I see what's wrong and I'll check in a fix when I have a chance.
