### ISSUE TITLE
QT Compile error under Windows 10

### ISSUE THREAD

**Issue by frog89** [leozide/leocad#162]
Hi LeoCAD developer community,

I am using Qt Creator 4.5.0 based on Qt 5.10.0 (MSVC 2015, 32 bit). When I download leocad-master.zip, unzip it on my machine and compile leocad.pro in the QT creator tool, I get many compile errors, starting with:
C:\Qt\5.10.0\msvc2015\include\QtCore\qnamespace.h:53: Fehler: C2143: syntax error: missing '{' before '*'

I am a newbee with Qt. Do you have an idea what is set up wrong? 

When I follow your compiling guide and try to call "C:\Qt\5.10.0\winrt_x64_msvc2015\bin\qmake -tp vc" to produce project files for Visual Studio, I get following error:
Project ERROR: Cannot run target compiler 'cl'. Maybe you forgot to setup the environment?

Any ideas?

Best regards, 
Frank

**Comment by leozide** [comment]
I'm getting the same error on Qt Creator for Windows (I had never tried it before), but it works on Linux and Mac. 

Try running "qmake -spec win32-msvc -tp vc" from a Visual Studio x86 Native Command Prompt (so that it can find the required environment variables).

**Comment by leozide** [comment]
I believe the QtCreator error is a Qt bug: https://forum.qt.io/topic/86103/qt-5-10-tries-to-compile-my-precompiled-headers-as-c-instead-of-c-obviously-fails/7 - I'll file a bug report with them.

I use VS2015 Community, it has a "VS2015 x64 Native Tools Command Prompt" shortcut for me, maybe you didn't check one of the boxes in the installer. Try "qmake -spec win32-msvc -tp vc" (without 2015), this should create a VS project.

**Comment by frog89** [comment]
Hallo zusammen,

Ich habe folgende Schritte ausgeführt:
Schritt 1) leocad-master als ZIP file von Github heruntergeladen und in einem Verzeichnis entpackt, in dem ich Schreibrechte habe.
Schritt 2) Starten der VS2015 Entwickler Console:
 C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2015\Visual Studio Tools\Developer Command Prompt for VS2015
Schritt 3) Folgendes Kommando ausgeführt:
C:\Qt\5.10.0\winrt_x86_msvc2015\bin\qmake.exe -spec win32-msvc -tp vc
=> Die folgenden Datein wurden erstellt:
.qmake.stash
LeoCAD.vcxproj
LeoCAD.vcxproj.filters
Schritt 4) Anschließend die Datei LeoCAD.vcxproj in VS2015 geöffnet und kompiliert. Ich bekam 732 Fehlermeldungen. Es beginnt mit folgender Fehlermeldung:
Error	C3646	'mFileWatcher': unknown override specifier	LeoCAD	e:\frank\prj\leocad-master\common\project.h	123	

Schritt 5)
Alle Schritte wiederholt, nur dass ich im Schritt 3) folgendes Kommando ausgeführt habe:
C:\Qt\5.10.0\winrt_x86_msvc2015\bin\qmake.exe -spec win32-msvc -tp vc leocad.pro
=> Das gleiche Ergebnis.

Ich würde das Programm gern kompilieren können, um den HTML-Export anzupassen. 

Was kann ich noch tun? Ich wäre für Tipps dankbar.

**Comment by frog89** [comment]
Hello again,

Sorry, my last post was in German :-)

I have done following steps:
Step 1) I downloaded leocad-master as ZIP file from Github and extracted it in a folder where I have write rights..
Step 2) Started VS 2015 command prompt:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2015\Visual Studio Tools\Developer Command Prompt for VS2015
Step 3) Executed following command:
C:\Qt\5.10.0\winrt_x86_msvc2015\bin\qmake.exe -spec win32-msvc -tp vc
=> Following files have been created:
.qmake.stash
LeoCAD.vcxproj
LeoCAD.vcxproj.filters
Step 4) Afterwards I opened LeoCAD.vcxproj in VS2015 and started a build. I gat 732 error messages staring with following error:
Error	C3646	'mFileWatcher': unknown override specifier	LeoCAD	e:\frank\prj\leocad-master\common\project.h	123

Step 5)
I repeated all steps, bute executed in step 3) following command:
C:\Qt\5.10.0\winrt_x86_msvc2015\bin\qmake.exe -spec win32-msvc -tp vc leocad.pro
=> Same result.

I would like to be able to modify the applications HTML export.

I am thankful for further tips what I could try...

Best regards, Frank

**Comment by frog89** [comment]
Hi Leonardo,

Thanks for reporting that issue to the QtCreator team!

Meanwhile I made some code modifications (mainly renamed the *.h files to *.hpp and some header file modifications). 

I also notified that I have started the wrong qmake version. The correct command is the following:
C:\Qt\5.10.0\msvc2015\bin\qmake.exe -spec win32-msvc -tp vc

The attached files work for me in QtCreator and also in VS2015. It might be a help for people with Windows computers who are interested in LeoCAD development like posfan12.

To debug the compiled application some additional QT files are necessary:
Qt5Concurrentd.dll
Qt5Cored.dll
Qt5Guid.dll
Qt5Networkd.dll
Qt5OpenGLd.dll
Qt5PrintSupportd.dll
Qt5Widgetsd.dll
Qt5Xmld.dll

[leocad-master-win-compatible.zip](https://github.com/leozide/leocad/files/1646789/leocad-master-win-compatible.zip)

**Comment by leozide** [comment]
Someone had reported it already and looks like it's fixed: https://bugreports.qt.io/browse/QTBUG-65103

I've checked in a workaround for the pch problem. There's still a UNICODE related link error that I'll take a look when I have a chance.

**Comment by posfan12** [comment]
> I use VS2015 Community, it has a "VS2015 x64 Native Tools Command Prompt" shortcut for me, maybe you didn't check one of the boxes in the installer. Try "qmake -spec win32-msvc -tp vc" (without 2015), this should create a VS project.

It was my mistake. I overlooked some items in the Start Menu.

**Comment by leozide** [comment]
This seems to be resolved. I've checked in some more fixes and I can compile with Qt Creator for Windows now.

**Comment by frog89** [comment]
I can confirm, using the current version ant QT update the app can be build using VS2015!
