### ISSUE TITLE
Library-Linux-10289.zip include LDraw's Parts Library in raw-format, not in bin-format

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#163]
So, there no binary `library.bin` file inside, instead inside it placed `complete.zip` with LDraw's pars in raw-format.

- https://github.com/leozide/leocad/releases/download/v18.01/Library-Linux-10289.zip

**Comment by leozide** [comment]
Oops, fixed.

**Comment by leozide** [comment]
I've updated the file, there's library.bin inside now. I just downloaded
from that link and it's correct.
