### ISSUE TITLE
Show full path when hovering over part name

### ISSUE THREAD

**Issue by posfan12** [leozide/leocad#166]
Could you make it so that when hovering the mouse over a part name, the full path to the part appears? Currently, the name is truncated to fit the available space. For instance, in Windows Explorer, when editing a file name you can see the whole name. Thanks!

![leocad_screen_02](https://user-images.githubusercontent.com/13713396/35086689-82d4888a-fbfb-11e7-80c1-60d8d42e4be8.png)
![leocad_screen_03](https://user-images.githubusercontent.com/13713396/35086769-cf39d66c-fbfb-11e7-9540-4b40de4563f3.png)

**Comment by posfan12** [comment]
An alternative partial fix might be to reduce the full path to just the file name.

**Comment by posfan12** [comment]
Here's another example of Windows Explorer showing the full file name when hovering over a partial file name.

Does Qt support this?

![leocad_screen_05](https://user-images.githubusercontent.com/13713396/35308857-9ed01d58-0077-11e8-9b74-0603053b0a98.png)

**Comment by posfan12** [comment]
Here's another example where Windows Explorer will show the full file or folder name when hovering the mouse over a clipped version. Does Qt support this?

![leocad_screen_05](https://user-images.githubusercontent.com/13713396/35308958-175cec56-0078-11e8-8ff7-ba45e3664a63.png)

**Comment by tcuje** [comment]
@leozide I think this issue can be closed, since the UI currently shows just the tile description in this position and not the full filepath anymore.
