### ISSUE TITLE
Could not connect to Rebrickable

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#167]
LeoCAD version: 18.01
OS: MX Linux MX-17 (Debian 9 "Stretch"), x86_64 (64-bit)

After request search in "Sets Database" window it look like non-stop loading, but really it not loading anything.

![Rebrickable issue](http://hnng.moe/f/ZVd)

In terminal it just print this: 

```
$ ./LeoCAD-Linux-18.01-10289-x86_64.AppImage
QObject::connect: Incompatible sender/receiver arguments
        QNetworkAccessManager::finished(QNetworkReply*) --> lcSetsDatabaseDialog::DownloadFinished(lcHttpReply*)
```

**Comment by leozide** [comment]
a3995efa3661a282fed7e0324eaaf0bca9fa7d84
