### ISSUE TITLE
VS2015 build errors

### ISSUE THREAD

**Issue by posfan12** [leozide/leocad#173]
I was able to pull the latest LeoCAD revision from GitHub, and create the vcxproj file as per the instructions [here](https://github.com/leozide/leocad/issues/162).

When I try to build LeoCAD in VS2015 I get some errors, however.

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	LeoCAD	
    C:\Users\mikh2\Documents\LeoCAD_Git\leocad\common\lc_library.cpp	16	
    Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	LeoCAD	
    C:\Users\mikh2\Documents\LeoCAD_Git\leocad\common\lc_zipfile.cpp	5	

I am running Windows 10 and Microsoft Visual Studio Express 2015 for Windows Desktop Version 14.0.25431.01 Update 3.

**Comment by leozide** [comment]
Did you install the Qt sources?

**Comment by posfan12** [comment]
I'm not sure I built any sources. Here is Qt Creator's About dialog:

> Qt Creator 4.5.0
Based on Qt 5.10.0 (MSVC 2015, 32 bit)

Built on Dec 4 2017 04:12:22

From revision fcea6ceba6

Copyright 2008-2017 The Qt Company Ltd. All rights reserved.

The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

**Comment by leozide** [comment]
Not build, I think you need to install the Qt sources to get this header.

**Comment by posfan12** [comment]
Can they be downloaded somewhere? [This page](https://doc-snapshots.qt.io/qt5-5.9/build-sources.html) says they can be gotten from the [Downloads page](https://www.qt.io/download), but I don't see how.

**Comment by leozide** [comment]
The online installer has option for that.

**Comment by posfan12** [comment]
I have been using these instructions to install Qt:
https://stackoverflow.com/questions/48272668/cant-import-configure-qt-project
I just started over and added 'Sources' to the stuff I need to install.

**Comment by leozide** [comment]
With the online installer you need to install:

Qt 5.10 -> MSVC 2015 32-bit
Qt 5.10 -> Sources

Qt Creator is always installed so don't worry about that.

These are the options I have on my second Windows machine and I'm able to compile with just that.

**Comment by posfan12** [comment]
Do I need to install MinGw?

**Comment by leozide** [comment]
No

**Comment by posfan12** [comment]
Okay, it is building correctly now. Thanks.

**Comment by leozide** [comment]
So all you had to do was install those 2 options I mentioned?

**Comment by mjhorvath** [comment]
I think so, yes.
