### ISSUE TITLE
LDraw's parts with wrong bounding box & inverted faces in mesh

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#174]
Just found few issues that look like a bugs of LDraw's parts, but maybe are LeoCAD issues:

- Incorrect bounding box of part
  - Broken: [`11477.dat` Slope Brick Curved 2 x 1](http://ldraw.org/library/official/parts/11477.dat) -- too big bounding box
  - Correct: [`50950.dat` Slope Brick Curved 3 x 1](http://ldraw.org/library/official/parts/50950.dat)
- Inverted (?) faces of part's mesh
  - Broken:  [`50951.dat` Tyre 6/ 30 x 11](http://ldraw.org/library/official/parts/50951.dat) -- faces on lattice are inverted/invisible 

![LeoCAD LDraw issues](http://hnng.moe/f/ZZb)

Here is simple test case (from screenshot) -- `leocad-ldraw-isssues.ldr`

```
1 179 70 -16 0 0.866025 0.433013 -0.25 0 0.5 0.866025 0.5 -0.75 0.433013 50951.dat
1 179 10 -16 -40 -1 0 0 0 1 0 0 0 -1 50951.dat
1 179 -80 -24 -30 1 0 0 0 1 0 0 0 1 11477.dat
1 4 -80 -40 80 1 0 0 0 1 0 0 0 1 50950.dat

```

P.S.: I just discovered only this, but some other parts maybe has such issues too.

**Comment by Symbian9** [comment]
For the record, here is screenshots with same model opened in LDView

- All faces in `50951.dat` mesh look correct
![ldview mesh](http://hnng.moe/f/ZZt)

- Bouinding box of `11477.dat` look correct.
![ldview bounding box](http://hnng.moe/f/ZZu)

So, according this, its look like issue related to LeoCAD.

**Comment by nathaneltitane** [comment]
I second this bug. I had noticed it a while back although it never really bothered me to signal it. Guess it'S worth a shot @leozide

**Comment by Symbian9** [comment]
@leozide, why you already close this issue?

I still look unsolved in latest build!

- `LeoCAD-git.5c1cfa4.qt57-x86_64.AppImage`
  - https://github.com/leozide/leocad/commit/5c1cfa4bc9a74799dad3730df43164fe63882033

**Comment by leozide** [comment]
This was closed because it's fixed. You may need to clear your cache.

**Comment by Symbian9** [comment]
> You may need to clear your cache.

Oh, now I clear cache - and its fixed ! ;-)

P.S.: It would be cool add "Clear cache" button in "View -> Preferences -> General"
