### ISSUE TITLE
Qt5 builds

### ISSUE THREAD

**Issue by Lewiscowles1986** [leozide/leocad#182]
I've looked at the Travis file, and I'm unsure how you're building for qt5. Travis reports you are, but simply copy-pasting commands from travis.yml into a `Vagrantfile` the build fails. I've managed to get it built using the following (borrows heavily from Travis). Mostly using vagrant because I'm lazy and didn't want to alter my machine or wait for Travis.

```shell
    apt-get update
    apt-get install -y git build-essential zlib1g-dev

    add-apt-repository -y ppa:beineri/opt-qt59-xenial
    apt-get update -yqq

    apt-get install -yqq qt59base qt59tools qt59gamepad libqt5opengl5-dev
    export QT_BASE=59
    source /opt/qt59/bin/qt59-env.sh

    mkdir /tmp/build
    cp -ar /vagrant/* /tmp/build/
    cd /tmp/build
    sed -i '10 s/^/#/' PKGBUILD
    sed -i '12 s/#//' PKGBUILD

    qmake PREFIX=/usr -v
    qmake PREFIX=/usr -r
    make -j4
```

At first, I thought exporting `QT_BASE` would help, but it didn't seem to. Then I looked into the `PKGBUILD` and noticed there was a commented out QT5 on line 12, QT4 version of that line was showing on line 10. How are you currently managing that in Travis? I can't find it anywhere and it's driving me mildly up the wall.

relates to #159 (I'll need to be able to automate build in order to work sanely).

**Comment by leozide** [comment]
Travis doesn't use PKGBUILD, only the yml file. It calls (for the QT5 build):

sudo apt-get install -qq qt57base libqt5opengl5-dev; source /opt/qt57/bin/qt57-env.sh; 
qmake 
make
