### ISSUE TITLE
Enable parallel rotate of parts with same transformation matrix

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#183]
I often come across cases of duplicated parts that wind up having the same transformation matrix and that need, for instance, to be rotated independently to achieve the same positioning on a model.

would it be possible to enable a 'parallel' transformation feature + keyboard shortcut scheme to have the selected parts rotate in place but at the same time with a combination?

How to reproduce:
Select parts to be rotated (multiple selection)
***Independantly rotate selected parts (2 + step process)***
Set parts in place

Solution:

Select parts to be rotated (multiple selection)
Rotate parts using a keyboard combination (each individual part rotates on its own at it's specified relative location)
Set parts in place

Thanks

**Comment by leozide** [comment]
I believe this is working now
