### ISSUE TITLE
Compiling on Linux also requires libqt4-opengl-dev

### ISSUE THREAD

**Issue by doyousketch2** [leozide/leocad#19]
On your compiling guide   leocad.org/docs/compiling.html

you have these listed
`$ sudo apt-get install libqt4-dev zlib1g-dev`

But I ran into this error:
```
common/lc_global.h:6:20: fatal error: QtOpenGL: No such file or directory
 #include <QtOpenGL>
                    ^
compilation terminated.
Makefile:336: recipe for target 'build/release/.obj/leocad.gch/c++' failed
make: *** [build/release/.obj/leocad.gch/c++] Error 1
```
So I had to install the QT-OpenGL headers as well.
libqt4-opengl-dev

Not a biggie, just letting you know.

**Comment by leozide** [comment]
I've updated the page, thanks.
