### ISSUE TITLE
Part positions not saved correctly

### ISSUE THREAD

**Issue by andmanno** [leozide/leocad#191]
Hi,
i have a project with svereal sub models. When i save the project and reopen it again, the position of some parts is not saved correctly.  Can i somehow submit this file privately (i don't want to make it public yet) so you can test what`s wrong?

I'm using v18.02

Thanks for all your work and effort!

BR

**Comment by leozide** [comment]
You can send it to me and I'll take a look

**Comment by andmanno** [comment]
How? I didn't find any contact details.

**Comment by leozide** [comment]
The notification email you receive when I post a reply here has my email address.

**Comment by andmanno** [comment]
I send the files.

**Comment by leozide** [comment]
Hmm, actually it doesn't send my real email. You can email leozide@gmail.com
