### ISSUE TITLE
Part images don't show up at v18

### ISSUE THREAD

**Issue by j3j3ling** [leozide/leocad#194]
It doesn't shows up at 18.01 nor 18.02
But part images still show up when i use leocad under v18. ex: v17
What could be the problem?

leocad v18
![1](https://user-images.githubusercontent.com/36720988/36519638-421bb298-17bf-11e8-8802-1a570538870a.PNG)

leocad v17
![2](https://user-images.githubusercontent.com/36720988/36519642-47b5a6a0-17bf-11e8-8f74-7357e2194275.PNG)

**Comment by leozide** [comment]
Have you tried updating your video card drivers? 

https://support.amd.com/en-us/download
