### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by mardy** [leozide/leocad#195]
Hi! It seems that LeoCAD does not support stickers -- or at least, I haven't found a way to load them properly.
For instance, if I load these stickers in LeoCAD I only get some weird yellow pieces: http://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/194325a.dat

**Comment by leozide** [comment]
That part loads correctly for me:

![image](https://user-images.githubusercontent.com/9685066/36633656-432bc872-194e-11e8-85ee-2a4dfe7a1b1c.png)

Can you post a screenshot of what you're seeing and how you have your library organized?

**Comment by mardy** [comment]
Here's the screenshot of how part `194325a2.dat` is rendered:
![screenshot from 2018-02-24 23-24-13](https://user-images.githubusercontent.com/59287/36634725-ea1d1eb8-19b9-11e8-8b68-9fa597e52461.png)
my ldraw parts are in `~/ldraw/`. Indeed, it might be that I haven't installed the parts properly: I just copied the files into `~/ldraw/parts/`; is there more to be done?

**Comment by leozide** [comment]
Did you copy the subparts?

**Comment by mardy** [comment]
Yes, I've put them in `~/ldraw/parts/` as well. But I didn't run the mkparts application, as it appears that it's a Windows-only program.

**Comment by leozide** [comment]
Subparts go in parts/s/

**Comment by mardy** [comment]
OK, I've put the `194325a1.dat` and `194325a2.dat` in `parts/s/`, while the main one is in `parts/`, and that indeed helped.
Thanks, and sorry for the noise! :-)
