### ISSUE TITLE
Release AppImage has ugly font (nightly AppImage font look better)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#198]
Nightly AppImage's (Travis builds) look left; Release AppImage's (stable builds) look right
![LeoCAD fonts in AppImage](http://pasteall.org/pic/show.php?id=129556)

**Comment by Symbian9** [comment]
@leozide, it's look like latest nightly AppImage build now got ugly font too...

- LeoCAD-git.2575188.qt57-x86_64.AppImage
  - https://travis-ci.org/leozide/leocad/builds/368285361

![LeoCAD-git.2575188.qt57-x86_64](http://i.imgur.com/NGsT2vD.png)

Previous nightly builds has NO such ugly font!

@probonopd, could you look what happen and tell how set LeoCAD use system font?

### REFERENCE

- http://github.com/appimage/appimagekit/issues/125

**Comment by probonopd** [comment]
I would be surprised if this had anything to do with AppImage. To check, run ./LetoCAD*.AppImage `--appimage-extract` and then run `./squashfs-root/AppRun`.

**Comment by Symbian9** [comment]
> To check, run ./LeoCAD*.AppImage `--appimage-extract` and then run `./squashfs-root/AppRun`.

Just tried - NO changes. Font still look ugly.

**Comment by probonopd** [comment]
> I just try it - NO changes. Font still look ugly.

Then it's not caused by AppImage at least. :-)

**Comment by Symbian9** [comment]
> Then it's not caused by AppImage

@probonopd, So, what then? Qt?

**Comment by probonopd** [comment]
I don't know. sorry. Possibly Qt, possibly the Qt configuration, possibly some font rendering library, possibly linuxdeployqt.

**Comment by Symbian9** [comment]
> possibly linuxdeployqt

Is possible that some changes in `linuxdeployqt` could cause fonts in Qt apps?

> possibly some font rendering library

Interesting. I got few updated libs few days ago on my PC with installed MX Linux MX-17:

- libfontconfig1-dev (2.11.0-6.7+b1) to 2.13.0-4~mx17+1
- libfreetype6-dev (2.6.3-3.2) to 2.8.1-2~mx17+1
- xfce4-settings (4.12.1-1) to 4.12.3-1~mx17+1

Maybe, this also related? Will check...

@probonopd, but this not give an answer to question why on same system in same time *nightly* and *release* versions of LeoCAD built as AppImage was different look of fonts? (as shown on first comment in this issue discussion)

**Comment by Symbian9** [comment]
It's look like "font hinting" broken in latest `freetype` versions...

- https://bugs.launchpad.net/ubuntu/+source/freetype/+bug/1722508

**Comment by probonopd** [comment]
> Why on same system in same time nightly and release AppImage builds of LeoCAD got different look of fonts

Again, can be the same reasons: Different libraries bundled, different versions of linxudeployqt used, different Qt versions used, different bugs... I don't know. Best unpack both AppImages and compare the contained libraries.

**Comment by leozide** [comment]
Release builds are now built the same way as continuous
