### ISSUE TITLE
translation missing

### ISSUE THREAD

**Issue by jschwender** [leozide/leocad#201]
it seems leocad is exclusively english. is there a way to get it translated to other languages?

**Comment by Symbian9** [comment]
> it seems leocad is exclusively english.

Not only English, it has partially translation to other languages too

- French -- https://github.com/leozide/leocad/blob/master/resources/leocad_fr.ts
- Portuges -- https://github.com/leozide/leocad/blob/master/resources/leocad_pt.ts

@leozide, add `../resources/leocad_template.ts` for translators

**Comment by leozide** [comment]
If you want to translate to another language, let me know which and I'll set it up.
