### ISSUE TITLE
LeoCAD problems with patterned parts

### ISSUE THREAD

**Issue by mjhorvath** [leozide/leocad#215]
I am trying to edit this model:
http://www.mediafire.com/file/ne7omh9uetxmifl/datsville_te_rev013_inlined_y_boxed_n.zip
Here's a screenshot:
https://i.imgur.com/snxxy1U.png

Notice the tall white and yellow columns? They should be much smaller parts. Not sure what is happening. I think it is sometimes because the parts are patterned. Could you fix it please?

**Comment by leozide** [comment]
There's something wrong with loading the primitives after they were inlined so the app is replacing them with boxes. I'll fix when I have a chance.
