### ISSUE TITLE
Rendering modes

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#219]
Hey Leo,

Is there a possibility of you dissociating the parts preview panel rendering mode from the model viewport rendering mode? Meaning, if i toggle the wireframe/flat/lighting modes, it would make sense to apply it only to the model and not the parts preview unless specified otherwise.

Thank you

**Comment by leozide** [comment]
Is this just a wireframe problem? I'm against having different toggles for the model and preview, but I can change it so the preview never goes into wireframe.

**Comment by nathaneltitane** [comment]
Sounds alright to me

**Comment by Symbian9** [comment]
> I'm against having different toggles for the model and preview, but I can change it so the preview never goes into wireframe.

What about add to parts widget sub-menu option ***"Lock Preview Shading"*** (similar to *"Lock Preview Color"*)? Think this is best way for solve this task
