### ISSUE TITLE
Part color modification within group

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#220]
When a part within a group is selected, its properties modification affect the whole group.

Example, selecting a 1x1 brick withing a group of varied parts and changing it's color from red to blue will change the whole group to blue.

Solutions?

1 - either make editing unavailable when in group
2 - apply new properties to selected part only

Thank you

**Comment by leozide** [comment]
If you have a group selected then all parts in that group are selected and changing the color will affect all parts. I'm changing how submodels work and groups will probably be removed if it all works out.

**Comment by nathaneltitane** [comment]
Explanation? 
The way I see it, groups are still a valid part of the editing process and are still a valuable feature to have, at least in managing how the build process goes...

**Comment by leozide** [comment]
What do you get from groups that you don't get from submodels? They overlap too much in my opinion so I plan to merge their functionality.

**Comment by leozide** [comment]
Isn't creating a nested submodel equivalent to creating a nested group? And isn't inlining a submodel the same as ungrouping?

There are no groups in the ldraw spec.

**Comment by nathaneltitane** [comment]
IMHO I see them as two completely different elements and use them both entirely differently:

I see grouping as a tool for facilitating arrangement within a model, which is then nested within a greater arrangement of other models. I can ungroup a set of parts but not 'unnest' and LDR from an MPD unless I merge LDR 1's parts to LDR 2's content.
