### ISSUE TITLE
Duplicate does nothing

### ISSUE THREAD

**Issue by 1manfactory** [leozide/leocad#225]
Windows
LeoCAD 18.02

I created/inserted a figure with the Minifig Wizard (really a nice tool, great job you guys)

When selecting the figure and choosing Duplicate (CTRL-D) nothing happens. I would expect to create a copy of the same figure and had it inserted at the same place (or close to it)

Copy and Paste of figure runs ok as expected.

**Comment by leozide** [comment]
This sounds like a duplicate of #158
