### ISSUE TITLE
Buggy Model Import

### ISSUE THREAD

**Issue by 1manfactory** [leozide/leocad#226]
Windows
LeoCAD 18.02

I tried to import a model generated with LDRAW http://omr.ldraw.org/file/603

The result was not so nice. (See picture)

![unbenannt](https://user-images.githubusercontent.com/232674/38670456-1aa22bce-3e49-11e8-80ab-0f66ec50665b.JPG)

**Comment by leozide** [comment]
I think this is a duplicate of #215, the model loads correctly for me.
