### ISSUE TITLE
Memory corruption in the part library on one image after loading a big file

### ISSUE THREAD

**Issue by Lswbanban** [leozide/leocad#230]
After I opened a large mpd file (385 kb, around 8 000 parts), I noticed that the first image of the part library was corrupted (please see the image attached).

![corruptedmemory](https://user-images.githubusercontent.com/14555331/39110001-f2e97d1e-4701-11e8-949c-2c5ae168ba35.JPG)

**Comment by leozide** [comment]
I changed how those are drawn, may be fixed now.
