### ISSUE TITLE
Import set inventory - Error connecting to server

### ISSUE THREAD

**Issue by BartAdv** [leozide/leocad#236]
When I attempt to import a set inventory, I only get this error, nothing else:

```
Error connecting to server
```

Not sure from where I could fetch additional logs, or maybe it's a known issue (perhaps, something changed in rebrickable API) ? Or maybe I need to configure something.

I'm on Arch-linux, build from AUR repository: https://aur.archlinux.org/packages/leocad/

**Comment by BartAdv** [comment]
Oh, I've totally forgot I can just check the network packets. It seems the problem is that the HTTP client used does not honor 301 response:

```
GET /rebrickable.json HTTP/1.1
Host: www.leocad.org
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
User-Agent: Mozilla/5.0

HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: https://www.leocad.org/rebrickable.json
X-GitHub-Request-Id: D02C:77F1:5056A4D:6FA0393:5AE5DA5B
Content-Length: 178
Accept-Ranges: bytes
Date: Sun, 29 Apr 2018 14:44:46 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-hhn1534-HHN
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1525013086.334721,VS0,VE97
Vary: Accept-Encoding
X-Fastly-Request-ID: 2c3ee16fd9ef3ef3589fe5aa8d759372bc0efd1e

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by leozide** [comment]
About a month or so ago I changed the server to only support https, the code has been updated but I haven't released a new version since that change.

**Comment by BartAdv** [comment]
OK, so I've tried with `leocad-git 18.02.r41.25751889-1` version, but that one is lacking the "Import Set Inventory"...

**Comment by BartAdv** [comment]
Well, I'm not building it on my own, just using the AUR leocad-git package.

**Comment by Symbian9** [comment]
@leozide, it seems like *"Error connecting to server is back"* with latest `LeoCAD-Linux-c10804d-x86_64.AppImage`:

![Screenshot_2021-12-21_23-43-32](https://user-images.githubusercontent.com/13188580/147072266-b2b87a8e-1a88-4995-bf74-e5485b154644.png)
