### ISSUE TITLE
Problem pointing leoCAD to parts library from GitHub releases page.

### ISSUE THREAD

**Issue by BillGHero** [leozide/leocad#239]
Using:
 Ubuntu 18.04
leoCAD 18.01 (from the Ubuntu 18.04 repo), Library-Linux-10289.zip

A small problem that required some time to nail down here:
When using the library file from gitHub (in this case Library-Linux-10289.zip), I could not get leoCAD to use them in the expected way. i.e. in hte way that a typical application would work.

When pointing leoCAD to the parts library using the preferences dialogue; I clicked on the elipses (...) and pointed it to the folder that the library was in. The file picker dialogue does not allow you to select the library file itself, this was true whether I used the zip file or the bin file it contained.

However, you must have the library filename in the path for this method to work, in spite of the fact that the file picker does not allow you to select it. So, to make leoCAD use that library file I added that file name to the end of the path in the preferences dialogue via keyboard.

This is not a huge problem, but it is an issue. A file picker for a path should allow the user to select the entire path necessary in one go, particularly if the file being selected is from the developer of the application (which is the case here, correct?) This issue is further compounded by the existence of several, I believe unofficial, instructions for setting up leoCAD with a parts library - the two set of instructions I found both assume that leoCAD will be able to find any compatible parts library as long as the path is set to the library's root folder (which is not the case in my experience with leoCAD.)

**Comment by leozide** [comment]
The path can either be the bin file, or the directory containing an unzipped LDraw library but the picker dialog can only select a file or a path, it can't select both (Qt limitation). Since most people that have a custom library will have loose files with their own changes, I chose to have the dialog select a directory.

The instructions from https://www.leocad.org/docs/library.html tell you to unzip Library.zip to /usr/share/leocad, at which point the app should find it automatically. Is it not finding it there? Where did you see conflicting instructions?

**Comment by BillGHero** [comment]
Sorry to hear about the QT limitation. I definitely see why you decided to go with the option you chose.

I installed the 18.01 version of leoCAD from the repository for Ubuntu 18.04. The install didn't create a folder in /usr/share/ for leocad. :( If that's wrong, I imagine it is probably due to an error by the package maintainer?)


By the way, my kid says your application is awesome. :) Thanks for the hard work!

**Comment by BillGHero** [comment]
p.s. I can see about entering it into launchpad, unless you would prefer I not do so?

**Comment by Symbian9** [comment]
> I installed the 18.01 version of leoCAD from the repository for Ubuntu 18.04. The install didn't create a folder in /usr/share/ for leocad. :( If that's wrong, I imagine it is probably due to an error by the package maintainer?)

@BillGHero, You install it with or without 'root' permissions?

**Comment by luisriera** [comment]
@BillGHero , here is a way around your problem.

1. Download the as instructed in [https://www.leocad.org/docs/library.html]
2. Create the hosting folder using `sudo mkdir /usr/share/leocad/library.bin`
3. Unzip the `ldrawunf.zip` into a temp folder using `unzip ldrawunf.zip`
4. Move the two unzip folders to the folder you created in point 2 using 'sudo mv p*  /usr/share/leocad/library.bin'

That should get you going.

@[Symbian9](/Symbian9), Ubuntu require root privileges to install most apps by the using "sudo", "leocad' is not an exemption.

**Comment by tcuje** [comment]
![image](https://user-images.githubusercontent.com/4201214/53911496-dd8ed000-4056-11e9-8b66-bf9c64fcce66.png)

I patched the two buttons on the right

**Comment by Symbian9** [comment]
> I patched the two buttons on the right

Could you also patch for multiply ZIP selection?

For example, for select not only `complete.zip` and `ldrawunf.zip`, but also other unoficial parts libraries:

- Parts Libraries: `<path-to>/complete.zip;<path-to>/ldrawunf.zip;<path-to>/my-parts.zip`

REFERENCE:

- https://github.com/Symbian9/AWESOME-LDraw

**Comment by tcuje** [comment]
If LeoCAD supports to load multiple libraries at the same time, it should be trivial to do so. From the code it looks like it does and does not, I'm confused...

Last but not least on some operating systems, files can contain `;` in their filename. But this issue could be acceptable...

**Comment by Symbian9** [comment]
I really dislike "space" usage in file/folder naming. So, as for me, LeoCAD should not support file/folder names with ` ` symbols.

**Comment by leozide** [comment]
The right thing to do here would be to display a list of folders and files and let the user add/remove as needed.

We currently support 2 libraries but the second one is always hard coded to be the unofficial folder or zip file of the first one.
