### ISSUE TITLE
Hidden parts in submodels are visible in their parent model

### ISSUE THREAD

**Issue by Lswbanban** [leozide/leocad#240]
If you hide some parts in a submodel, then if you add that submodel in a bigger model, then those hidden parts are visible in the top model.

IMHO, when displaying a model, you should keep the visibility recursively, in all subsequent submodels of the hierarchy.

**Comment by nathaneltitane** [comment]
I second this! I find it quite difficult to leverage hiding components on complex assemblies du to this behavior!

**Comment by tcuje** [comment]
Almost fixed with b18645b8803452c557231285fcdbabb5045a0962, but hidden parts are now hidden in the preview of parts selection too. For testing I hid the rim in the submodel:
![image](https://user-images.githubusercontent.com/4201214/54525442-88b35980-4974-11e9-96db-8057f855cd81.png)

**Comment by leozide** [comment]
I think they should be hidden in the preview as well. The preview should match what the model will look like after it has been added to another model.

**Comment by Lswbanban** [comment]
I agree, I think the hidden parts should also be hidden in the preview of the submodel.
