### ISSUE TITLE
Transparent color picture alpha not rendered correctly

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#241]
The output of a cli command from mpd model to pic, containing tranparent color parts (trans green specifically - very obvious) does not layer correcty and rasterizes fully translucent/transparent directly over the png background. See attachement.

![model](https://user-images.githubusercontent.com/5674757/42192664-3a8b83f2-7e38-11e8-9313-0da30d4b8a34.png)

**Comment by Symbian9** [comment]
Yeah, it's look like LeoCAD during rendering cutout parts of bricks behind transparent bricks

![LeoCAD transparent cutout](http://i.imgur.com/GzUFnlf.png)

**Comment by nathaneltitane** [comment]
@Symbian9 I was merely stating that the output was generated through CLI for reference purpose, I'm aware that it stems from LeoCAD.

If we are to focus on the first zoomed image of your comment, i can assert that the parts are not stacked to one another, they are clearly separate and defined, meaning it should normally render a white bg behind the trans green dish.

**Comment by leozide** [comment]
Those are different issues.
