### ISSUE TITLE
cli issue in bash, parsing camera angle coordinates as array pairs

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#245]
I've run into an issue where setting camera angle coordinates as lat long values fails to be understood as a parameter by leocad because of the built in array/variable expansion in bash withing single quotes.

		run_leocad () {

			height="4096"
			width="4096"
			snapshotsuffix=".png"
			latlong=${coordinates[position]//\'/}

			leocad \
				-h "$height" \
				-w "$width" \
				-i "${option_prefix}${model_render_name}${view[position]}${snapshotsuffix}" \
				--camera-angles "$latlong" "$1"
		}

			coordinates=(
				"30 225"
				"30 45"
				"30 180"
				"30 0"
			)

--

+ leocad -h 4096 -w 4096 -i gn-001-exia-quarter-front.png --camera-angles '30 45' /media/MEGA/Lego/models/mobile-suits/gn-001-exia/00-gn-001-exia.mpd

(leocad:15889): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
Invalid value specified for the '--camera-angles' argument.

--

**Comment by leozide** [comment]
I think you're adding the quotes yourself with the //\'/ part.

**Comment by nathaneltitane** [comment]
My bad, that was a very quickly typed attempt at showing the issue, should've been /'//.

Still persists btw

**Comment by leozide** [comment]
I don't get quotes when I try that script
