### ISSUE TITLE
Segmentation fault when starting on Fedora 28

### ISSUE THREAD

**Issue by HaasJona** [leozide/leocad#246]
```
$ ./LeoCAD-Linux-18.02-x86_64.AppImage 
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve ERR_free_strings
QSslSocket: cannot resolve sk_new_null
QSslSocket: cannot resolve sk_push
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot resolve SSLeay_version
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
Segmentation fault
```

Any ideas what to do to debug thus issue?

**Comment by leozide** [comment]
I think you just need to install libopenssl, weird that it crashes when it's missing.

**Comment by dylanswift** [comment]
I see the exact same errors on Fedora 27 - I have openssl & openssl-devel packages installed.

Any thoughts?

**Comment by HaasJona** [comment]
I also have openssl-libs-1:1.1.0h-3.fc28 installed.

**Comment by HaasJona** [comment]
running it in gdb shows:

```
Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x00007ffff678a27b in ?? ()
   from /tmp/.mount_LeoCADmvrahZ/usr/bin/../lib/libQt5Network.so.5

```

**Comment by leozide** [comment]
I just installed Fedora 28 on a VM and it works fine, I don't get this crash.

**Comment by divinity76** [comment]
to those of you who can reproduce the crash, can you run it through ldd?
`ldd ./LeoCAD-Linux-18.02-x86_64.AppImage`

**Comment by dylanswift** [comment]
ldd command returns:

`        not a dynamic executable`

**Comment by leozide** [comment]
@probonopd have you see any issues with Qt appimages on Fedora like this?

**Comment by probonopd** [comment]
Don't remember it, but I don't know so many Fedora users either...

**Comment by sbuller** [comment]
This looks similar: https://github.com/aferrero2707/gimp-appimage/issues/7, which links to https://stackoverflow.com/questions/42094214/why-is-qsslsocket-working-with-qt-5-3-but-not-qt-5-7-on-debian-stretch

The prognosis there seems to be that Qt requires libssl 1.0 while Fedora provides 1.1. If I'm reading all that correctly.

**Comment by sbuller** [comment]
I found another here https://bugs.kde.org/show_bug.cgi?id=395201.
Cura also seems to have been hit by this. It looks like Qt dlopen()s libssl.

**Comment by sbuller** [comment]
Fedora has a compat-openssl10 package which provides /usr/lib64/libssl.so.10.

strace of LeoCAD shows:
```
$ strace ./LeoCAD-Linux-18.02-x86_64.AppImage 2>&1  |grep ssl                                                                                              
openat(AT_FDCWD, "/tmp/.mount_LeoCADps6iHZ/usr/bin/../lib/libssl.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64/libssl.so", O_RDONLY|O_CLOEXEC) = 39
…
```

/lib64/libssl.so links to libssl.so.1.1.0h in Fedora 28. If the theory that Qt relies on ssl 1.0 is correct, then the solution would be to either fix up the path so it opens /lib64/libssl.so.10 or add libssl.so to the AppImage.

**Comment by probonopd** [comment]
May be related to https://github.com/probonopd/linuxdeployqt/issues/209
