### ISSUE TITLE
View cube text labels look ugly

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#249]
### Current behaviors

1. Text labels font is ugly.
2. Text label "Bottom" has NO space / offset on the right side.

![pic1](https://i.imgur.com/R0XEG2z.png)

![pic2](https://i.imgur.com/359H64v.png)

![pic3](https://i.imgur.com/MxGMLS5.png)

### Expected behaviors

1. Text labels font should be readable on monitor with 96..98 DPI.
1.1. Draw text by line segments, instead of use font file (how it drawn now?).
2. Add space symbol / offset on the right side of text label "Bottom"

### Details

Version: `LeoCAD-git.5e31d69.qt57-x86_64.AppImage`

**Comment by nathaneltitane** [comment]
antialiasing does not seem to apply to the view cube widget nor its labels - fix? @leozide

**Comment by Symbian9** [comment]
> antialiasing does not seem to apply to the view cube widget nor its labels

To be clear, antialiasing applied to cube edges.

But text labels rendered without antialiasing. This also same for axis labels (`X`, `Y`, `Z`).

As proposed above, think, it would be better draw text for axis & cube labels by line segments, instead of use font file.

**Comment by Symbian9** [comment]
> antialiasing does not seem to apply to the view cube widget nor its labels - fix?

Latest build got fixed labels! Now text labels on viewcube looks much better ;-)

- `LeoCAD-git.61ce943.qt57-x86_64.AppImage`
![viewcube fixed labels](http://i.imgur.com/XxiOJq2.png)

P.S.: @leozide, maybe, need apply same fix for axis labels & camera label too, what you think?

**Comment by Symbian9** [comment]
@leozide, I just tested latest changes: "view cube" -> "view sphere"

- `LeoCAD-git.b77b9aa.qt57-x86_64.AppImage`

![pic.1](http://i.imgur.com/YRh2Ugo.png)

![pic.2](http://i.imgur.com/oDAn500.png)

As for me, "view cube" was much better and current "view sphere" lost few viewpoints (that was on "view cube", e.g. align to corner & align to edge)

- `LeoCAD-git.58c6398.qt57-x86_64.AppImage`

![pic.3](http://i.imgur.com/xfFzqHC.png)

@nathaneltitane, what you think?

**Comment by nathaneltitane** [comment]
@leozide 

Another good idea would be to shade or enable a color option to the view sphere (with alpha?) to know it's boundaries and area?

An svg overlay scaled to the size option could do the trick :)

Also, have you ever looked at Autodessk's viewcube widget? I use Autodesk products on the daily and it works like a charm :)

https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/AutoCAD-Core/files/GUID-E6D3896C-AF39-4F5C-A57C-CACE2A1117F9-htm.html

**Comment by leozide** [comment]
> when clicking a label to enable a view, all other view labels are inaccessible from the sphere, thus making the widget useless.

I don't understand this part, you can still select between side views to rotate. 

> there also seems to be an issue with the sphere's outer perimeter: it looks grainy and that's due to how the edge of the text in the labels are being rendered.

I'm still working on the edges, I need to make it look better overall.

> Another good idea would be to shade or enable a color option to the view sphere (with alpha?) to know it's boundaries and area?

Not sure what you mean by this.

I know about the view cube, I've seen it in Maya.

**Comment by nathaneltitane** [comment]
@leozide 

the area to click is undefined and depends on the label itself as to what i can see on my current running build? there is no highlight aside from the label becoming red, and it's not always triggered accuratly *every time* i click on a label to toggle a view.

the shading/color part was to make the sphere more visible when on a neutral or white bg. I haven't tested any other kind of bg to see how the sphere is affected.

The part about the svg was to have it be an overlay to the sphere, unless you prefer applying color changes to the sphere object itself? - it would behave the same as the autodesk viewcube as to how the hover/selection changes the shade or color of the specified face and make the view secletion clearer.

**Comment by leozide** [comment]
I couldn't get this to work a way I liked, best I could do was the current
system where it highlights the 2 or 3 side views related to the zone you're
clicking

**Comment by leozide** [comment]
I believe I've addressed all issues pointed here, if you feel like something is missing from the sphere please open a new ticket.
