### ISSUE TITLE
View cube: after click on "Bottom" text label all disappear

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#250]
### Current behaviors

If click on "Bottom" text label on view cube all objects (axis icon, view cube and model's parts) disappear.

![pic1](https://i.imgur.com/3zKzeZW.png)

![pic2](https://i.imgur.com/OkDdgp7.png)

### Expected behaviors

Click on "Bottom" text label on view cube should work correctly.

### Details

Version: `LeoCAD-git.5e31d69.qt57-x86_64.AppImage`

**Comment by nathaneltitane** [comment]
Still happens with latest commit @leozide

**Comment by Symbian9** [comment]
Yeah, latest `LeoCAD-git.7ba01db.qt57-x86_64.AppImage` still has such issue
