### ISSUE TITLE
error creating image under linux and windows

### ISSUE THREAD

**Issue by bonkersdeluxe** [leozide/leocad#256]
Hi i would use leocad to export ldraw parts to png.
But when i save, an dialogbox apperas with an error create images.
I try it out with 100x 100 pixels without an positive result

my version is 18.02 for linux and windows.
Thank you!
Sincerely Bonkersdeluxe

**Comment by Symbian9** [comment]
Check, is it same issue as previous?

- https://github.com/leozide/leocad/issues/255

If so, close this issue report as duplicate and discuss it in https://github.com/leozide/leocad/issues/255 thread

**Comment by bonkersdeluxe** [comment]
I think its the same.
https://github.com/leozide/leocad/issues/255
Please can you fix this. Thank you!
