### ISSUE TITLE
Not building on MacOs

### ISSUE THREAD

**Issue by d029940** [leozide/leocad#267]
In the "leocad.pro" file

at line 118/119
        library.files += $$_PRO_FILE_PWD_/library.bin
        library.path = Contents/Resources

stops the building process with error message:
:-1: error: No rule to make target `../leocad/library.bin', needed by `build/debug/LeoCAD.app/Contents/Resources/library.bin'.  Stop.

If I change this section to ... (i.e. commenting these 2 lines out), it will build.

macx {
	ICON = resources/leocad.icns
	QMAKE_INFO_PLIST = qt/Info.plist

	document_icon.files += $$_PRO_FILE_PWD_/resources/leocad_document.icns
	document_icon.path = Contents/Resources
        #library.files += $$_PRO_FILE_PWD_/library.bin
        #library.path = Contents/Resources
    povray.files += $$_PRO_FILE_PWD_/tools/povray/povray
    povray.path = Contents/MacOS

    QMAKE_BUNDLE_DATA += document_icon library povray
    DEFINES += LC_DISABLE_UPDATE_CHECK=1
}

I suppose, this is not the way to do (there had ben some thoughts). Probably the file "library.bin" is missing.

**Comment by leozide** [comment]
That file is not checked in because it’s too big, you can download it or just comment out those lines.

There’s a note in the documentation about it: 
https://www.leocad.org/docs/compiling.html
