### ISSUE TITLE
Segmentation fault: 11 on MacOS 10.13.6 (High Sierra)

### ISSUE THREAD

**Issue by d029940** [leozide/leocad#268]
Launching leocad gives a Segmentation fault: 11 on MacOS 10.13.6 (High Sierra).
Qt-Version: 5.11.1

It seems to be associated to QGamepad.

If I define "LC_ENABLE_GAMEPAD 0" in "lc_mainwindow.cpp", there will be no segmentation fault

If it is defined as "LC_ENABLE_GAMEPAD (QT_VERSION >= QT_VERSION_CHECK(5, 10, 0))", the variable "mModelTabWidget" is not initialized in method "lcMainWindow::GetActiveView()" in file "lc_mainwindow.h"

On Windows 10, same Qt version, there is no problem.

**Comment by leozide** [comment]
Probably needs the next change as well, I can't test it.

**Comment by leozide** [comment]
That sounds like what I did on the last 2 changes, did that not work?

**Comment by d029940** [comment]
Sorry, I did not update my local repository. So, I did it now. And, yes indeed, it works. Sorry & Thank you.
