### ISSUE TITLE
LeoCad 

### ISSUE THREAD

**Issue by AWCris** [leozide/leocad#269]
Is there a way to print a jpeg of your design within the program? 
If so is there an email or number to call to discuss program confliction details of my project.
Thank you.

**Comment by leozide** [comment]
You can save a jpeg file using File->Save Image from the main menu.

**Comment by AWCris** [comment]
Hello Leonardo,

I am running a learning lab where kids of all ages can come and learn and be creative. However so that the kids don’t try to leave the site, we have a block software that does not allow them to do anything other than use the creative software provided.
so is there a way to print without leaving the program or downloading anything?

Thank you,
Crystal

**Comment by leozide** [comment]
I wasn't sure if you wanted to save a jpeg or print. 

There's a Print (and Print Preview) option on the File menu.
