### ISSUE TITLE
Embedded parts in ldr are not displayed

### ISSUE THREAD

**Issue by ali1234** [leozide/leocad#274]
I have a model using some custom parts. They are embedded in the LDraw file as in-line DAT sections. When I open my file in recent leocad these parts are not shown. This seems to be a regression as I originally created this file in leocad.

I suspect this may be related to https://github.com/leozide/leocad/issues/64 as in some places the file names are capitalized and in others they are not.

**Comment by ali1234** [comment]
Forgot to mention I'm using 18.01 and my model is here: https://github.com/ali1234/pirover/blob/master/bricks/pirover.ldr

It imports correctly in Blender with https://github.com/TobyLobster/ImportLDraw and should look like this:

![screenshot_2018-10-28_00-38-12](https://user-images.githubusercontent.com/651970/47610303-c822ed00-da49-11e8-9dfa-e3464a329c5c.png)

The wheels and some other bits are custom parts.

**Comment by leozide** [comment]
I think the model looks correct when I import:

![image](https://user-images.githubusercontent.com/9685066/47624852-e1757900-dadd-11e8-9935-6e9840042cf3.png)

And the wheel looks like this:

![image](https://user-images.githubusercontent.com/9685066/47624869-04079200-dade-11e8-9929-7f313ec6fc4c.png)

**Comment by leozide** [comment]
That was from 18.02, why are you still using 18.01?

**Comment by ali1234** [comment]
This is fixed by https://github.com/leozide/leocad/commit/5ac11506b0d876d291b28dd2ad2dc046341a62a3
