### ISSUE TITLE
Blurry app icon when installing from Debian/Ubuntu package

### ISSUE THREAD

**Issue by patrickrst** [leozide/leocad#278]
As @nathaneltitane recently pointed out in #2, installing LeoCAD from Debian/Ubuntu package manager results in a blurry icon in the app menu.

The package contains a 32x32 .png and a .svg (which is a 256x256 .png), but by default the 32x32 image seems to preferred over the SVG.

Should this be reported to the Debian/Ubuntu packaging team?

**Comment by leozide** [comment]
I think the menu icon is selected by the Debian package scripts, I don't control that.

**Comment by nathaneltitane** [comment]
@leozide we could make the svg override the 32x32 png by symlink, no?

**Comment by patrickrst** [comment]
I have contacted the Debian package maintainer of LeoCAD, he will have a look.

**Comment by nathaneltitane** [comment]
@patrickrst  - any chance he can pull the latest code into a package as well?
