### ISSUE TITLE
Certificate error for https://leocad.org

### ISSUE THREAD

**Issue by ali1234** [leozide/leocad#283]
http://leocad.org and http://www.leocad.org redirect to https://www.leocad.org which presents a LE certificate.

But visiting https://leocad.org results in a certificate error - it presents the github certificate.

According to the github docs, it should be possible to make both `leocad.org` and `www.leocad.org` work: https://help.github.com/articles/about-supported-custom-domains/

And LE definitely supports it too - although your current certificate appears to be for `www.leocad.org` only, you can make one for `leocad.org` and `www.leocad.org` without having to use a wildcard.

**Comment by leozide** [comment]
I'm not sure how to change this, the current certificate was created automatically by Github.

**Comment by tcuje** [comment]
I think the issue is with the DNS records for leocad.org. It is currently a CNAME record for leozide.github.io., which is not a good idea according to [docs](https://help.github.com/en/articles/setting-up-an-apex-domain) (see warning) and [this](https://dnsmadeeasy.com/services/anamerecords/) (see How it works).

To fix this issue the DNS record should be changed from CNAME into an ANAME record at tektonic.net DNS server.

**Comment by leozide** [comment]
I think I had an extra CNAME record and the A records were pointing to the wrong IP. I've fixed that and  leocad.org is redirecting me to www.leocad.org now without a certificate error, but let me know if it's still broken.

**Comment by tcuje** [comment]
Issue still persists for me right now. To reproduce this you might have to restart your browser/clear cache. Once you follow the insecure connection the browser receives a redirect, caches it and never uses the actual leocad.org, www.leocad.org instead.

DNS dig says the entries are correct now:
```
:~$ dig +noall +answer leocad.org
leocad.org.		159	IN	A	185.199.108.153
leocad.org.		159	IN	A	185.199.111.153
leocad.org.		159	IN	A	185.199.109.153
leocad.org.		159	IN	A	185.199.110.153```

Step 4 [here](https://help.github.com/en/articles/setting-up-an-apex-domain#configuring-a-records-with-your-dns-provider) suggests to remove and readd the custom URL after changing the DNS entries, maybe this helps...

**Comment by leozide** [comment]
I'm reopening to investigate but it's still working for me after a reboot. I had done step 4 before but I repeated it once again just in case.
