### ISSUE TITLE
First 2019 release

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#289]
Seems like LDraw now released (or prepared for new release)

- LDraw parts update 2018-02 released on Dec 8, 2018 - https://www.ldraw.org/parts/latest-parts.html
- New `MLCad.ini` 2018-02 released on Feb 4, 2019 - https://www.ldraw.org/news/41/151/MLCad.ini-2018-02-update-now-available.html
- AIO Installer 2018-02 released on Feb 16, 2019 - https://www.ldraw.org/news/42/151/LDraw-All-In-One-Installer-2018-02-v1-now-available.html

**Comment by knightknight** [comment]
I'm itching to finish some models that need the flexible parts. Any news on the next release?

**Comment by Symbian9** [comment]
> I'm itching to finish some models that need the flexible parts. Any news on the next release?

@knightknight , You could already use latest nightly builds ;-)

- https://github.com/leozide/leocad/releases/tag/continuous

**Comment by knightknight** [comment]
@Symbian9 thanks! Last time I check it only had OSX release. 

Fyi, for anyone downloading the nightly release. I had to add the ldraw library via the preferences for the Windows release otherwise all good. :)

**Comment by leozide** [comment]
Windows was only added last week. I removed the library to keep the download smaller.

**Comment by Symbian9** [comment]
LDraw released `2019-1` (`2018-2`) official parts update:

- https://forums.ldraw.org/thread-23517.html

Here are listed official/unofficial & other (3rd-party) LDraw parts

- https://github.com/Symbian9/AWESOME-LDraw

**Comment by Symbian9** [comment]
`MLCad.ini` version `2019-01` released

- https://forums.ldraw.org/thread-23553.html
  - http://www.holly-wood.it/files/mlcad/MLCad_ini_2019-01.zip

**Comment by knightknight** [comment]
@Symbian9, so what do you use for the `Color Configuration` and `LGEO library` settings?

**Comment by Symbian9** [comment]
> what do you use for the `Color Configuration`

You mean `LDConfig.ldr`?

- https://github.com/leozide/leocad/issues/349

> and `LGEO Library`

I don't use `LGEO`, because for rendering I use [Blender](https://blender.org) + `ImportLDraw` addon

- https://github.com/TobbyLobster/ImportLDraw

**Comment by knightknight** [comment]
@Symbian9, cool thanks didn't understand what the Color Configuration was for. All ready using Blender and the ImportDraw addon. 👍

**Comment by leozide** [comment]
New version released.

**Comment by Symbian9** [comment]
Would you rebuild binary for `19.07` release with latest two commits?

**Comment by leozide** [comment]
I'm building a patch.
