### ISSUE TITLE
Adding flexible hoses

### ISSUE THREAD

**Issue by knightknight** [leozide/leocad#292]
I'm using LeoCAD on OSX, how do add hoses that are bent around objects?

**Comment by leozide** [comment]
- Find the hose that you want to add, for example "Technic Ribbed Hose 11L".
- When you add it to your model you'll see that it has 2 green cubes at the edges
- Move/rotate the cubes and drag the tension line to bend it to the desired shape
- Right click on the hose and choose "Add control point" to add new bends

Note that not all flexible elements are supported, let me know if there's a particular part that you need and I'll add support for it

**Comment by knightknight** [comment]
@leozide, thanks for the reply. I can see the green cubes on the Technic Ribbed Hose 11L.

The part I was trying to bend was 'Medium Stone Gray Plastic Hose 16.8 cm (76259)' recreating the front hoses on 'Luke's Landspeeder Set 75173'. The parts that appear for '7625' 'Technic Flex-System don't have the flex support.

I also had a similar issue trying to use hoses for the 'Back to the Future Time Machine Set 21103'. Again not flex supported.

- Black Flexible Hose 8.5 with Tabbed Ends (6211)
- Black Flexible Hose 8.5 with Tabless Fixed Ends (64230)

**Comment by leozide** [comment]
I've added support for all ~30 Flex System hoses I could find, but I don't see any of the other 4 parts you mentioned in the latest library. Are these official parts?

**Comment by knightknight** [comment]
I believe all parts are offical based on the 18.02 LeoCAD release. I was taking brick numbers from [brickowl](https://www.brickowl.com), although sometimes they don't match up. 

So for 76259 the parts in LeoCAD are 76250, 76252 and 76254.

![](https://i.postimg.cc/C5WTt04G/leocad-hose-01.png)

Both '[Black Flexible Hose 8.5 with Tabbed Ends (6211)](https://www.brickowl.com/catalog/lego-flexible-hose-8-5-with-tabbed-ends-6211)' and '[Black Flexible Hose 8.5 with Tabless Fixed Ends (64230)](https://www.brickowl.com/catalog/lego-black-flexible-hose-8-5-with-tabless-fixed-ends-64230)' the best match I found was 73590b and 73590a.

![](https://i.postimg.cc/LX33w3BN/leocad-hose-02.png)

With '[Blue 4mm Diameter Pneumatic Hose 11.2 cm (88355)](https://www.brickowl.com/catalog/lego-blue-4mm-diameter-pneumatic-hose-11-2-cm-88355)' again I will just use the best match available.

Will we need to compile an updated version or will you push a new [release](https://github.com/leozide/leocad/releases/) soon?

**Comment by leozide** [comment]
My Mac died last December so I don't how I'll make new OSX releases from now on. I might be able to setup something using Travis CI but I won't be able to test builds.

I've added support for 76250, 76252 and 76254 yesterday, I'll take a look at 73590b and 73590a.

**Comment by knightknight** [comment]
Ok.

For those using [brew](https://github.com/Homebrew/brew) on OSX there appears to be a [brew cask for LeoCAD](https://github.com/Homebrew/homebrew-cask/pull/59109) which is at the current version.

```bash
brew cask info leocad
leocad: 18.02
https://github.com/leozide/leocad
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/leocad.rb
```

**Comment by leozide** [comment]
I've added support for 73590b and 73590a

**Comment by knightknight** [comment]
@leozide, thank you. I'll re-open if I come across any others.

**Comment by Nomkid** [comment]
There's also a bunch of wires (for Mindstorms and other electric things) that don't flex, though I'm not sure which ones are actually supposed to.
