### ISSUE TITLE
Load `minifig.ini` from folder where LDraw parts placed

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#293]
Add to *LeoCAD* function for load custom `minifig.ini` (if it exists) from folder where LDraw parts located , in same way as `ldrawunf.zip` recognized and loaded.

**Comment by leozide** [comment]
It already does, but it looks for mlcad.ini instead.

https://github.com/leozide/leocad/blob/master/common/minifig.cpp#L39

**Comment by Symbian9** [comment]
> but it looks for `mlcad.ini` instead.

Great! Thanks for pointing!

But, let's change `...QLatin1String("mlcad.ini")...` to `...QLatin1String("minifig.ini")...`
