### ISSUE TITLE
Upload OSX builds from Travis CI

### ISSUE THREAD

**Issue by leozide** [leozide/leocad#299]

**Comment by Symbian9** [comment]
It would be cool upload all nightly builds (Linux, MacOS, Windows) as `continuos` release on GitHub. Check this example:

- https://github.com/olive-editor/olive/releases/tag/continuous

Take a look:

- https://github.com/olive-editor/olive/blob/master/.travis.yml
  - https://github.com/olive-editor/olive/tree/master/.travis
    - https://github.com/olive-editor/olive/blob/master/.travis/after_success.sh

More details:

- https://github.com/probonopd/uploadtool

**Comment by leozide** [comment]
I've thought about doing that before but I dislike that it shows the continuous packages first, I'd rather people see the stable releases first when they go to the releases page. I want to discourage regular users to use untested versions.

**Comment by Symbian9** [comment]
@leozide, You could customize description of `continuous` release by adding notes with link to latest stable release . For example:

> NOTE: This is nightly development build for testing purposes only!
> 
> Use latest stable build instead:
> 
> - https://leocad.org/download/

Think, @probonopd could help with it.

**Comment by Symbian9** [comment]
Please, upload nightly builds as `continuous` release, because uploading to transfer.sh often not finished

- https://api.travis-ci.org/v3/job/504408202/log.txt

**Comment by Symbian9** [comment]
Which version of LeoCAD*.AppImage deployed to GitHub: Qt4.x or Qt5.x?

- https://github.com/leozide/leocad/releases/tag/continuous

Maybe, need indicate it in AppImage file name?

**Comment by leozide** [comment]
Qt5, I don’t really want to support Qt4 anymore.

**Comment by Symbian9** [comment]
> Qt5, I don’t really want to support Qt4 anymore.

OK.
