### ISSUE TITLE
LeoCAD just crashed

### ISSUE THREAD

**Issue by virtualrepublic** [leozide/leocad#3]
This morning LeoCAD on my Alienware 17 with GTX 880M latest driver worked fine.

Now I get a crash. I uninstalled. Installed. Still crashing.

Attached you will receive the dump-file.
[minidump.zip](https://github.com/leozide/leocad/files/602034/minidump.zip)

**Comment by leozide** [comment]
Can you open a command prompt and type:

reg export "HKCU\software\leocad software" leocad.reg

and then attach the leocad.reg file it creates?

There's something wrong with the saved window position, deleting the key HKCU\software\leocad software\mainwindow from the registry should fix this.

**Comment by virtualrepublic** [comment]
Here's the leocad.reg.
[leocad.zip](https://github.com/leozide/leocad/files/602937/leocad.zip)

**Comment by leozide** [comment]
This is a Qt bug: https://bugreports.qt.io/browse/QTBUG-48288

I'll upgrade Qt for the next version.

**Comment by leozide** [comment]
I've uploaded a new version that should fix this.
