### ISSUE TITLE
Nothing visible after Move to New Model

### ISSUE THREAD

**Issue by j6t** [leozide/leocad#30]
Under certain (frequent) circumstances, after using Move to New Model nothing is visible in the view tab of the new model.

To reproduce, do the following:

1. Create a new project
2. Insert 2 pieces, each in its own step.
3. Select the piece in the second step.
4. Select Piece->Move to New Model (accept the default name)
5. Select the new model from the Model menu

Notice that the view is blank. There is not even the usual ground pattern. Now:

6. Press H (Home viewpoint). Nothing happens.
7. Go to the next step ("Next" button). Nothing happens.
8. Press H (Home viewpoint). Now the piece becomes visible.

Also note that there is an empty "Step 1" in the timeline of the new model. This becomes really annoying if the "Move to New Model" was used on pieces in a very late step: there are many empty steps before the actual pieces in the new model.

**Comment by leozide** [comment]
I've fixed both issues.
