### ISSUE TITLE
LeoCAD load only upper-case named external parts/submodels

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#302]
Is it possible use external submodules stored in same folder where model file stored?

I tried open "Datsville" model (`datsville.ldr`), but LeoCAD could not recognize and import external submodules stored in same folder

- https://sourceforge.net/projects/datsville

**Comment by leozide** [comment]
Datsville loads for me. There was an issue with the camera after it's loaded but I fixed it.

**Comment by Symbian9** [comment]
> Datsville loads for me

But not for me. Here is how LeoCAD load `datsville.ldr`

![pic.1](https://i.imgur.com/6A6cZPy.png)

Datsville version: `rev550` (files from `datsville-master` directory)

LeoCAD version: `git.188860f` (AppImage)

OS: Debian 9.x (x86_64)

**Comment by Symbian9** [comment]
Seems like this issue related to case-sensitive file naming.

Datsville ZIP distribution include directory `datsville_master` with only lower-case named files.

Here is `datsville.ldr` source:

```
0 Datsville
0 Name: datsville.ldr
0 Author: John VanZwieten, Michael Horvath, Tore Eriksson
0 !LICENSE Redistributable under CC BY-SA version 3.0 : see https://creativecommons.org/licenses/by-sa/3.0/
0 Unofficial Datsville Model
0 ROTATION CENTER 0 0 0 1 "Custom" 
0 ROTATION CONFIG 0 0
1 16 0 0 0 1 0 0 0 1 0 0 0 1 layer_blocks_base.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 layer_streets_base.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 layer_river.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 layer_blocks_overlay.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 layer_streets_overlay.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 layer_traffic.ldr
0 16 0 0 0 1 0 0 0 1 0 0 0 1 layer_terrain.ldr
0
```


As you can see `datsville.ldr` include linked external parts/submodules, that has lower-case names:

- `layer_blocks_base.ldr`
- `layer_streets_base.ldr`
- `layer_river.ldr`
- `layer_blocks_overlay.ldr`
- `layer_streets_overlay.ldr`
- `layer_traffic.ldr`
- `layer_terrain.ldr`

But when I open `datsville.ldr` LeoCAD try load upper-case named external parts/submodules, that not exists (see screenshot above):

- `LAYER_BLOCKS_BASE.LDR`
- `LAYER_STREETS_BASE.LDR`
- `LAYER_RIVER.LDR`
- `LAYER_BLOCKS_OVERLAY.LDR`
- `LAYER_STREETS_OVERLAY.LDR`
- `LAYER_TRAFFIC.LDR`
- `LAYER_TERRAIN.LDR`

So, on case-sensitive file systems (such as Linux use) LeoCAD always try load upper-case named linked external parts/submodules and ignore case sensitive names.
