### ISSUE TITLE
Recognize external parts (.dat) located in same folder

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#305]
If there are DAT-files in same folder where opened LDR/MPD file located, recognize it as external parts.

**Comment by leozide** [comment]
I don't understand this bug, how is this different than the previous one you wrote about datsville?

**Comment by Symbian9** [comment]
This is not a bug report for Datsville.

Here I mean that need add option for LeoCAD recognize DAT-files stored in same directory where opened LDR/MPD file placed (no matter, if opened LDR/MPD files include those DAT files or not)

**Comment by leozide** [comment]
Then I believe this is also a duplicate of #181.
