### ISSUE TITLE
Keyboard shortcuts not working in translated versions

### ISSUE THREAD

**Issue by tcuje** [leozide/leocad#308]
I tested the German translation, but the keyboard shortcuts stopped working.

The issues seems to be that the shortcuts are translated, too. Where "Ctrl+N" is translated to "Strg+N", which is good for readability. Unfortunately the keyboard shortcuts parser seems not to expect translated strings.

To solve the issue I suggest that the keyboard shortcut strings are only translated in the UI.

**Comment by leozide** [comment]
How are you testing this? When I set LANG=de_DE and run I get translated text and shortcuts are working, but they are displayed as Ctrl+ in the menus.

**Comment by tcuje** [comment]
I also set LANG=de_DE.UTF-8 and my shortcuts are all crippled to this:
![image](https://user-images.githubusercontent.com/4201214/53654767-db8bd200-3c4e-11e9-9c87-ef01c1c1b53c.png)
But they are not working so pressing O doesn't give me the open file dialog.

I can also re-assign the correct (working) shortcuts to each action, the UI the says Ctrl+O again, and they get back working. If I hit on reset to default they are all removed again and set to the crippled ones. Maybe just an issue with the default shortcuts...

**Comment by tcuje** [comment]
When I remove the translation for the keyboard shortcuts like Strg+O back to Ctrl+O everythings works as expected.

**Comment by tcuje** [comment]
translate should not be used here: https://github.com/leozide/leocad/blob/51bf3d00780c2fab712d697ca8828792ae21b4f9/common/lc_shortcuts.cpp#L61
Instead the QT translator should be included. See my pull request for fixing commit.
