### ISSUE TITLE
ldr vs mpd file save bug

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#311]
Hi Leo,

Hope all is well.

I started a new project and saved the initial file as a standard ldr.
Upon adding a minifig through the wizard, i the used the 'move to new model' feature, which then turns the file into an mpd, but upon wanting to save, leocad does not detect the structure change and prompt to save as mpd.

It kept the original ldr extension.

Can the ave logic be reviewed to detect submodels and prompt to save as multipart data file when there is at least one submodel aside from the main?

Thank you

**Comment by leozide** [comment]
I tried testing this and the file is saved correctly, even though it has the ldr extension. Was the submodel not saved?

I can't find any places that state that mpd files need to have the mpd extension, it's just a meta command in an ldraw file.

**Comment by nathaneltitane** [comment]
Well, wouldn't it be logical for the file to be saved with the appropriate extension?

Other utilities and tools exist that filter and identify files by there extension and load them that way...

I myself use the mpd extension as my reference point to find and edit the master model files I've created and then port the individual updated submodels into their own respective ldr for keepsake.

I may be mistaken, but that creates confusion as to why the mpd extension even exists if it's not to reflect a different kind of file format and content structure.

**Comment by leozide** [comment]
I think the mpd extension is just legacy now but I could be wrong. It's probably a minor change to prompt  the user to rename the file but wouldn't it be simpler if all files were just .ldr?

**Comment by nathaneltitane** [comment]
I don't believe it would make it simpler.
Also:

http://www.ldraw.org/article/47.html
