### ISSUE TITLE
Wavefront export rotation has swapped y and z axis

### ISSUE THREAD

**Issue by tcuje** [leozide/leocad#329]
LeoCAD:
![image](https://user-images.githubusercontent.com/4201214/54299152-922a7380-45ba-11e9-9dc5-8a168dff4dc4.png)

Wavefront Import in Blender:
![image](https://user-images.githubusercontent.com/4201214/54299202-ab332480-45ba-11e9-82ee-6c39c9e37cbf.png)

**Comment by leozide** [comment]
I think this is a blender specific problem and not related to LeoCAD. There should be a place where you can configure the axis in Blender.

**Comment by tcuje** [comment]
Actually the same issue with the same rotation appeared to me in Android AR, but I wanted to report something reproducable. Also if you take a look at the axis in the lower left corners, they're the same.

Maybe I can find some documentation, which clarifies this...

**Comment by leozide** [comment]
It's an option on the Blender import dialog, look at the bottom left:

![image](https://user-images.githubusercontent.com/9685066/54321098-cbf47d80-45ac-11e9-825b-e868ac3eb148.png)

**Comment by tcuje** [comment]
Cool thanks! Unfortunately this doesn't fix my issue with Android

**Comment by tcuje** [comment]
I still think that the axis should be swapped for convenience, but not an actual issue.
