### ISSUE TITLE
Add search fields for filter shortcuts on "Keybord" and "Mouse" tabs in "Preferences" dialog

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#338]
Add search fields for filter (quick search) shortcuts in "Preferences" dialog

Such field implemented in *Olive*

- https://github.com/olive-editor/olive
  - https://github.com/olive-editor/olive/issues/259

**Comment by probonopd** [comment]
Please check out https://github.com/aoloe/scribus-plugin-actionSearch.

Is there much Scribus-specific about it @aoloe? Could it be turned into a generic Qt plugin that applications like this one could use?

**Comment by Symbian9** [comment]
> It's certainly nice to be able to search somewhere in a settings screen

Requested already in separate issue:

- https://github.com/leozide/leocad/issues/337
