### ISSUE TITLE
[Feature] Mirror or symmetry a part/selection across a selected axis

### ISSUE THREAD

**Issue by knightknight** [leozide/leocad#339]
The Mirror tool mirrors a selection across a selected axis, similar to Blender.

https://docs.blender.org/manual/en/latest/modeling/meshes/editing/transform/mirror.html

https://docs.blender.org/manual/en/latest/modeling/meshes/editing/basics/symmetry.html

**Comment by leozide** [comment]
This has been requested before but I'm against it because mirroring creates parts that don't exist in real life.

**Comment by app4soft** [comment]
@leozide, What about creating mirror option at least for flexible parts' handles according parts' origin in relative X, Y or Z direction?

Here is the simple example of flexible part with a complex deformation, and it needs to create the same part, but with flipped handles positions according to origin in X direction (in local/relative reference coordinate system).

```
0 
0 Name: Submodel #1.ldr
0 Author: 
0 !LEOCAD SYNTH BEGIN
0 !LEOCAD SYNTH CONTROL_POINT -219.8671 262.1261 41.1355 0.205489 -0.924962 -0.319717 0.9782 0.204134 0.038138 0.029989 -0.320584 0.946745 200
0 !LEOCAD SYNTH CONTROL_POINT 1 0 1 1 0 0.000001 0 1 0 -0.000001 0 1 0.1
1 7 -70 -146.9585 -101.8163 0 0 -1 -0.701532 -0.712638 0 -0.712638 0.701532 0 22463.dat
0 !LEOCAD SYNTH END
```
