### ISSUE TITLE
Broken color config page

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#340]
Check this:

- https://forums.ldraw.org/thread-23301.html

### Reference

- http://www.ldraw.org/article/547.html

**Comment by leozide** [comment]
I don't understand what this issue means.

**Comment by Symbian9** [comment]
Could you check LDraw colors representation inside LeoCAD?

As there was some issue on LDraw website with colors config:

- https://forums.ldraw.org/thread-23301.html

**Comment by leozide** [comment]
This only affects their website.
