### ISSUE TITLE
Scale inserted submodel (and parts)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#344]
Add property "Scale" on *"Properties"* widget, that should be used for change inserted submodel or parts scale factor.

![Scale Factor property](https://i.imgur.com/4qMUP1V.png)

Of course, it could be extended to:

- Properties:
  - ...
  - Scale:
    - X = `0.625` (set custom scale on X axis)
    - Y = `0.625` (set custom scale on Y axis)
    - Z = `0.625` (set custom scale on Z axis)
  - ...

For, example:

> You can mix LEGO System parts with Modulex parts if you make a separate Modulex sub-model and scale it down by `0.625`
>
> Example:
>
> ```
> 1 7 0 -192 -50 0.625 0 0 0 0.625 0 0 0 0.625 Modulex_submodel.ldr
> ```

### REFERENCE

- http://www.chris-w-dee.co.uk/Modulex/
- https://forums.ldraw.org/thread-5616.html

**Comment by leozide** [comment]
I'm against allowing scale changes, as it will likely create non-existent parts. Loading scaled files is supported.

**Comment by j6t** [comment]
Can this issue be closed then?
