### ISSUE TITLE
Add support for LeoCAD package

### ISSUE THREAD

**Issue by LeandroStanger** [leozide/leocad#345]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by leozide** [comment]
We already have AppImage available, what's the advantage of Flatpak over it?

Looking at the (probably biased) comparison in https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison I don't really see any reasons to add another package.

**Comment by Symbian9** [comment]
AppImage is much better with less dependencies than Flatpak.

**Comment by LeandroStanger** [comment]
I am [Endless OS](endlessos.com) user only Flatpak is supported

**Comment by leozide** [comment]
https://community.endlessos.com/t/appimage-no-endless-instalar-aplicativo-fora-da-central-de-programas/7999/2 says that it AppImages work even though they are not officially supported. Have you tried running one of the AppImages from the releases page? What errors do you get?

**Comment by ZanderBrown** [comment]
I have produced a flatpak manifest for [the latest release](https://github.com/leozide/leocad/releases/tag/v19.07.1) which seems to work

Note it only has x11 access rather than wayland + fallback as either Qt or yourselves have some render bugs to fix there

```json
{
    "id": "org.leocad.LeoCAD",
    "runtime": "org.kde.Platform",
    "runtime-version": "5.12",
    "sdk": "org.kde.Sdk",
    "command": "leocad",
    "rename-icon": "leocad",
    "rename-desktop-file": "leocad.desktop",
    "rename-appdata-file": "leocad",
    "finish-args": [
        "--device=dri",
        "--share=ipc",
        "--socket=x11",
        "--filesystem=home",
        "--filesystem=xdg-config/kdeglobals:ro"
    ],
    "modules": [
        {
            "name": "leocad",
            "buildsystem": "qmake",
            "config-opts": [
            	"INSTALL_PREFIX=/app"
            ],
            "sources": [
                { 
                    "type": "git", 
                    "url": "https://github.com/leozide/leocad.git",
                    "tag": "6c7291b919a9128518c682a706fb53399feb6f81"
                } 
            ],
            "post-install": [
                "mkdir -p /app/share/icons/hicolor/scalable/apps",
                "cp /app/share/icons/hicolor/scalable/mimetypes/application-vnd.leocad.svg /app/share/icons/hicolor/scalable/apps/leocad.svg"
            ]
        }
    ]
}
```

Hopefully you can submit that to flathub and all will be fine, otherwise the flathub folks will help you out

**Comment by leozide** [comment]
https://github.com/flathub/flathub/pull/1122
