### ISSUE TITLE
Enhancement - prevent window border from overlapping preview panel/list

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#346]
As you can see (lower left hand side of window) pushing the parts preview panel all the way through cuts off the thumbnail.

Maybe you can set a boundary to match the selected thumbnail size or a certain amount of characters for the 'no icons' selection to prevent cut-off.

![Screenshot from 2019-05-11 13 20 00](https://user-images.githubusercontent.com/5674757/57572985-e8b40280-73ef-11e9-8645-f0ce443451c5.png)

**Comment by nathaneltitane** [comment]
@leozide works great when the panel is vertical, you forgot to account for horizontal positioning!

**Comment by leozide** [comment]
The whitespace on the right is because of the properties widget
