### ISSUE TITLE
Parts creating/editing (authoring)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#347]
Add functionality for creating & editing parts directly in *LeoCAD*.

Use *LDForge* (Qt-based) sources, if possible:

- sources - https://bitbucket.org/crimsondusk/ldforge
  - discussion - https://forums.ldraw.org/thread-13858.html
- old sources - https://github.com/crimsondusk/ldforge
  - old discussion - https://forums.ldraw.org/thread-8711.html
- tutorial - http://jc-tchang.philohome.com/manuel/LDForge.htm

![LDForge screen](https://forums.ldraw.org/attachment.php?thumbnail=1335)

### REFERENCE

- *"Do we need another LDraw building program?"* - https://forums.ldraw.org/thread-14370.html

**Comment by leozide** [comment]
This is an interesting idea but outside the scope of the application.
