### ISSUE TITLE
Misspelling in the ldconfig.ldr file name?

### ISSUE THREAD

**Issue by yurivict** [leozide/leocad#348]
It is spelled in the lowercase here https://github.com/leozide/leocad/blob/master/common/lc_library.cpp#L308, however the distribution has it with mixed case http://www.ldraw.org/library/official/LDConfig.ldr Also see the Arch package:https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ldraw-parts-library

**Comment by Symbian9** [comment]
Related

- https://github.com/leozide/leocad/issues/290
- https://github.com/leozide/leocad/issues/293
