### ISSUE TITLE
Build break

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#350]
The Qt-48 build has been broken since [Also print continuous build on the command line - fb0bcc4](https://github.com/leozide/leocad/commit/fb0bcc48ec7ced83c95990982f663c4dacbcc816).

The BASE-48 build shows green but...
![Screenshot - 30_05_2019 , 04_56_51](https://user-images.githubusercontent.com/13388970/58605624-b849e080-8298-11e9-8969-c56c24fe05fd.png)

The build has actually abnormal ended.
![Screenshot - 30_05_2019 , 04_56_24](https://user-images.githubusercontent.com/13388970/58605812-766d6a00-8299-11e9-8c6e-80c8d1e5688f.png)

Also, very strangely on Ubuntu Xenial, the build also abends with `'function' is not a member of 'std'` although -std=c++11 is specified. Other flavours of Linux (Arch, Fedora), macOS, and even Ubuntu Trusty used to build my AppImage, do not show this behaviour.
![Screenshot - 30_05_2019 , 04_59_22](https://user-images.githubusercontent.com/13388970/58605723-1b3b7780-8299-11e9-8499-7c7fff4d1abf.png)

**Comment by leozide** [comment]
The second error is probably missing #include functional.h, you can try that to unblock you. I’ll take a look at everything tomorrow

**Comment by trevorsandy** [comment]
Yep, `#include <functional>` did the trick.

**Comment by leozide** [comment]
It should all be fixed now, thanks for reporting.
