### ISSUE TITLE
BrickLink Export MINQTY > 1 results in invalid quantity

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#353]
A part quantity of 1 will trigger suppression of the `<MINQTY/>` BrickLink export tag.

~~~
	if (Count > 1)
	{
		sprintf(Line, "    <MINQTY>%d</MINQTY>\n", Count);
		BrickLinkFile.WriteLine(Line);
	}
~~~

However, although Bricklink supports an empty Quantity field, when a BrickLink site export is performed, the "empty" value returns as **-1**. For example, if the following exported XML is uploaded to Bricklink
```
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>2444</ITEMID>
    <COLOR>11</COLOR>
  </ITEM>
</INVENTORY>
```
it looks like this
![image](https://user-images.githubusercontent.com/11013917/58945430-82bb6080-878c-11e9-922c-bac696b43c5b.png)

the quantity value is a **-** instead of **1**
![image](https://user-images.githubusercontent.com/11013917/58945517-abdbf100-878c-11e9-98a2-cdaa85f9a06c.png)

Upon download, the Bricklink Wanted list shows the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<INVENTORY>
<ITEM>
<ITEMTYPE>P</ITEMTYPE>
<ITEMID>2444</ITEMID>
<COLOR>11</COLOR>
<MAXPRICE>-1.0000</MAXPRICE>
<MINQTY>-1</MINQTY>
<CONDITION>X</CONDITION>
<NOTIFY>N</NOTIFY>
</ITEM>
</INVENTORY>
```

and when this Wanted list is uploaded to Rebrickable, it complains about **-1** being an invalid quantity.

Cheers,

**Comment by leozide** [comment]
I don't remember why the >1 was there, I've removed it.
