### ISSUE TITLE
Import Stud.io models

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#356]
Add option for import *Stud.io* files

Some details about file format from *Rebrickable's «Guide to Stud.io»*

>  ### What is Stud.io?
>
> Bricklink Stud.io (SIO) is a freeware computer program produced by BrickLink Limited; it is available for macOS and Windows (32-bit and 64-bit), and it allows users to build models and scenes using virtual Lego bricks, in a computer-aided design like manner.
>
> ### What is an IO file?
>
> A three-dimensional model or scene created by Bricklink Stud.io (SIO); it is saved in a password protected compressed .ZIP format and contains six files:
>
> - `THUMBNAIL.PNG` - a .PNG design preview
> - `.INFO` - contains the Stud.io version and a parts count
> - `errorPartList.err` - a parts error list
> - `model.ldr` - the LDraw file for the model
> - `model2.ldr` - the LDraw file for the model with included part definitions
> - `modelv1.ldr` - unknown
>
> ### What is a scene?
> 
> One or more models can be put into a scene, with additional floor and background, one or more light sources and a camera that determines how is the scene is viewed. An .io file can contain a single model, but it can also contain many different models, for example a self-build LEGO city.

Here are `*.io` files for testing:

- https://reprage.com/designs/2019-02-27-SpaceX-Spaceport_stud.io
- https://github.com/jussikinnula/lego-studio-train-models

### REFERENCE

- https://rebrickable.com/help/guide-to-stud-io
- https://reprage.com/post/lego-spacex-drone-ship
- https://github.com/Albe96XDA/Zip-Password-Cracker

**Comment by darkstar** [comment]
As long as the password to those zip files is not publicly known, there's probably no way to add this feature

**Comment by leozide** [comment]
I've seen the password posted somewhere before but I don't want to deal with any of the headaches that could come from including it in the source code.

**Comment by kuukow1** [comment]
> Add option for import _Stud.io_ files
> 
> Some details about file format from _Rebrickable's «Guide to Stud.io»_
> 
> > ### What is Stud.io?
> > Bricklink Stud.io (SIO) is a freeware computer program produced by BrickLink Limited; it is available for macOS and Windows (32-bit and 64-bit), and it allows users to build models and scenes using virtual Lego bricks, in a computer-aided design like manner.
> > ### What is an IO file?
> > A three-dimensional model or scene created by Bricklink Stud.io (SIO); it is saved in a password protected compressed .ZIP format and contains six files:
> > 
> > * `THUMBNAIL.PNG` - a .PNG design preview
> > * `.INFO` - contains the Stud.io version and a parts count
> > * `errorPartList.err` - a parts error list
> > * `model.ldr` - the LDraw file for the model
> > * `model2.ldr` - the LDraw file for the model with included part definitions
> > * `modelv1.ldr` - unknown
> > 
> > ### What is a scene?
> > One or more models can be put into a scene, with additional floor and background, one or more light sources and a camera that determines how is the scene is viewed. An .io file can contain a single model, but it can also contain many different models, for example a self-build LEGO city.
> 
> Here are `*.io` files for testing:
> 
> * https://reprage.com/designs/2019-02-27-SpaceX-Spaceport_stud.io
> * https://github.com/jussikinnula/lego-studio-train-models
> 
> ### REFERENCE
> * https://rebrickable.com/help/guide-to-stud-io
> * https://reprage.com/post/lego-spacex-drone-ship
> * https://github.com/Albe96XDA/Zip-Password-Cracker
