### ISSUE TITLE
Visual C Runtime DLL missed in Windows binary

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#358]
Some users reported that latest Windows binary could not be installed due to missed DLL files:

- https://forums.ldraw.org/thread-23434-post-32597.html#pid32597

> No I can't install it. It uses a DLL missing from my ageing system (tried to install it in the past, but failed, known problem). 

- https://forums.ldraw.org/thread-23434-post-32600.html#pid32600

> Well, technically it's not a problem with LeoCAD but with my system (I do have the same problem when I try to install other programs). The DLL is `api-ms-win-crt-runtime-l1-1-0.dll`

- https://forums.ldraw.org/thread-23434-post-32608.html#pid32608

> That's a visual c runtime dll, the leocad installer should include the version that comes with the compiler used.

**Comment by MinnieTheMoocher** [comment]
This issue was closed.

So was there a bugfix commit?

Or was the bug report an error?

**Comment by leozide** [comment]
Yes, 789fca6a0c715e3c99251f2d88e1ce8c24e1e4c8
