### ISSUE TITLE
Newbie trying to compile 18.02, fails with no QtOpenGL

### ISSUE THREAD

**Issue by William-Purvis** [leozide/leocad#362]
I've just downloaded the 18.02 distro and tried to compile as per the website documentation.
qmake leocad.pro       ran OK with no errors,
make fails with:
lrelease-qt4 -silent resources/leocad_fr.ts -qm resources/leocad_fr.qm
lrelease-qt4 -silent resources/leocad_pt.ts -qm resources/leocad_pt.qm
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qarraydialog.ui -o build/release/.ui/ui_lc_qarraydialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qgroupdialog.ui -o build/release/.ui/ui_lc_qgroupdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qaboutdialog.ui -o build/release/.ui/ui_lc_qaboutdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qeditgroupsdialog.ui -o build/release/.ui/ui_lc_qeditgroupsdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qselectdialog.ui -o build/release/.ui/ui_lc_qselectdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qpropertiesdialog.ui -o build/release/.ui/ui_lc_qpropertiesdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qhtmldialog.ui -o build/release/.ui/ui_lc_qhtmldialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qminifigdialog.ui -o build/release/.ui/ui_lc_qminifigdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qpreferencesdialog.ui -o build/release/.ui/ui_lc_qpreferencesdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qcategorydialog.ui -o build/release/.ui/ui_lc_qcategorydialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qimagedialog.ui -o build/release/.ui/ui_lc_qimagedialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qupdatedialog.ui -o build/release/.ui/ui_lc_qupdatedialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qfinddialog.ui -o build/release/.ui/ui_lc_qfinddialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_qmodellistdialog.ui -o build/release/.ui/ui_lc_qmodellistdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_renderdialog.ui -o build/release/.ui/ui_lc_renderdialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic qt/lc_setsdatabasedialog.ui -o build/release/.ui/ui_lc_setsdatabasedialog.h
g++ -m64 -pipe -O2 -std=c++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -Iqt -Icommon -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/release/.moc -Ibuild/release/.ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -x c++-header -c common/lc_global.h -o build/release/.obj/leocad.gch/c++
common/lc_global.h:8:20: fatal error: QtOpenGL: No such file or directory
compilation terminated.
make: *** [build/release/.obj/leocad.gch/c++] Error 1
Makefile:611: recipe for target 'build/release/.obj/leocad.gch/c++' failed

I have QtOpenGL 5.5.1 installed. I'm happy to provide further info it someone tells me what is needed.
Thanks,
Bill

**Comment by leozide** [comment]
What do you have in /usr/include/x86_64-linux-gnu/qt5/QtOpenGL?

**Comment by William-Purvis** [comment]
I replied to the query by email, but it doesn't appear to have found its way into the system.
I'll repeat it here:
--------------------------------------------------------------------
Initially:
    5.5.1/QtOpenGL/private/*
I tried copying all the * up into the upper level:
so I now have:

$ ls -lR /usr/include/x86_64-linux-gnu/qt5/QtOpenGL/
/usr/include/x86_64-linux-gnu/qt5/QtOpenGL/:
total 140
drwxr-xr-x 3 root root  4096 Feb  1  2018 5.5.1
-rw-r--r-- 1 root root  4753 Jun 25 14:47 qgl2pexvertexarray_p.h
-rw-r--r-- 1 root root 16204 Jun 25 14:47 qgl_p.h
-rw-r--r-- 1 root root  2487 Jun 25 14:47 qglcustomshaderstage_p.h
-rw-r--r-- 1 root root 19610 Jun 25 14:47 qglengineshadermanager_p.h
-rw-r--r-- 1 root root 20751 Jun 25 14:47 qglengineshadersource_p.h
-rw-r--r-- 1 root root  5250 Jun 25 14:47 qglframebufferobject_p.h
-rw-r--r-- 1 root root  3312 Jun 25 14:47 qglgradientcache_p.h
-rw-r--r-- 1 root root  3323 Jun 25 14:47 qglpaintdevice_p.h
-rw-r--r-- 1 root root  3278 Jun 25 14:47 qglpixelbuffer_p.h
-rw-r--r-- 1 root root 13609 Jun 25 14:47 qglshadercache_meego_p.h
-rw-r--r-- 1 root root  2487 Jun 25 14:47 qglshadercache_p.h
-rw-r--r-- 1 root root  2783 Jun 25 14:47 qgraphicsshadereffect_p.h
-rw-r--r-- 1 root root 11914 Jun 25 14:47 qpaintengineex_opengl2_p.h
-rw-r--r-- 1 root root  5556 Jun 25 14:47 qtextureglyphcache_gl_p.h

/usr/include/x86_64-linux-gnu/qt5/QtOpenGL/5.5.1:
total 4
drwxr-xr-x 3 root root 4096 Feb  1  2018 QtOpenGL

/usr/include/x86_64-linux-gnu/qt5/QtOpenGL/5.5.1/QtOpenGL:
total 4
drwxr-xr-x 2 root root 4096 Jun  8 10:44 private

/usr/include/x86_64-linux-gnu/qt5/QtOpenGL/5.5.1/QtOpenGL/private:
total 136
-rw-r--r-- 1 root root  4753 Oct 13  2015 qgl2pexvertexarray_p.h
-rw-r--r-- 1 root root 16204 Oct 13  2015 qgl_p.h
-rw-r--r-- 1 root root  2487 Oct 13  2015 qglcustomshaderstage_p.h
-rw-r--r-- 1 root root 19610 Oct 13  2015 qglengineshadermanager_p.h
-rw-r--r-- 1 root root 20751 Oct 13  2015 qglengineshadersource_p.h
-rw-r--r-- 1 root root  5250 Oct 13  2015 qglframebufferobject_p.h
-rw-r--r-- 1 root root  3312 Oct 13  2015 qglgradientcache_p.h
-rw-r--r-- 1 root root  3323 Oct 13  2015 qglpaintdevice_p.h
-rw-r--r-- 1 root root  3278 Oct 13  2015 qglpixelbuffer_p.h
-rw-r--r-- 1 root root 13609 Oct 13  2015 qglshadercache_meego_p.h
-rw-r--r-- 1 root root  2487 Oct 13  2015 qglshadercache_p.h
-rw-r--r-- 1 root root  2783 Oct 13  2015 qgraphicsshadereffect_p.h
-rw-r--r-- 1 root root 11914 Oct 13  2015 qpaintengineex_opengl2_p.h
-rw-r--r-- 1 root root  5556 Oct 13  2015 qtextureglyphcache_gl_p.h
$
Didn't make any difference. Happy to try other arrangements...
-------------------------------------------------------
Hope this can be re-opened?

**Comment by leozide** [comment]
I don't know how to help you, looks like something wrong with your system. This is what I have:
```

leo@leo-vb:/usr/include/x86_64-linux-gnu/qt5/QtOpenGL$ ls -l 
total 180
-rw-r--r-- 1 root root    17 Mar  5 23:59 QGL
-rw-r--r-- 1 root root    23 Mar  5 23:59 QGLBuffer
-rw-r--r-- 1 root root  4034 Mar  5 23:59 qglbuffer.h
-rw-r--r-- 1 root root    25 Mar  5 23:59 QGLColormap
-rw-r--r-- 1 root root  3267 Mar  5 23:59 qglcolormap.h
-rw-r--r-- 1 root root    17 Mar  5 23:59 QGLContext
-rw-r--r-- 1 root root    17 Mar  5 23:59 QGLFormat
-rw-r--r-- 1 root root    34 Mar  5 23:59 QGLFramebufferObject
-rw-r--r-- 1 root root    34 Mar  5 23:59 QGLFramebufferObjectFormat
-rw-r--r-- 1 root root  5344 Mar  5 23:59 qglframebufferobject.h
-rw-r--r-- 1 root root    26 Mar  5 23:59 QGLFunctions
-rw-r--r-- 1 root root 50439 Mar  5 23:59 qglfunctions.h
-rw-r--r-- 1 root root    26 Mar  5 23:59 QGLFunctionsPrivate
-rw-r--r-- 1 root root 17146 Mar  5 23:59 qgl.h
-rw-r--r-- 1 root root    28 Mar  5 23:59 QGLPixelBuffer
-rw-r--r-- 1 root root  3878 Mar  5 23:59 qglpixelbuffer.h
-rw-r--r-- 1 root root    30 Mar  5 23:59 QGLShader
-rw-r--r-- 1 root root    30 Mar  5 23:59 QGLShaderProgram
-rw-r--r-- 1 root root 14312 Mar  5 23:59 qglshaderprogram.h
-rw-r--r-- 1 root root    17 Mar  5 23:59 QGLWidget
-rw-r--r-- 1 root root   341 Mar 11 06:27 QtOpenGL
-rw-r--r-- 1 root root   226 Apr 11 06:29 QtOpenGLDepends
-rw-r--r-- 1 root root  2261 Mar  5 23:59 qtopenglglobal.h
-rw-r--r-- 1 root root    29 Mar 11 06:27 QtOpenGLVersion
-rw-r--r-- 1 root root   208 Mar 11 06:27 qtopenglversion.h
```
There are no subfolders, just files. What distro/version do you have?

**Comment by William-Purvis** [comment]
Mint 18.3

**Comment by William-Purvis** [comment]
Just re-installed libqt5opengl and it looks better.
make has now run to completion without errors. 
My apologies for my lack of understanding how things QT/C++ work - I still haven't converted my brain to the modern stuff, and probably never will, now!
