### ISSUE TITLE
POV-Ray export issues

### ISSUE THREAD

**Issue by mjhorvath** [leozide/leocad#364]
A couple of POV-Ray issues:

1. The program does not recognize these colors properly:

lc_Color_353
lc_Color_507
lc_Color_508
lc_Color_509

2. It also does not recognize the following colors, but no other program seems to recognize them either:

lc_Color_10002
lc_Color_10026
lc_Color_10031
lc_Color_10070
lc_Color_10226
lc_Color_10308
lc_Color_10320
lc_Color_10321
lc_Color_10322
lc_Color_10323
lc_Color_10484

3. Pigments should use "srgb" instead of "rgb".

**Comment by leozide** [comment]
What do you mean by doesn't recognize?

What os and version of pov-ray are you using?

**Comment by leozide** [comment]
Also, those look like unofficial colors. If you want to use them you have to provide your own ldconfig.ldr with the new colors.

**Comment by mjhorvath** [comment]
Sorry, I just realized those colors are new in the latest 2019-01 release of "ldconfig.ldr". However, there is an issue with the "complete.zip" archive. I will return later with a working download link.

**Comment by mjhorvath** [comment]
The "official" colors are as you say. I had an unofficial copy of "ldconfig.ldr" apparently.
