### ISSUE TITLE
Model won't load/render

### ISSUE THREAD

**Issue by mjhorvath** [leozide/leocad#365]
I am unable to load this model:

https://github.com/mjhorvath/Mike-LDraw-Models/blob/master/regular/ldr_carriage_house_new.mpd

The screen is blank, even when cycling through submodels.

**Comment by mjhorvath** [comment]
Continuous Build cd3a03e

**Comment by mjhorvath** [comment]
I forgot to set the parts library, sorry.

**Comment by mjhorvath** [comment]
Sorry I should not have closed this.

**Comment by mjhorvath** [comment]
All my other models load fine. The problem is only with this one.

**Comment by mjhorvath** [comment]
Does the program have a cache I can clear?

**Comment by leozide** [comment]
I've seen something similar to this happen when there was a bug parsing a part and the camera couldn't fit the model.

Are you able to load the model with the official parts library?

**Comment by leozide** [comment]
There's a cache in %USERPROFILE%\appdata\local\leocad software, try renaming the folder to something else. Please don't delete in case that fixes your problem, I'll want to take a look at the files.

**Comment by mjhorvath** [comment]
I cleared the cache and the file still won't render. I copied the old cache to a different location and still have those files if you need them.

**Comment by leozide** [comment]
Are you able to load the model with the official parts library? Which library are you using?

**Comment by mjhorvath** [comment]
I don't understand what you mean. Is there more than one library?

**Comment by leozide** [comment]
I mean, can you load the model using the library downloaded from either here or ldraw.org without adding/removing any parts?

I suspect you may have a part that isn't parsed correctly by LeoCAD.

**Comment by knightknight** [comment]
No problems loading the .mpd file with Continous Build cd3a03e.

[![2d5-RSriovb.png](https://i.postimg.cc/43tKfPL9/2d5-RSriovb.png)](https://postimg.cc/Tyd2QVXd)

I re-saved the file out as ldr: [https://ufile.io/wx26fd54](https://ufile.io/wx26fd54)

**Comment by mjhorvath** [comment]
If I move the model to a different folder on my hard drive, I am able to load it.

If I leave the model where it is but rename it to something different, I am also able to load the model.

**Comment by leozide** [comment]
Can you try this:
- run regedit
- go to HKEY_CURRENT_USER\Software\LeoCAD Software\LeoCAD\TabLayouts
- find the path to the model that doesn't load in the list
- save the value
- delete the key for your model

If this fixes it then please send me the saved value.

**Comment by mjhorvath** [comment]
That worked, thanks! I have attached the file.

[carriage_house.zip](https://github.com/leozide/leocad/files/3388454/carriage_house.zip)

**Comment by leozide** [comment]
For some reason the view settings were saved incorrectly when you previously closed the model. I've added some checks when loading the views to avoid this happening again.
