### ISSUE TITLE
Unable to render the notebook

### ISSUE THREAD

**Issue by swatiluthra** [leozide/leocad#367]
I am unable to render the uploaded python file,,

https://github.com/swatiluthra/Capstone/blob/master/Capstone-Week1.pynb

Please help

**Comment by swatiluthra** [comment]
I am unable to render the uploaded python file,,

https://github.com/swatiluthra/Capstone/blob/master/Capstone-Week1.pynb

Please help

**Comment by leozide** [comment]
I have no idea what that file is.

**Comment by swatiluthra** [comment]
It is a juptyer notebook, uploaded to Github.

**Comment by leozide** [comment]
And how do I get an ldr file out of it?
