### ISSUE TITLE
Insert step moves previous parts to new step

### ISSUE THREAD

**Issue by knightknight** [leozide/leocad#373]
LeoCAD Version 19.07.1
Windows 10.0.17763 Build 17763

`Insert step` moves previous steps parts to the new step rather than retaining the original step.

Example: 

Add new part, automatically assigns to step 1
[![Leo-CAD-90-X4n18-Uq-S.png](https://i.postimg.cc/28WbNK9r/Leo-CAD-90-X4n18-Uq-S.png)](https://postimg.cc/D82yqBKM)

Insert Step, part from step 1 then moves to step2.
[![Leo-CAD-Wwr-B8-RQtfe.png](https://i.postimg.cc/Z5FWCyhQ/Leo-CAD-Wwr-B8-RQtfe.png)](https://postimg.cc/mPkLnkk3)

**Comment by leozide** [comment]
This is how it's supposed to work, you don't need to insert a step at the end since you can just move to the next step and a new one will be created automatically.

I can see how this can be confusing so I'll rename things to make it more clear.

**Comment by knightknight** [comment]
@leozide, I've never used nor did I know what the blue arrow where! I assumed they where part of whatever the `Add Keys` does. So I've just tried the arrow icons and `Alt + Right` and it does exactly as you say... So the confusing part is right clicking in the Timeline panel and using `Insert Step` which you would assume would be the same as `Alt + Right`.

**Comment by leozide** [comment]
Keeping this open to remind me
