### ISSUE TITLE
Parts library for 19.07.x?

### ISSUE THREAD

**Issue by jorgicio** [leozide/leocad#374]
Hi!

I noted every version of LeoCAD has its own parts library. However, the most recent ones doesn't have to.
Is it not needed anymore or it may be installed separately? Latest one came with 18.02.

Thanks!

**Comment by leozide** [comment]
It's included in all 3 release packages now.

**Comment by jorgicio** [comment]
Thanks, however, I forgot to mention that I built LeoCAD from sources. May I have to use another parts library?

I maintain the package for Gentoo.

**Comment by leozide** [comment]
You can use the LDraw library if there's a package for it already, or download https://github.com/leozide/leocad/releases/download/v18.02/Library-Linux-11494.zip.

**Comment by jorgicio** [comment]
I'll try the LDraw then. Meanwhile, I had to use the 11494 library, which works fine.

Thanks.
