### ISSUE TITLE
Hide parts that begin with "="

### ISSUE THREAD

**Issue by techdude1996** [leozide/leocad#378]
It gets slightly annoying having to scroll past all of the parts that start with an equal sign "=" when I never use any of those parts. An option either in settings or the right-click menu to hide these like decorated parts would be nice.
![image](https://user-images.githubusercontent.com/25308291/62092688-1d439780-b244-11e9-99b3-b5690bea6ab8.png)
(For those wondering, I'm on Manjaro Linux with KDE Plasma.)

**Comment by techdude1996** [comment]
Any reason why this was closed?

**Comment by techdude1996** [comment]
Thanks

**Comment by leozide** [comment]
This was added in e523398 as the message shows.
