### ISSUE TITLE
Problem creating a camera in orthographic projection

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#379]
Creating a camera in orthographic projection appears to be broken. It looks like the GetProjectionMatrix() call at
`lcUnprojectPoints(Points, NumPoints, mCamera->mWorldView, GetProjectionMatrix(), Viewport);` in [view.h](https://github.com/leozide/leocad/blob/e523398c70f685e1c85af3608b31806ed123cab9/common/view.h#L152) is failing to properly initialize because the position and target coordinates are enormous.
![Screenshot - 08_08_2019 , 00_41_35](https://user-images.githubusercontent.com/13388970/62662858-b9248000-b975-11e9-833a-612420e6157f.png)

And the model disappears when the created camera is set. Then the camera disappears on attempt to rotate it.
![Screenshot - 08_08_2019 , 00_42_28](https://user-images.githubusercontent.com/13388970/62662859-b9248000-b975-11e9-9b7e-a83da3ff0f61.png)

Cheers,

**Comment by leozide** [comment]
I've added something to try to place the new camera near the model, let me know if you have any cases where this doesn't work well.

**Comment by trevorsandy** [comment]
Works well - Many thanks!

However, it seems like the "IsOrtho" attribute is not being set:

![Screenshot - 11_08_2019 , 00_17_23](https://user-images.githubusercontent.com/13388970/62827372-4bbf5c00-bbce-11e9-9fcc-80af0ac574ed.png)

Cheers,

**Comment by leozide** [comment]
The menu is wrong, the picture shows a perspective projection. I think I fixed the case where this was happening.

**Comment by trevorsandy** [comment]
After a few tries, I figured out the reason. If you set and select the camera before setting the projection to Ortho, you'll get the correct view shown below. If you set the projection to Ortho before setting and selecting the camera, you get the view shown above.

![Screenshot - 11_08_2019 , 05_25_31](https://user-images.githubusercontent.com/13388970/62829345-93a8a800-bbfb-11e9-8fbc-9d2939ef5907.png)
