### ISSUE TITLE
"ldrawloader"

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#381]
Would be it usefull implement `ldrawloader` into *LeoCAD*? @pixeljetstream

- https://github.com/pixeljetstream/ldrawloader
- https://forums.ldraw.org/thread-23623.html

![pic.1](https://raw.githubusercontent.com/pixeljetstream/ldrawloader/master/doc/ldrawloader.png)

![pic.2](https://raw.githubusercontent.com/pixeljetstream/ldrawloader/master/doc/ldrawloader2.png)

As for me, "Chamfered" representation of pins and rounded edges looks better than current LeoCAD implementation.

**Comment by pixeljetstream** [comment]
Don't think it's feature complete/compatible enough to be used in a major tool, that's also not directly my intent for that codebase.

**Comment by j6t** [comment]
Is this still relevant?
