### ISSUE TITLE
ARM64 build not functioning

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#383]
I am setting up my new linux environemt to run on my Samsung Galaxy S10+ - I was able to successfully build the latest LeoCAD from git source

when attempting to run, CLI returns:

QNativeImage: Unable to attach to shared memory segment.
Bad system call.

Can this be fixed?

Thanks

**Comment by leozide** [comment]
A stack trace would help, but I think this is between Qt and Dex.

**Comment by nathaneltitane** [comment]
@leo how could I help to fix this issue?

**Comment by leozide** [comment]
I posted above, run from gdb and see if you can get a call stack. Is there a way I can run this on a VM?

**Comment by nathaneltitane** [comment]
There is an image provided by Samsung, maybe you can have it run on VM and see?

WebView.linuxondex.com

**Comment by nathaneltitane** [comment]
Sent a bug report to the LoD/Dex dev team - seems this issue is common to all Qt dependant apps/builds

**Comment by nathaneltitane** [comment]
here is the trace from gdb -q leocad using the repository version of leocad on ubuntu 16.04 lts arm from the lod system:

(gdb) run
Starting program: /usr/bin/leocad 
warning: Unable to determine the number of hardware watchpoints available.
warning: Unable to determine the number of hardware breakpoints available.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
QNativeImage: Unable to attach to shared memory segment. 

Program terminated with signal SIGSYS, Bad system call.
The program no longer exists.

**Comment by nathaneltitane** [comment]
@leozide 

seems this issue is known when qt apps operate under container/virtual systems.
i was able to make leocad function using QT_X11_NO_MITSHM=1 and QT_GRAPHICSSYSTEM=native

problem solved i guess :)

**Comment by nathaneltitane** [comment]
Seems the workaround mentioned above only works with the build currently in the ubuntu repos for 16.04 - when building from source under arm64, the issue still occurs
