### ISSUE TITLE
Trans-light blue exporting wrong bricklink code

### ISSUE THREAD

**Issue by AdvancedStyle** [leozide/leocad#392]
Trans-Light Blue is being exported as "113" color code when exporting to bricklink file, instead of color "15" which is it should be: https://www.bricklink.com/catalogColors.asp

**Comment by AdvancedStyle** [comment]
Note i've created a pull request fixing this: https://github.com/leozide/leocad/pull/393

**Comment by leozide** [comment]
I've updated the entire table with the latest data from BL, that includes your changes plus a few more fixes.
