### ISSUE TITLE
part category menu drop down disappeared

### ISSUE THREAD

**Issue by disloyalpick** [leozide/leocad#397]
i was building something using technic parts and it wont let me change the part category. the drop down for category selection disappeared and i cant use technic parts. 

is there possibly a way to fix this that i might be missing? i just want the menu back lol
![xs9pOze 1](https://user-images.githubusercontent.com/13305403/66711650-c6872d80-ed5d-11e9-9001-817f85f10d34.png)

**Comment by leozide** [comment]
You probably resized it too small, move the mouse over the left side of the toolbar and you should see the cursor change, then you should be able to drag and resize it.
