### ISSUE TITLE
Can't search by brick number

### ISSUE THREAD

**Issue by QuantumAnomaly** [leozide/leocad#401]
Sorry, this isn't a bug sort of issue. More of a usability thing.

I just installed LeoCAD and the first obstacle I've hit is that there appears to be no way to search by brick number, or even view brick numbers of selected bricks.

If you already have the brick numbers for something you want to put together (example: https://www.brickowl.com/catalog/lego-unikitty-minifigure/inventory )
you can't just type in those numbers. You've got to scroll though the various categories and hope to find the pieces you're looking for. This is very time consuming.

(Also, it would be nice if one could "favorite" frequently used bricks, but that's another matter.)

I realize this isn't a place for feature requests, but if people can't find bricks by number that could present a significant barrier for some.

**Comment by leozide** [comment]
Searching for numbers works for me:

![image](https://user-images.githubusercontent.com/9685066/70377534-624e9900-18ca-11ea-8e53-bc72f033e57b.png)

What are you trying to search?

This is the correct place for feature requests.

**Comment by Symbian9** [comment]
> Searching by part numbers works for me

I also though about it.

Maybe, it would be useful add some special options/query argument `p:<number>` for such by number only.

**Comment by QuantumAnomaly** [comment]
Thanks for the reply, leozide! That's really good to know. It turns out I just got unlucky with the first few parts I tried searching. Examples: 15856, 34078, 28626... but it turns out those last two have alternate numbers that _do_ show up: 89522, 85861. I also just learned from [this page](https://www.lego.com/en-us/service/help/bricks-building/replacement-parts/identifying-lego-set-and-part-numbers-408100000009668) that there are both element numbers and design numbers, so this could be the reason for multiple numbers being listed for a part.

**Comment by nathaneltitane** [comment]
@QuantumAnomaly some parts return odd results due to how the ldraw library is made and how cross references are made in the part files themselves - i found myself in a bit of a situation where i had to manually override and change part number entries in my library for bricklink to recognize the right items to purchase...

the search field does seem to work as expected but could also use a bit of love @leozide  :)

**Comment by leozide** [comment]
what sort of improvements do you want to see with the search?

**Comment by nathaneltitane** [comment]
Well, in addition to finding specific results through input, wouls be nice to have a popup onr some means of rotating the part in the preview to see its features before plugging it into a model, makes for less of a headache given the many parts variants that exist. would go well together i think and it's totally up to you to agree to it or not :)

**Comment by nathaneltitane** [comment]
@leozide I was also thinking that the 'search parts' input box could be it's own widget:

it could benefit from being positioned at the top or bottom of the Leocad main window and benfit from the full span/width of the window itself (search input would not be truncated) and you could add buttons to toggle certainsearch criteria as well.

It could look something like this:

[ Search Parts                                                        ][   ] [   ] [   ] [   ] [   ] [   ]

**Comment by j6t** [comment]
The original topic of this issue has been resolved. If the search box is of importance to you, @nathaneltitane , please file a new issue. This one can be closed, IMO.

**Comment by Symbian9** [comment]
> The original topic of this issue has been resolved

@j6t, could you show where it was solved?

**Comment by leozide** [comment]
The original issue was never a bug, you could always search by number.

**Comment by trevorsandy** [comment]
> what sort of improvements do you want to see with the search?

It could be useful to add the Bricklink and LEGO part numbers - perhaps as additional categories. A cross referenced file with these numbers can be downloaded as ‘codes.txt’ directly from Bricklink. I use them for my element annotations and you already use a resourced equivalent list for your Bricklink export.

Cheers,

**Comment by nathaneltitane** [comment]
> > what sort of improvements do you want to see with the search?
> 
> It could be useful to add the Bricklink and LEGO part numbers - perhaps as additional categories. A cross referenced file with these numbers can be downloaded as ‘codes.txt’ directly from Bricklink. I use them for my element annotations and you already use a resourced equivalent list for your Bricklink export.
> 
> Cheers,

URL?

**Comment by j6t** [comment]
So, this can be closed? The Bricklink part number redirection is a different issue.

**Comment by Symbian9** [comment]
> The original issue was never a bug, you could always search by number.

@leozide, how to limit search only to number ID? (by ignoring any parts with number in its NAME field)

**Comment by leozide** [comment]
You can't, but can you give me an example of when this is a problem? Typing 3 numbers should be enough to avoid all name matches.
