### ISSUE TITLE
Black Model Screen

### ISSUE THREAD

**Issue by The-S-Dev** [leozide/leocad#406]
![Capture](https://user-images.githubusercontent.com/58951506/70929359-e3283600-202a-11ea-96f0-99cd4f8e64e2.PNG)
Hi im am new to leoCad but i when i load up the program i am greeted with a black model screen, there might be somthing simple to fix this but currently i am not sure how

thanks for any help

**Comment by leozide** [comment]
Can you copy and paste the contents of the Help->About Dialog please?

**Comment by thebrickbot19** [comment]
Qt Version 5.11.3 (compiled with 5.11.3)

OpenGL Version  (GLSL )
 - 

Color Buffer: 32 bits RGBA double buffered
Depth Buffer: 24 bits
Stencil Buffer: 8 bits

GL_ARB_vertex_buffer_object extension: Not supported
GL_ARB_framebuffer_object extension: Not supported
GL_EXT_framebuffer_object extension: Not supported
GL_EXT_blend_func_separate: Not supported
GL_EXT_texture_filter_anisotropic extension: Not supported

**Comment by Movies25** [comment]
I have this same issue and am waiting to hear how to address.

**Comment by leozide** [comment]
It looks like your computer doesn't support OpenGL. Do you know what video card you have? Have you tried updating your video card drivers?
