### ISSUE TITLE
Insert steps goes backwards

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#408]
Inserting a new step in a build does not behave as expected:

when inserting a step, one would like the insertion to move forward (or downwards in the timeline) as one builds a model.

Currently, insertion generates a step in reverese order (see attached) - adding a step *after* the current step should not result in having a step frame be put before the current step, but after it.

Also, steps should be treated as parts where any normal delete key input should enable removal rather than having to right click context to remove step

![image](https://user-images.githubusercontent.com/5674757/71546914-e0054200-2968-11ea-8160-2c9db50e64b6.png)

![image](https://user-images.githubusercontent.com/5674757/71547239-76d2fe00-296b-11ea-8092-e1c8e5ea50f9.png)

![image](https://user-images.githubusercontent.com/5674757/71547244-7fc3cf80-296b-11ea-9ea4-16097a55a7a5.png)

**Comment by nathaneltitane** [comment]
#408 - possible duplicate?

**Comment by leozide** [comment]
The idea is that you don't need to insert a step after the last one, there should always be an empty step at the end but there was a bug and it wasn't working. My last commit should have fixed that so please give it a try and let me know if you still feel like you need to use the insert step option.

Insert should really be used for inserting a step before the current one but that's confusing, I could rename it to "insert before" and add "insert after".

**Comment by Symbian9** [comment]
Also there is issue with "Time" tollbar: its still possible add & remove new keys using "Previous" and "Next" buttons while "Add Keys" button is NOT activated!

**Comment by Symbian9** [comment]
> `#408` - possible duplicate?

@nathaneltitane You just self linked this thread.

**Comment by nathaneltitane** [comment]
> > `#408` - possible duplicate?
> 
> @nathaneltitane You just self linked this thread.

went too fast, meant to link 373 - fixed.

**Comment by leozide** [comment]
Is this still an issue after my previous reply?

**Comment by nathaneltitane** [comment]
Have not tested due to crashes on latest build, witll build your new commit and let you know - thanks

**Comment by Symbian9** [comment]
> Is this still an issue after my previous reply?

Okay, there is another issue: LeoCAD should not add new step if previous step is empty.

![img.1](https://i.imgur.com/UaoX5Dz.png)

**Comment by leozide** [comment]
Those steps are only visible because you went to step 18, if you go back they will disappear.

**Comment by Symbian9** [comment]
> Those steps are only visible because you went to step 18, if you go back they will disappear.

I mean that its issue - LeoCAD should not create more than on empty step.

On "Time" toolbar "Next" button should be inactive if actual step is empty. LeoCAD also should ignore shortcut for adding new steps in this situation.

![pic.1](https://i.imgur.com/r0B6Wje.png)

Also, in this situation menu entries *"View > Step > Next"* and *"View > Step > Insert Step"* should be inactive.

![pic.2](https://i.imgur.com/7eBvadu.png)

Additionally, if actual 'empty step' is '1st step on timeline' — *"View > Step > Remove Step"* should be inactive too.

**Comment by leozide** [comment]
I don't see any harm in allowing the user to create empty steps. It's pretty common to see that in official instructions where some steps just show the model from a different angle or tell you to move parts.

**Comment by Symbian9** [comment]
> It's pretty common to see that in official instructions where some steps just show the model from a different angle or tell you to move parts.

Can you explain your vision on how it could be used for instruction in LeoCAD with just adding two and more *empty steps* in a row?

I expect that additional views for steps from different angle should be use inserted additional camera objects.

> tell you to move parts.

Also, if in new step no new parts added, we anyway should add something to each step to represent movements on *"Timilene"*. (I already has an idea for solution, but should add more details tomorrow)

**Comment by leozide** [comment]
Here's an example where you end up having an empty step:

0 !LEOCAD MODEL BACKGROUND COLOR 0.8 0.8 0.8
1 4 0 -24 0 1 0 0 0 1 0 0 0 1 3005.dat
0 !LEOCAD PIECE POSITION_KEY 1 0 0 72 
0 !LEOCAD PIECE POSITION_KEY 2 0 0 48 
1 4 0 -48 0 1 0 0 0 1 0 0 0 1 3005.dat
0 STEP
0 STEP
1 4 0 -72 0 1 0 0 0 1 0 0 0 1 3005.dat

Plenty of editors show keyframes, but I haven't seen anything that works well for instructions:

https://knowledge.autodesk.com/support/motionbuilder/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/MotionBuilder/files/GUID-120DEC2F-7AE6-4577-966C-E3FFAA393366-htm.html

**Comment by Symbian9** [comment]
> Here's an example where you end up having an empty step:

No, I mean I understand such LDR-file will look internally.

But I'm talking on representation of movements on "Timeline" widget (in LeoCAD GUI)

I propose add actions icons per each step:

- ➕ (added part on this step)
- ➖  (removed part on this step
- ➚ (moved part on this step)
- ⭮ (rotated part on this step)
- ...

![pic.1](https://i.imgur.com/SjJHpX0.png)

**Comment by nathaneltitane** [comment]
I must agree with @Symbian9  here, @leozide i would expect the inserted step to make it'S way after the selected or current step and not before, regardless of the presence of an automatic last step.

I've been working on a new model and the behavior is quite unnatural

**Comment by Symbian9** [comment]
> regardless of the presence of an automatic last step.

Yeah, this is fully unnatural.

Additionally, as LeoCAD now has option to fade previous step, moved part should not be faded in actual step.

### Previous step

![pic.1](https://i.imgur.com/gNhxgcc.png)

### Actual step

![pic.2](https://i.imgur.com/QhDHTNt.png)

Also if select moved part it shown as part from previous step, BUT in actual step it moved so it could not be "part from previous step" as location already different in actual step

![pic.3](https://i.imgur.com/VgNCQ5I.png)

Any movements should be represented in each step on *"Timeline"*.
