### ISSUE TITLE
steps with submodel does not parse on print

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#409]
Having an mpd with submodel(s) containing steps does not result in the document being printed and reflecting the subassembly steps being shown to instruct how to build. please see attached.

0 FILE New Model.ldr
0 !LEOCAD MODEL AUTHOR Nathanel Titane - nathanel.titane@gmail.com
1 4 0 0 0 1 0 0 0 1 0 0 0 1 3005.dat
0 STEP
1 4 0 -24 0 1 0 0 0 1 0 0 0 1 4588.dat
1 4 40 48 -30 1 0 0 0 1 0 0 0 1 test.ldr
0 NOFILE
0 FILE test.ldr
0 !LEOCAD MODEL AUTHOR Nathanel Titane - nathanel.titane@gmail.com
1 3 -40 -24 30 1 0 0 0 1 0 0 0 1 3062b.dat
0 STEP
1 3 40 -24 10 1 0 0 0 1 0 0 0 1 3062b.dat
0 NOFILE

[test.pdf](https://github.com/leozide/leocad/files/4007249/test.pdf)

**Comment by nathaneltitane** [comment]
@leozide still buggy on the output, it does give the elaboration of submodels, but pov/forcus on parts is still elusive. see attached

0 FILE New Model.ldr
0 !LEOCAD MODEL AUTHOR Nathanel Titane - nathanel.titane@gmail.com - All rights reserved
1 3 -150 -24 -30 1 0 0 0 1 0 0 0 1 3005.dat
0 STEP
1 3 50 -24 -110 1 0 0 0 1 0 0 0 1 3062a.dat
0 STEP
1 4 10 0 0 1 0 0 0 1 0 0 0 1 Submodel #1.ldr
0 NOFILE
0 FILE Submodel #1.ldr
0 !LEOCAD MODEL AUTHOR Nathanel Titane - nathanel.titane@gmail.com - All rights reserved
1 4 100 -24 -140 1 0 0 0 1 0 0 0 1 3005pt0.dat
0 STEP
1 4 10 -24 -20 1 0 0 0 1 0 0 0 1 3005pe2.dat
0 NOFILE



[print.pdf](https://github.com/leozide/leocad/files/4011894/print.pdf)

**Comment by leozide** [comment]
I fixed the font size yesterday, try getting latest.
