### ISSUE TITLE
Always focus on actual step in "Timeline" widget

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#410]
### Actual behavior

Actual step NOT highlighted in "Timeline" widget if switching between steps using "Previous"/"Next" buttons on "Time" toolbar or using shortcuts

![img.1](https://i.imgur.com/WCPB3PI.png)

### Expected behavior

Switching between steps using "Previous"/"Next" buttons on "Time" toolbar or using shortcuts should be described on "Timeline" widget by highlighting actual step

- **Video** - https://transfer.sh/get/mERHY/loading-ldr-s.mp4 *(link will expire in 14 days)*

**Comment by leozide** [comment]
The timeline selection reflects the part selection in the view, so selecting the current step in the timeline would clear the part selection every time you go to another step.

**Comment by Symbian9** [comment]
> The timeline selection reflects the part selection in the view

So, actual step should be highlighted *always* when there no any selected parts.

**Comment by leozide** [comment]
I've made the current step bold, which I think is a better solution.

**Comment by nathaneltitane** [comment]
@leozide behavior still very ambiguous as visual confirmation of what'S going on is usually sought in the model space - maybe using the in context model edit shading would work well in tandem with bolding the step?
