### ISSUE TITLE
Enhancement : find feature upgrade

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#414]
Hi leo,

I've been looking into the current features offered by leocad.

The Search/Find dialog could benefit from an additional replace / replace all / replace all (in all (sub)model(s)) when looking for a part or color or part w/ color combination , making the search more beneficial and proactive in modifying or updating models as a whole, rather than just find items and modify them manually afterwards.

cases:

1 - find part
2 - find color
3 - find part w/color

a- replace in current model (as toggle)
b - replace in all models (as toggle)

Thank you

**Comment by nathaneltitane** [comment]
@leozide what do you think?

**Comment by leozide** [comment]
I've added a replace feature
