### ISSUE TITLE
Additional instruction output formats

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#415]
Could there be an addition to the current output when printing a model, for instruction creation that could output pages in image format? PNG, JPG, etc?

**Comment by Symbian9** [comment]
> PNG, JPG, etc?

And PDF

**Comment by nathaneltitane** [comment]
> > PNG, JPG, etc?
> 
> And PDF

It already does pdf. Keyword: printing

**Comment by leozide** [comment]
How is this different from saving images?

**Comment by Symbian9** [comment]
With "Printing to File (PDF)" its impossible setup DPI for raster images bundled into resulted PDF.

**Comment by nathaneltitane** [comment]
@leozide, i had completely dismissed the fact that the dialog for the 'save as image included the steps and subassemblies options - my bad.
