### ISSUE TITLE
duplicating parts duplicates control handle position when part is changed

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#418]
setting a custom position for a part handle and then duplicating it causes an issue when the duplicated part is then modified for another throught the properties panel.

expected behavior: if duplicated part A is modified into part B, reset custom control point to part defaults OR add feature to manually reset control point to default with additional keyboard shortcut to command

thank you

![image](https://user-images.githubusercontent.com/5674757/71753521-d2602880-2e50-11ea-8274-ba8fd0717c09.png)

![image](https://user-images.githubusercontent.com/5674757/71753661-3aaf0a00-2e51-11ea-94fd-a4a4291a0201.png)

**Comment by leozide** [comment]
I don't understand the issue, when you duplicate a part I think the rotation center should be duplicated as well.

To reset the rotation center you can use Piece -> Reset Pivot Point, you can assign a shortcut for it already.

**Comment by nathaneltitane** [comment]
Alrighty. Thanks
