### ISSUE TITLE
ISSUE: previous step fade while editing

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#420]
While editing a model, it can be difficult to discern parts unless the actual step is selected.

Maybe the previous step fade should be enabled only at the instructions level and/or a toggle + shortcut should be added to enable or disable it while editing a model for adequate preview.

Thank you

**Comment by rsbx** [comment]
This is another request for a previous step fade button and (settable) keyboard shortcut.

I would expect it to default to the saved preferences setting and the button/shortcut would toggle the display but not change the saved preference.

**Comment by rsbx** [comment]
That was fast!

No toolbar button :-( but a keyboard shortcut is confirmed is to work.
