### ISSUE TITLE
ENHANCEMENT: Search parts input box - clear on click

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#421]
Could the 'Search Parts' input box that resides in th eparts panel be upgraded with a 'click to clear' feature to facilitate quick search input?

**Comment by leozide** [comment]
It's the red X on the right:

![image](https://user-images.githubusercontent.com/9685066/71786458-508f0d00-2fc0-11ea-9a25-382e5722291a.png)

**Comment by nathaneltitane** [comment]
none here on linux based builds... also, icons on buttons are off scale all over the place

![image](https://user-images.githubusercontent.com/5674757/71786549-76c1a680-2fda-11ea-8c79-927da74368a7.png)

**Comment by leozide** [comment]
It works on Linux, you need Qt 5.2 or later to see it.
