### ISSUE TITLE
Parts "Visibility > Hide" property is unclear

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#423]
Actually parts *"Visibility > Hide"* property on *"Properties"* widget is unclear

> - **Visibility**
>   - Show: `1`
>   - Hide: `4294967295`

What does *Hide:* `4294967295` variable mean? How user should use it?

Also how *Show:* `1` property work? Changing to *Show:* `0` has no any (visual) effects too.

![pic.1](https://i.imgur.com/0XfAoCx.png)

**Comment by nathaneltitane** [comment]
[HIDE] 0 / 1     /    'no' / 'yes'

**Comment by Symbian9** [comment]
> [HIDE] 0 / 1 / 'no' / 'yes'

Changing it to 1 hide part, but immediately this value swithced to `2` and later it fully ignore changing to `0` or `1`

Also, on "Timetable" seems LeoCAD not show it as hidden part

![pic.1](https://i.imgur.com/0k5BpIM.png)

![pic.2](https://i.imgur.com/OdHPSgk.png)

**Comment by leozide** [comment]
This isn't an on/off switch, it's the step where a part appears and when it disappears later.
