### ISSUE TITLE
BUG: parts order inverted on step modification

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#424]
Parts in step with order A,B,... get inverted when dragged or moved into another step to ...,B,A.

Please fix to keep same order.

See attached 

Thanks

![image](https://user-images.githubusercontent.com/5674757/71787510-bbebd580-2fe6-11ea-9bf2-9334ed434d32.png)

![image](https://user-images.githubusercontent.com/5674757/71787514-c8702e00-2fe6-11ea-9a4c-9f1c60b10a29.png)

**Comment by leozide** [comment]
Looks like https://bugreports.qt.io/browse/QTBUG-45320, try upgrading your Qt libs.

**Comment by nathaneltitane** [comment]
i currently build using qt4 on the latest ubuntu version available - you mean to say that when you build under qt5 there is no such problem?

**Comment by leozide** [comment]
Actually this isn't fixed, it's a Qt bug but I can probably work around it.

**Comment by nathaneltitane** [comment]
Sorry @leozide 

Just built the latest commit and i can say it still happens.

To be specific, when selecting parts, this happens when you dropped them *ONTO* the step label, but not when they are put into the step when a part is already present, before or after it.

**Comment by leozide** [comment]
You may still need to update Qt, I can't repro after my fix.

**Comment by nathaneltitane** [comment]
Which version are you on?
Did you account for the fact that leocad can be built under 4.8+ ?

**Comment by leozide** [comment]
It works correctly on 5.12 and it doesn't on 4.8.

**Comment by nathaneltitane** [comment]
will upgrade then - thank you for the workaround
