### ISSUE TITLE
FEATURE REQUEST: Rotate all selected parts according to their relative axis.

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#430]
Hi Leo,

I have a strange case scenario that prompts for an intriguing feature request:

I have been using an old version of piece 54200.dat for as long as i can remember, the parts Z axis has since been rotate by 90 deg., resulting in my most recent parts update showing all the 54200 parts in all my models being rotated that way.

I was wondering if there was any way to introduce a rotation feature that would enable the rotation on X, Y or Z of parts that are selected either individually or by filtering (using same part, same color, etc) in their respective positions in a model, but using the parts control point.

This would make the process of updating, changing or editing orientation of parts very easy and much more effective.

Currently, when doing multiple selections, only the last item selected shows its control point, resulting in the transformation going along that control point only.

![image](https://user-images.githubusercontent.com/5674757/71916637-63cee380-314c-11ea-87d6-2e6c47a2d293.png)

![image](https://user-images.githubusercontent.com/5674757/71916742-9f69ad80-314c-11ea-902d-a46b2a8f915d.png)

The feature would enable all the control points, on all the selected parts, and permit the rotation of all of them at the same time, resulting in the preview below, but in a single step rather than 3 individual ones.

![image](https://user-images.githubusercontent.com/5674757/71916768-ab556f80-314c-11ea-8838-3bb901819f1c.png)

Thank you

**Comment by nathaneltitane** [comment]
@leozide @Symbian9  thoughts?

**Comment by Symbian9** [comment]
> thoughts?

Feature itself would be useful, but there are few ways to realize it. I will try give my POV soon.

**Comment by nathaneltitane** [comment]
Hey Leo, 
Doing well I hope?

Any chance you've had some time to think about this one?

**Comment by nathaneltitane** [comment]
@leozide

Maybe we could have a look at this?

**Comment by Symbian9** [comment]
As for me, there should be added some sort of *"Transform > **Relative Separately Rotation**"* on "Properties" widget (+ some shortcut)

![pic.1](https://i.imgur.com/gkjr9XF.png)

**Comment by leozide** [comment]
I'm trying to understand the use case for this, is this a one off to fix those parts?

**Comment by nathaneltitane** [comment]
@leozide 

When using already existing models as templates or when duplication parts for use troughout an assembly, it's often easy to:

1- position part
2 - duplicate said part
3 - translate/posiotn duplicate
4 - rotate simultaneously on relative axis

Step 4 relieves us from having to reselect the componante sin question individually and apply rotation to each of them

**Comment by nathaneltitane** [comment]
@leozide Should i elaborate further?

I create models on the daily and can provide many other usage cases

**Comment by Symbian9** [comment]
I just found small trick on rotating all parts which are just entries of same submodel.

- Screencast - https://twitter.com/app4soft/status/1252661541977145345

There is one issue with adding steps during "Edit Selected Model" - steps added to edited submodel only. So, it could be useful, but need investigate more into this trick way.

**Comment by nathaneltitane** [comment]
> I just found small trick on rotating all parts which are just entries of same submodel.
> 
> * Screencast - https://twitter.com/app4soft/status/1252661541977145345
> 
> There is one issue with adding steps during "Edit Selected Model" - steps added to edited submodel only. So, it could be useful, but need investigate more into this trick way.

Already aware of that, but it's bad practice to integrate parts as submodels.

**Comment by nathaneltitane** [comment]
@leozide sorry, mustve been some kind of glitch: I had to remove the assignment, assign a letter a key without modifier accept and then re-edit the combo back to modifier+key for it to work.

All good now.
