### ISSUE TITLE
Model not drawn on Wayland

### ISSUE THREAD

**Issue by zoqaeski** [leozide/leocad#432]
I suspect #406 may be related to this issue. I'm using GNOME on Wayland, and the model isn't drawn with just a black screen or a distortion where the model viewport is shown. Installing the necessary qt5-wayland libraries doesn't seem to help:
```
$ QT_QPA_PLATFORM=wayland leocad
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
```
Here's a screenshot of the result:
![Screenshot from 2020-01-11 01-37-45](https://user-images.githubusercontent.com/172912/72160787-0c15ce00-3413-11ea-97c5-92c2fa0a5212.png)

**Comment by leozide** [comment]
Can you add the contents of your About Dialog? It should show some basic OpenGL information.

**Comment by zoqaeski** [comment]
Here you go:

> Qt Version 5.14.0 (compiled with 5.14.0)
> 
> OpenGL Version 3.0 Mesa 19.3.1 (GLSL 1.30)
> Mesa DRI Intel(R) Haswell Desktop  - Intel Open Source Technology Center
> 
> Color Buffer: 24 bits RGBA double buffered
> Depth Buffer: 24 bits
> Stencil Buffer: 8 bits
> 
> GL_ARB_vertex_buffer_object extension: Supported
> GL_ARB_framebuffer_object extension: Supported
> GL_EXT_framebuffer_object extension: Supported
> GL_EXT_blend_func_separate: Supported
> GL_EXT_texture_filter_anisotropic extension: Supported (max 16)

It displayed the same information on both environments. Weirdly enough, LeoCAD works just fine under Wayland on my laptop, but not my desktop, and they display the same information in the about dialog.

**Comment by scaronni** [comment]
Same happening here with an Intel card on Fedora with Wayland. I have to start the app by forcing Xwayland:
```
XDG_SESSION_TYPE=x11 leocad
```

**Comment by leozide** [comment]
I think this is a Fedora/Qt bug:

https://bugs.launchpad.net/mixxx/+bug/1850729
https://fedoraproject.org/wiki/Changes/Qt_Wayland_By_Default_On_Gnome

Do you have that patch?

**Comment by scaronni** [comment]
Ehm... patch is here: http://pkgs.rpmfusion.org/cgit/free/mixxx.git/commit/?id=709069aaddacf11bf552ebdb364655eea166eddb

It is actually a workaround to force the application to start with X instead of Wayland, without fixing the application.

Since Fedora 31 also all QT applications run by default under Wayland, unless instructed otherwise. So far I have an issue only with LeoCad and Plex Media Player where I have specifically to run under X (Xwayland).

**Comment by scaronni** [comment]
Btw, thanks for the program, it's great!

**Comment by leozide** [comment]
Can you try disabling anti aliasing? it's in View->Preferences->Rendering.

What do I need to do to repro this? Install Fedora 31 with Wayland/Gnome?
