### ISSUE TITLE
Fixed direction Keys Not working (on Mac)

### ISSUE THREAD

**Issue by welsmore** [leozide/leocad#434]
I believe this is a bug, but I could be wrong.

Moving elements with the keyboard (left/right etc) always seems to move the element with regard to the elements' original placing. eg, if an 1x1  brick is laid onto it's side, then pressing the keyboard shortcut for 'left' will cause it to go upwards.

This happens whether 'fixed direction keys' is selected or not. I would expect it not to, if 'fixed direction keys' is enabled.

Moving from Bricksmith, this is a real pain, as Bricksmith moves parts relative to the entire model all the time - regardless of the parts' orientation.

**Comment by leozide** [comment]
I believe what you're looking for is the 'Relative Transforms' button on the toolbar:

![image](https://user-images.githubusercontent.com/9685066/72223500-4fac2d00-3524-11ea-8ef5-906e8ddf3e2e.png)

Make sure that's unchecked.

**Comment by welsmore** [comment]
I stand corrected, thankyou :-) Not a bug.
