### ISSUE TITLE
'Parts in use' filter does not differentiate submodels from actual parts

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#436]
Hi Leo,

I've stumbled upon something that may be related to a an issue previously mentioned by someone else (maybe palette or filter related):

upon finishing my model, i went into the 'Parts in use' section of the parts widget and found that the listed parts weren't 'exploded' but rather shown at a submodel level

One would hope the filer or function would iterate over all the model entries and actually list the individual parts being used in the entirety of the model, whereas the 'Submodels' entry would list the submodels within the model file.

Thanks

![Screenshot_20200113_231932](https://user-images.githubusercontent.com/5674757/72314528-4e325000-365d-11ea-9b27-11f5205f3aa5.png)

**Comment by nathaneltitane** [comment]
Just built the latest commit - @leozide I would suggest removing the display of submodels in that category as it is confusing - although I understand that submodels are in fact 'parts' to the model,o one would only expect actual individual lego pieces under that filter, since submodels category already exists

**Comment by leozide** [comment]
My intention for that category is to be able to easily find items already used in the current submodel. I agree that 'Parts in Use' is confusing since submodels aren't parts so I've renamed it to just 'In Use'.
