### ISSUE TITLE
OPTION: disable parts list color override

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#437]
When selectiing the option to add the parts list after a given step, the color overrride makes it counterintuitive to reference the appropriate part/color if setting up the instruction (as represented at the end of the document with a full BOM with actual parts colors as shown in model file)

An option/toggle would be necessaryto disable the override to keep the part color as represented within the model.

Thank you

![image](https://user-images.githubusercontent.com/5674757/72361253-283d9780-36bf-11ea-9f89-d0b2d5d75cac.png)

**Comment by leozide** [comment]
I'm going to remove this option and replace it with a single image like the BOM.

**Comment by nathaneltitane** [comment]
Excellent!

Thanks :)

**Comment by leozide** [comment]
I've replaced the table with an image, the next step will be to merge the 2 images.
