### ISSUE TITLE
ENHANCEMENT: Highlight missing items using export step highlight feature

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#438]
Hi Leo,

It isn't always easy finding missing parts or elements within a model, expecially if those are embedded:

Would you be able to apply the same highlighting method used for current steps in the HTML export feature to make them more visible?

I would also recommend also maybe making a small dialog (preferably exportable or out of normal text) that would list the file names / parts missing or not found.

See attached:

![image](https://user-images.githubusercontent.com/5674757/72465644-8f357c00-37a5-11ea-94c3-7e0f725cfde8.png)

Thanks

**Comment by j6t** [comment]
For me it is unclear what you mean. What is a "missing part"? And what does the screenshot illustrate?

**Comment by rsbx** [comment]
I believe what he's  asking for is a way to find out what part IDs & locations, used in the current model, can't be found in the local parts library and model files and to highlight the placeholder shapes and lines in the timeline.

**Comment by nathaneltitane** [comment]
> I believe what he's asking for is a way to find out what part IDs & locations, used in the current model, can't be found in the local parts library and model files and to highlight the placeholder shapes and lines in the timeline.

precisely

**Comment by nathaneltitane** [comment]
> For me it is unclear what you mean. What is a "missing part"? And what does the screenshot illustrate?

overthinking much? most of your responses are overdone my dude.
