### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#441]
The bricklink export feature could benefit from an additional option:

when uploading a bom as is, some part ID are mismatched or are not recognized by the bricklink importer.

To get a bom working, one has to regex and replace the miscellaneous or unrecognized IDs by whichever one is assigned as the main ID for a part on bricklink - the best example i have right now would be 12825.dat which is only recognized as 2555.

The user could have a file with the list of items to replace on export (or such a thing could be integrated into the settings.conf for repeatability and portability.

ex.:

12825	>	2555
93794	>	2555
15712	>	2555
50951	>	50945
98313	>	53989
48729a	>	48729
48729b	>	48729
4287a	>	4287
4287b	>	4287
4287c	>	4287
6141	>	4073

Case:

1 build model using parts
2 export said model using the bricklink xml export feature
2b exporter parses replacement list
2c xml bom is exported using actual bricklink recognized IDs
3 XML bom upload does not return any errors.

also see #439 for relevant issue on bom tags missing

thanks

**Comment by hfiguiere** [comment]
PR #632 has been merged and should address most of your concerns about parts not being properly mapped.

**Comment by j6t** [comment]
Has this been addressed? Can this issue be closed?
