### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by inglesuniversal** [leozide/leocad#442]
Can this code/script be ported to be accessible via website?

Best regards

**Comment by nathaneltitane** [comment]
@inglesuniversal which code/script?

**Comment by inglesuniversal** [comment]
sorry if I was clear enough.

I would like to know if you project can be ran from a server (LAMP) and work through a browser or it can only be install on a local computer (.exe or .dmg)

Thanks

**Comment by leozide** [comment]
It needs to be installed
