### ISSUE TITLE
Enhancement - Collada JSON format

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#444]
Hi Leo,

any chance you could have a look at pushing out collada in json format ?
this would be helpful in delivering files with a much, much smaller footprint which lead to a better online/webgl viewing experience.

Thank you

**Comment by leozide** [comment]
I don't understand what you mean, Collada is xml.

**Comment by nathaneltitane** [comment]
so could i load collada as xml under threejs? json is native and recomended
