### ISSUE TITLE
ISSUE: The Transformation Absolute/Relative (magic wand button) is not in the Edit menu

### ISSUE THREAD

**Issue by Lswbanban** [leozide/leocad#448]
The Magic Wand button in the toolbar that allow to toggle between absolute and relative transformation doesn't have a counterpart in the Edit menu.

Therefore it is impossible to associated a shortcut key binding.

I would like to add a shortcut key on that feature because it is very handy to toggle between the two mode, so please add the missing menu item.

**Comment by nathaneltitane** [comment]
@leozide this request/bug, like many others of the same nature addresses the fact that most of the features if not all of them should have a keybinding entry associated to them for users to specify and make their workflow easier.

Thank you for considering it.

**Comment by leozide** [comment]
@Lswbanban You can set a shortcut for it even if it's not in any menu, this action is called 'Relative Transforms' under the Edit section of the shortcuts (it was called 'TransformRelative' in older versions so look for both):

![image](https://user-images.githubusercontent.com/9685066/75187262-92a21880-56fe-11ea-99a8-d2b8151514dd.png)

@nathaneltitane As far as I know all actions can have their shortcuts configured. Please post specific actions that are missing and I'll add them.

**Comment by nathaneltitane** [comment]
I've already opened tickets to that effect @leozide , including usability improvements and other requests...

Maybe we should open a mega ticket?

**Comment by Lswbanban** [comment]
@leozide Sorry, my bad, I didn't see that line. Since I noticed that all the shortcuts where organized like the menus, I just assume there was no more, no less shortcuts than menus items.

You can close this issue, unless you want to add the menu item in the Edit menu.
