### ISSUE TITLE
Bricks don't appear correctly

### ISSUE THREAD

**Issue by jrobinson-uk** [leozide/leocad#449]
Just installed leocad under linux and downloaded the parts library.

Any brick I add fails to render properly in the design area, only rendering some faces or elements of the brick. See attached:

![Screenshot from 2020-02-28 20-55-40](https://user-images.githubusercontent.com/4701504/75587061-8e169080-5a6d-11ea-80fa-5804fd105d76.png)

**Comment by leozide** [comment]
This looks like there's something wrong with your parts library.

**Comment by jrobinson-uk** [comment]
It's a vanilla install, not sure how it can be parts....? I'll try downloading parts again

**Comment by jrobinson-uk** [comment]
Ok, yeah that fixed it
