### ISSUE TITLE
Reference Images

### ISSUE THREAD

**Issue by emanuele3d** [leozide/leocad#45]
Hi @leozide, newbie user here.

In the Visual Effects industry it is typical to make 3D models out of reference images, which could be photos, blueprints or even concept art. We do this by adding to the 3d scene one or more orthogonal planes with the reference images mapped onto them. See an example [here](https://www.youtube.com/watch?v=2dLMctUGKXw).

I haven't found a way to do this in LeoCAD, can you confirm? If so, can you add it to the wishlist? It would be very beneficial for scale builds. 

Obviously the best way from a performance perspective would be to do it with simple quads with a texture mapped onto it, like it is done in the example video. But perhaps you might want to catch two pigeons with one stone and implement the functionality to add arbitrary "stickers" to groups of bricks. In that scenario we'd simply add one or more images to one or more large smooth plates or even to a wall of bricks.

What do you think?

**Comment by leozide** [comment]
There isn't any way to do that right now, there used to be a way to set a texture on the base plane and I experimented with having vertical grids similar to what you're asking (but without the textures).

**Comment by emanuele3d** [comment]
And what was the outcome of the experiment and why did you eventually remove the way to have a texture on the base plane?

**Comment by leozide** [comment]
I didn't think the vertical grid was helping with the placement of pieces during my tests so I never checked it in.

The base plane was probably removed when I removed the terrain support. I saw it as a publishing feature and I wanted to focus on instructions more.

Here's an old screenshot of what it looked like:

![image](https://cloud.githubusercontent.com/assets/9685066/25829934/550c6b9e-340e-11e7-8621-37f025a23bfc.png)

**Comment by emanuele3d** [comment]
I see what you mean. Even if I was building a larger model I'd use large plates as grounds rather than a generic plane with a texture. 

So you had vertical, axis-aligned grids? I.e. along the XY and ZY planes (assuming Y is up)? With spacing between lines matching a 1x1 brick? When I worked in VFX and done other 3D work axis-aligned grids were useful, but I wasn't dealing with discrete objects like bricks and snapping to the (highly customizable) grids was quite useful, especially if the snapping could be quickly turned on/off.

But I can see how with Lego bricks they might be more redundant: all you need is a big plate to snap your bricks to. 

How about resurrecting that code adding the functionality to have a texture-mapped plane under the (infinite?) grid? What would be important is that the plane can be resized independently, so that, say, somebody using blueprints to model a car can choose between creating a modest 9-stud-wide model or, say, a much more complex 13-stud-side model.

**Comment by leozide** [comment]
I've written an example on how to get this to work:

http://www.leocad.org/docs/texmap.html

**Comment by emanuele3d** [comment]
Thank you @leozide : I will give it a try.

**Comment by DLu** [comment]
I have two questions about the referenced example. First, where does that code go? Secondly, what folder would you put the images in? All of the configurations I've tried thus far have resulted in segmentation faults.

**Comment by leozide** [comment]
You have to open the ldr file with a text editor and paste it there.

Images should go in parts/textures. How did you get a segfault?

**Comment by DLu** [comment]
Using `LeoCAD-Linux-18.02-x86_64.AppImage`, I put the referenced code by itself in a textfile. I don't know anything about the LCD format, so I don't know if there's something else that is supposed to go in there. The saved LCD files I have are binary formatted. 

When you say `parts/textures`, do you mean within a parts library? Or does it go somewhere else?

**Comment by DLu** [comment]
Actually, I just realized this newer version uses ldr files. Let me see if that helps.

**Comment by leozide** [comment]
The LCD format is deprecated, you can read files but cannot save anymore.

The parts/textures folder inside your LDraw library folder (something like /home/dlu/ldraw/parts/textures).

**Comment by DLu** [comment]
The combination of those two elements got it. Thanks!
