### ISSUE TITLE
Make all applicable unofficial meta tags offical

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#450]
Could you please refer to the [meta official list](https://www.ldraw.org/article/401.html) and revert all applicable meta tags to their official counterpart?

**Comment by j6t** [comment]
Can you please provide an example? It would help understand what you mean.

I'd like to note that the link above points to a non-existent page.

**Comment by nathaneltitane** [comment]
> Can you please provide an example? It would help understand what you mean.
> 
> I'd like to note that the link above points to a non-existent page.

well it sure was active when I posted it a year or so ago...

cannot find its equivalent or moved page now...
