### ISSUE TITLE
Save file don't just save file

### ISSUE THREAD

**Issue by ondratu** [leozide/leocad#451]
## Problem
Hi, when i modify model, and then save it, save-as dialog try to save file with same path, same name, but without extension. Supported files are select on dialog, and i don's see any file. I must select all files, next select my ldr file and then save the file.

Other process goes to new file with same name, but without extension.

## version
LeoCAD Version 19.07.01 (Debian Bullseye (Testing))

Qt Version 5.12.5 (compiled with 5.12.5)

OpenGL Version 3.0 Mesa 19.3.3 (GLSL 1.30)
Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)  - Intel Open Source Technology Center

Color Buffer: 24 bits RGBA double buffered
Depth Buffer: 24 bits
Stencil Buffer: 8 bits

GL_ARB_vertex_buffer_object extension: Supported
GL_ARB_framebuffer_object extension: Supported
GL_EXT_framebuffer_object extension: Supported
GL_EXT_blend_func_separate: Supported
GL_EXT_texture_filter_anisotropic extension: Supported (max 16)

**Comment by leozide** [comment]
I can't get this to happen, can you post an example file with the problem?

**Comment by ondratu** [comment]
Load the file
![Snímek z 2020-03-14 13-09-42](https://user-images.githubusercontent.com/6469029/76681641-88848300-65f5-11ea-80cc-a2dca6fa3a13.png)

Do change
![Snímek z 2020-03-14 13-10-01](https://user-images.githubusercontent.com/6469029/76681639-87ebec80-65f5-11ea-949c-b043284bb31a.png)

Save file (whatever you use FIle->Save or Ctrl+S)
![Snímek z 2020-03-14 13-10-24](https://user-images.githubusercontent.com/6469029/76681638-87535600-65f5-11ea-8feb-bf683629e678.png)

Files in directory, eggbot.ldr is file which i load before, eggbot is new one:
```
drwxr-xr-x  2 mcbig mcbig 4096 Mar 14 13:11 .
drwxr-xr-x 14 mcbig mcbig 4096 Mar  8 16:59 ..
-rw-r--r--  1 mcbig mcbig 6769 Mar 14 13:11 eggbot
-rw-r--r--  1 mcbig mcbig 6769 Mar  9 22:35 eggbot.ldr
```

It's look like, that problem is in extension in file path. I try to use dat as file extension, but it is the same. Only `ldr` and `dat` files are listed in open file dialog with supported types selected.

**Comment by leozide** [comment]
I think the problem here is that you're trying to save a file with submodels with the .ldr extension. The app sees that and prompts you to choose a new name instead, as files with submodels should be saved with the .mpd extension instead (according to the current spec).

The open dialog should show ".lcd .ldr .dat .mpd", I don't see any places that show only ".ldr .dat", can you double check?

The lack of extension in your case is OS dependent, on Windows and Linux-KDE it will add the extension automatically.

**Comment by ondratu** [comment]
You are right, when i use mpd file extension, that works fine. Leocad behavior is:
* new model without aby submodels -> Save As append .ldr automatically
* new model with submodels -> Save As append .mpd automatically
* save model, previously saved as ldr (without submodels) -> don't append any extension

So:
* there could be file type for each extension in open/save dialog
* default extension could be model (.mpd) no submodel (.ldr) like now
* When model have submodels, Save As could be right, but with model extension, no without extension like now

LeoCAD is in QT, which i don't know, so i can't help you with it.

**Comment by leozide** [comment]
> there could be file type for each extension in open/save dialog
default extension could be model (.mpd) no submodel (.ldr) like now

That's how it works right now

> When model have submodels, Save As could be right, but with model extension, no without extension like now

This part depends on your Window manager, it works like that for Windows and KDE. What are you using?

**Comment by ondratu** [comment]
> > there could be file type for each extension in open/save dialog
> > default extension could be model (.mpd) no submodel (.ldr) like now
> 
> That's how it works right now

No, my version in Debian Linux have dafault extension `.ldr`. I just start LeoCAD -> add some part, then File -> Save -> in Save As dialog, I see New Model.ldr. So default extension is submodel now.

> > When model have submodels, Save As could be right, but with model extension, no without extension like now
> 
> This part depends on your Window Manager, it works like that for Windows and KDE. What are you using?

How Window Manager could have effect to selected extension on Save As dialog ? That does not make sense.
