### ISSUE TITLE
Copy from one step and paste to next

### ISSUE THREAD

**Issue by ondratu** [leozide/leocad#452]
When I copy some parts from in one step, then move to another, and paste it, new parts are paste to same step, when origin parts are. So I must append new parts in each step, never mind, that are really same, but on another position.

**Comment by nathaneltitane** [comment]
I second this one, either there is no way to get LeoCAD to understand the 'current step' is selected to paste to, or there is some bug preventing it from actually happening

**Comment by nathaneltitane** [comment]
@leozide this could ahve to do with how leocad recognizes or interprets the current or selected step: a tad ambiguous?

**Comment by leozide** [comment]
This is actually done on purpose, I can change it.
