### ISSUE TITLE
Submodels with names beginning with the letter 'P' do not show in the "Models" list.

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#453]
Submodels with names beginning with the letter 'P' (uppercase or lowercase) do not show up in the "Models" category of the "Parts" pane. Includes is a simple .MPD file that demonstrates the behavior.

Version: 18.02 from the Debian.org Debian 10 "Buster" repository.

[Model.mpd.txt](https://github.com/leozide/leocad/files/4330746/Model.mpd.txt)

0 FILE New Model.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 PSubmodel.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 BSubmodel.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 ASubmodel.ldr
0 NOFILE
0 FILE ASubmodel.ldr
1 1 0 -72 0 1 0 0 0 1 0 0 0 1 3005.dat
0 NOFILE
0 FILE BSubmodel.ldr
1 2 0 -48 0 1 0 0 0 1 0 0 0 1 3005.dat
0 NOFILE
0 FILE PSubmodel.ldr
1 4 0 -24 0 1 0 0 0 1 0 0 0 1 3005.dat
0 NOFILE

**Comment by leozide** [comment]
They show for me, can you try a more recent version?

**Comment by rsbx** [comment]
I tried the 19.07 AppImage version and found the same behavior.

However, removing my config file fixed the issue with the 19.07 AppImage 
version.

Playing with the differences between a newly created config file and my 
config file, I find that the behavior can be toggled by the "Show 
Decorated Parts" checkbox of the "Parts" pane in both the 19.07 AppImage 
version and the 18.02 Debian packaged version.
