### ISSUE TITLE
Awesome script

### ISSUE THREAD

**Issue by inglesuniversal** [leozide/leocad#455]
I have access to bitnami servers under any LINUX configuration... can this script be installed onto one of them in order to be accesible via web page or VPN ?

Hope you can give me some pointers

Best regards and congratulation for your amazing work!

Hugo

**Comment by Symbian9** [comment]
> can this scrip

Are you sure that you posted in correct issues tracker?

This is issues tracker of *LeoCAD*, CAD for digital Lego models creating.

**Comment by inglesuniversal** [comment]
*** I just want to know if the Lego builder app LeoCAD can run and be accessed by users via web

**Comment by Symbian9** [comment]
>  I just want to know if the Lego builder app LeoCAD can run and be accessed by users via web
>
> Not just locally.

As I know there are few ways to run it online, for example using such services as *RollAp*, 

- https://www.rollapp.com/app/leocad

Another option is to launch it throw *VNC* on remote PC (think, this is what you really looking for):

- https://en.wikipedia.org/wiki/Virtual_Network_Computing

**Comment by nathaneltitane** [comment]
or via ssh with a display export... this isn't an issue or feature request @inglesuniversal @Symbian9

**Comment by inglesuniversal** [comment]
sorry nathaneltitane  ... I'm fairly new handling this tech. 

Any links to posts you might consider helpful are appreciated.

**Comment by Symbian9** [comment]
>  this isn't an issue or feature request

I not claim that this **question** is an "issue"; I just told about "issues tracker" ( aka https://github.com/leozide/leocad/issues/ )

**Comment by Symbian9** [comment]
> > or via ssh with a display export...
>
> Any links to posts you might consider helpful are appreciated.

Here are few useful threads:

- https://stackoverflow.com/questions/12040551/using-ssh-to-open-application-on-desktop
- https://www.shellhacks.com/start-gui-application-remote-computer-ssh/
- https://askubuntu.com/questions/47642/how-to-start-a-gui-software-on-a-remote-linux-pc-via-ssh
