### ISSUE TITLE
Feature request: Add terminal widget?

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#457]
Hi Leo,

I was wondering if it was possible to integrate a terminal emulatir widget into leocad and here is the reason why:

I now find myself using my ldraw linux commandline utility quite often to modify colors or bricks in bulk for a model to keep them up to date with actual inventories and parts that are being made.

It would be practical to make use of the widgets setup to add a little integrated terminal that could live within leocad to help keep the workflow streamlined and minimize the number of widows required when working on a model.

If you would like to have a look at the shell utility I'm talking about, you can go to [https://github.com/nathaneltitane/ldraw](url)

Thanks again for all your amazing work :)

**Comment by Symbian9** [comment]
> I was wondering if it was possible to integrate a terminal emulatir widget into leocad and here is the reason why

Could you mockup your idea UI? (or show screenshot from other apps where such feature exists)

**Comment by nathaneltitane** [comment]
@Symbian9 
most common modern file managers integrate terminal emulators now - here's kde dolphin with a terminal emulator panel open:

![Screenshot_20200412_145043](https://user-images.githubusercontent.com/5674757/79077156-466e6000-7ccd-11ea-80a3-b3acb98514c7.png)

if i were to mock it up it would look something like this:

![Screenshot_20200412_145445](https://user-images.githubusercontent.com/5674757/79077188-92210980-7ccd-11ea-99a3-132f0ad7f6fb.png)

where the terminal is just like another tool widget that can be shown or added to the leocad setup

**Comment by leozide** [comment]
I'm not sure how I feel about this, it may be too much work to account for all the different platforms for something that very few people will use.

Would a menu with external tools like Visual Studio does be enough?

https://docs.microsoft.com/en-us/visualstudio/ide/managing-external-tools?view=vs-2019

**Comment by nathaneltitane** [comment]
@leozide i was just throwing the idea out there as a nice to have (maybe) - if it's too much trouble i can live with a terminal open next to my leocad session

I rather we focus on usability and actual needed features then :)

Thank you though!
