### ISSUE TITLE
Submodel selection does nothing

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#459]
Small bug/annoyance based off of predicted dialog behavior:

When opening submodel dialog, highlighting desired submodel and pressing 'OK' nothing happens

Should we normally expect the submodel to be activated? That's what selection would normally entail, no?

Expected bahavior: Highlighting submodel + OK = activate and open submodel

Thank you!

**Comment by leozide** [comment]
Some people complained so you have to click the Activate Model button.

**Comment by rsbx** [comment]
<devil's advocate>

One size fits all?

</devil's advocate>

**Comment by nathaneltitane** [comment]
@leozide so i'm not crazy, i knew the behavior had changed somehow.

Seemingly it feels odd to have that sort of behavior: if you're in the submodel dialog, you should expect that sort of thing.

Could we maybe have an option switch to toggle behavior?

Thank you
