### ISSUE TITLE
Crash with latest version 19.07.01

### ISSUE THREAD

**Issue by Pakito84** [leozide/leocad#460]
Hi,
discovering Leocad yesterday, I've started a project and it was all fine...until today! When I lauched Leocad it was slow and not working well, freezing my pc. Well I closed the program and launched it again. And since then, this message appear:
"LeoCAD just crashed. Crash information was saved to the file.........;please send it to the developers for debugging."
I've tried to uninstall and install again, but the message comes again.
Any help please?
I'm on win7 by the way.

**Comment by viras777** [comment]
I also close with a crash. Dump here.

[leocad.zip](https://github.com/leozide/leocad/files/4496423/leocad.zip)

**Comment by Pakito84** [comment]
do I use this zip or something?

**Comment by viras777** [comment]
Yes, I used zip to download leadad.dump here for you

**Comment by Pakito84** [comment]
I'm really sorry Viras, but I'm not very smart with all that things... I've extracted the zip and put instead of the other one in the folder but it still crashes. did i do something wrong? thank you so much for your help

**Comment by viras777** [comment]
I am not a developer:) I am the same user as you who found bug :)

**Comment by Pakito84** [comment]
oh..I see :( well... I'm trying to continue on LDCad instead..

**Comment by Pakito84** [comment]
please anyone to help me? I was so happy to discover this :(((((

**Comment by leozide** [comment]
> I also close with a crash. Dump here.
> 
> [leocad.zip](https://github.com/leozide/leocad/files/4496423/leocad.zip)

Which version are you using?

**Comment by leozide** [comment]
> Hi,
> discovering Leocad yesterday, I've started a project and it was all fine...until today! When I lauched Leocad it was slow and not working well, freezing my pc. Well I closed the program and launched it again. And since then, this message appear:
> "LeoCAD just crashed. Crash information was saved to the file.........;please send it to the developers for debugging."
> I've tried to uninstall and install again, but the message comes again.
> Any help please?
> I'm on win7 by the way.

Please post the leocad.dmp file mentioned in the message you get when you crash and I'll take a look.

**Comment by Pakito84** [comment]
[leocad.zip](https://github.com/leozide/leocad/files/4496916/leocad.zip)

**Comment by Pakito84** [comment]
I'm using the version 19.07.01. Saying again, yesterday I was using it for the 1st time without any problems.

**Comment by Pakito84** [comment]
thank for trying help me, but forget. I won't use this program anymore.
