### ISSUE TITLE
saving file without extension prompts save dialog

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#462]
I inadvertantly dis a 'Save as' of a model to test some design changes and backspaced the extension to modify the filename as well.

After making the changes and pressing 'Save' , leocad prompts me to save the file once again, then asking if i should overwrite teh already existing model with the same file name.

On inspection, saving as or saving, at large, does not seem to append the appropriate file extension according to the model structure (ldr/mpd)

Expected behavior:

check for submodels
check if filename has extension
test file extension against file structure
correct or append appropriate extension if wrong or not present.

**Comment by leozide** [comment]
I need a better example, it always appends the correct extension for me

**Comment by nathaneltitane** [comment]
I wouldn't know which other example to give you as it was the first time in a very long time I had not seen or experienced anything like it - i know that manually removing the extension in the file name field triggered it for me :/ - sorry @leozide

**Comment by hfiguiere** [comment]
it doesn't append the extension here.

I run GNOME, which mean the file dialog is Gtk. (see bug #610 for an exhibit of "things are different")
