### ISSUE TITLE
no shortcuts or context dialog available to show tool palettes

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#463]
Hello again :)

I've come across a peculiar usage case in KDE:
An extension is available to make the application menu global (a la MacOS).
When using it with leocad in full screen or immersive mde (hide taskbar - which i do), it becomes impossible to quickly toggle tool palettes on or off either from a context menu or via a shortcut/combo

Edit: although I just noticed that right clicking an already present widget does bring up the tools/widget toggles menu, if they're all toggled off, there does not seem to be any other quick solution that navigating the menu (think on the fly editing)

Expected behavior:

Provide contextual access to all tool menus
Provide keyboard shortcut bindings/customization for all tool palettes and widgets that can be toggled on/off when editing according to user needs.

see attached

![Screenshot_20200421_130502](https://user-images.githubusercontent.com/5674757/79892754-fd0ac880-83d0-11ea-83cb-ce775de18a22.png)
![Screenshot_20200421_130513](https://user-images.githubusercontent.com/5674757/79892762-ff6d2280-83d0-11ea-9484-da6cb66072c5.png)

**Comment by leozide** [comment]
You can toggle them from the view menu
