### ISSUE TITLE
Dark theme/ background overlay colors

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#464]
When using dark themes or setting a dark bg color for a model, some overlays become difficult to see, such as the 'rotate view' which consistently draws a black overlay on the model space.

see attached

![Screenshot_20200421_131012](https://user-images.githubusercontent.com/5674757/79893027-73a7c600-83d1-11ea-9e6b-8bd1cc7d88f6.png)

**Comment by leozide** [comment]
Do you mind sharing your stylesheet? I've been considering including a dark theme and I want to see if I like it.

**Comment by nathaneltitane** [comment]
This is the included Breeze Dark that's currently found on KDE 5.16 and up.

I've made the leocad customizable colors match the palette by manually color picking them.

**Comment by Symbian9** [comment]
> > Do you mind sharing your stylesheet?
>
> This is the included Breeze Dark that's currently found on KDE 5.16 and up.

@leozide, What about add themes support to *LeoCAD*  by choosing `.qss` stylesheet files via "Preferences" menu, independently from DE/WM theme?

- https://github.com/leozide/leocad/issues/396
