### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#467]
Compiling revision a5fde91ee on an up-to-date Debian 10 "Buster" (as of 2020/05/02-17:30Z) generates the following compiler warnings:

common/project.cpp: In member function ‘bool Project::ExportPOVRay(const QString&)’:
common/project.cpp:1791:26: warning: ‘%s’ directive writing up to 1023 bytes into a region of size 253 [-Wformat-overflow=]
     sprintf(Entry.first, "lg_%s", Dst);
                          ~~~~~~  ~~~
common/project.cpp:1791:12: note: ‘sprintf’ output between 4 and 1027 bytes into a destination of size 256
     sprintf(Entry.first, "lg_%s", Dst);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/project.cpp:1798:26: warning: ‘%s’ directive writing up to 1023 bytes into a region of size 253 [-Wformat-overflow=]
     sprintf(Entry.first, "ar_%s", Dst);
                          ~~~~~~  ~~~
common/project.cpp:1798:12: note: ‘sprintf’ output between 4 and 1027 bytes into a destination of size 256
     sprintf(Entry.first, "ar_%s", Dst);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/project.cpp:1930:25: warning: ‘%s’ directive writing up to 255 bytes into a region of size 253 [-Wformat-overflow=]
    sprintf(Entry.first, "lc_%s", Name);
                         ~~~~~~  ~~~~
common/project.cpp:1930:11: note: ‘sprintf’ output between 4 and 259 bytes into a destination of size 256
    sprintf(Entry.first, "lc_%s", Name);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

common/pieceinf.cpp: In member function ‘void PieceInfo::CreateProject(Project*, const char*)’:
common/pieceinf.cpp:105:9: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 128 equals destination size [-Wstringop-truncation]
  strncpy(m_strDescription, Project->GetFileName().toLatin1().data(), sizeof(m_strDescription));
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/pieceinf.cpp: In member function ‘void PieceInfo::SetModel(lcModel*, bool, Project*, bool)’:
common/pieceinf.cpp:64:9: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 256 equals destination size [-Wstringop-truncation]
  strncpy(mFileName, Model->GetProperties().mName.toLatin1().data(), sizeof(mFileName));
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/pieceinf.cpp:66:9: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 128 equals destination size [-Wstringop-truncation]
  strncpy(m_strDescription, Model->GetProperties().mName.toLatin1().data(), sizeof(m_strDescription));
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

common/camera.cpp: In member function ‘void lcCamera::Center(const lcVector3&, lcStep, bool)’:
common/camera.cpp:965:8: warning: variable ‘Yaw’ set but not used [-Wunused-but-set-variable]
  float Yaw, Pitch, Roll;
        ~~
common/camera.cpp:965:13: warning: variable ‘Pitch’ set but not used [-Wunused-but-set-variable]
  float Yaw, Pitch, Roll;
             ~~~~

The warnings are not new; just annoying.

Full typescript: [typescript.txt](https://github.com/leozide/leocad/files/4568443/typescript.txt)

**Comment by rsbx** [comment]
The first attached patch fixes the common/pieceinf.cpp warnings.

[0001-Fix-compiler-warnings.patch.txt](https://github.com/leozide/leocad/files/5704034/0001-Fix-compiler-warnings.patch.txt)

The second attached patch changes the common/project.cpp warnings from overflow to truncation. I'm not sure what the proper and complete fix is.

[0001-Change-warnings-from-overflow-to-truncation.patch.txt](https://github.com/leozide/leocad/files/5704037/0001-Change-warnings-from-overflow-to-truncation.patch.txt)

**Comment by leozide** [comment]
What warnings are you seeing in pieceinf.cpp? I don't see anything wrong with any of the compilers I use.

strncpy doesn't always append a 0 at the end of the string so those lines should stay.

**Comment by rsbx** [comment]
My initial message in this issue has the warnings for pieceinf.cpp; specified bound ... equals destination size. You're right, the lines I deleted need to stay (I was thinking src limit instead of dst limit).

**Comment by rsbx** [comment]
Warnings fixed; a full compile is quiet now.
