### ISSUE TITLE
Leocad windows10 not working

### ISSUE THREAD

**Issue by eriksmit19** [leozide/leocad#468]
Hi, how to get leocad working under w10. After starting leocad a message popsup  this version is not working.

**Comment by kevinsmia1939** [comment]
Would need more info, screenshot and your machine hardware specification would be a start.

**Comment by eriksmit19** [comment]
See attached files. Image is Dutch says  unkown decompression ?

**Comment by leozide** [comment]
I don't know what app you're trying to install, where did you download it? You can try downloading again in case the file is corrupt.

**Comment by eriksmit19** [comment]
Hi,
The uploaded files (above) and images are from Ldraw (Ldraw.org) Leocad is included in this file, I was told. Some minutes ago I installed leocad from leocad.org. See below I found no setup.log file.

This is after install
![Leocad install](https://user-images.githubusercontent.com/64733076/81537942-444ffd80-936e-11ea-90d0-71f76751aebf.JPG)

Tried to run leocad
![leocad run](https://user-images.githubusercontent.com/64733076/81538000-5df14500-936e-11ea-96fc-a730d0679d27.JPG)

**Comment by eriksmit19** [comment]
Hi, I found a log file from MS Visual C++. Perhaps this is why its not working.
[dd_vcredist_amd64_20200511100425.log](https://github.com/leozide/leocad/files/4608288/dd_vcredist_amd64_20200511100425.log)

**Comment by eriksmit19** [comment]
![ms visual](https://user-images.githubusercontent.com/64733076/81539020-e0c6cf80-936f-11ea-9e0f-99e448690bac.JPG)

**Comment by leozide** [comment]
It looks like the file from leocad.org installed correctly, is it not working?

**Comment by eriksmit19** [comment]
No, After starting leocad I get the blue popup. This app can't run on your PC

**Comment by VictorTagayun** [comment]
I have this view on win10x64
Any idea why it is like this?

![problem01](https://user-images.githubusercontent.com/12908735/87114780-07d44b80-c2a4-11ea-8c99-95cebd98034a.png)
