### ISSUE TITLE
Where does parts in appimage for linux from? Can multiple part libraries be added?

### ISSUE THREAD

**Issue by kevinsmia1939** [leozide/leocad#469]
Hello,

I am running on openSUSE.
I tried running LeoCAD-Linux-19.07.1-x86_64.AppImage which contain the parts library bundled.
However, when I try adding library.zip file which were bundle in resources/library.zip in the source code, it replace the original parts in the appimage.

1. Where can I get the parts bundled with the appimage? I try adding ldrawunf.zip, it is not it either.
edit: Just found it: https://www.ldraw.org/parts/latest-parts
2. Can I prevent the bundled parts in Appimage from being replace when adding extra parts library?
3. Can I add multiple .zip part library? I can only seems to choose one .zip file, select part library folder doesn't seems to do it either.

Thanks.

**Comment by nathaneltitane** [comment]
@kevinsmia1939 i believe you may have to specify the ldraw parts library in the preferences to override the bundled ones: hence you would have to download complete.zip and or 'latest-parts' and ldrawunf.zip if you'd like to add the unofficial parts to the list.

Hope this helps.

**Comment by leozide** [comment]
Some documentation here: https://www.leocad.org/docs/library.html

**Comment by kevinsmia1939** [comment]
@nathaneltitane 
Hello,
You are right, it override the previous library. 

@leozide Does leocad search for zip file under the parts library? The default parts library is /usr/ldraw but if I put zip file in /usr/ldraw/, leocad won't see the zip file unless I specify /usr/ldraw/complete.zip

**Comment by nathaneltitane** [comment]
@kevinsmia1939 
You can select the little zip icon beside the path input line in preferences or just type in the full path including the extension and restart leocad.
Leocad will look for other references under that same path automatically.

For convenience I suggest keeping stuff under ../ldraw/ as a lot of apps and utilities will expect it, wherever ../ldraw/ may be on your system.

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939
> You can select the little zip icon beside the path input line in preferences or just type in the full path including the extension and restart leocad.
> Leocad will look for other references under that same path automatically.
> 
> For convenience I suggest keeping stuff under ../ldraw/ as a lot of apps and utilities will expect it, wherever ../ldraw/ may be on your system.

Can leocad look under ../ldraw/ and use the zip file it found under that without specifying ../draw/complete.zip? Is this the intended behavior?

**Comment by nathaneltitane** [comment]
@kevinsmia1939 i do believe it would if you do not specify the archive itself but rather the path in the input box

**Comment by Symbian9** [comment]
> > Can I add multiple .zip part library? I can only seems to choose one .zip file, select part library folder doesn't seems to do it either.
>
> Some documentation here: https://www.leocad.org/docs/library.html

@leozide What about add feature to allow load `../complete.zip`, `../unfldraw.zip` and parts from `../my-parts/` folder (with my custom parts) in same LeoCAD session?

**Comment by leozide** [comment]
I planned to do something like that a long time ago, there's probably a bug about it here somewhere. It was more work than I originally thought so I decided to work on other things instead.
