### ISSUE TITLE
Part Categories Not Showing

### ISSUE THREAD

**Issue by justlouis** [leozide/leocad#480]
Hello, I go LeoCAD yesterday and it ran with no issues, but now the categories bar isn't showing up and I am unsure as to why; I have no idea how to get it back. I did a reinstall and it didn't work, the issue persists. How can I get it bak to normal?

**Comment by leozide** [comment]
You can toggle it from the main menu, View->Toolbars->Parts

**Comment by justlouis** [comment]
No the parts show but it doesn't have the part categories, I think it is just stuck on the "bricks" one and I can't change it

**Comment by leozide** [comment]
That's weird, can you post a screenshot of what it looks like? In older versions it was possible to hide the categories and you'd have to hover the mouse between the search box and the edge to drag and resize it.

**Comment by justlouis** [comment]
Ah I tried that and it worked; I am using it MacOS so that might have had something to do with it. Thank you so much for your help!!
