### ISSUE TITLE
part 35186 rendering problem (model 42110)

### ISSUE THREAD

**Issue by dan-2019** [leozide/leocad#485]
Yellow part 35186.dat of the 42110 Land Rover Defender.mpd (from OMR) displays as a cube.
Part is in the submodel 10 42110 frontaxle.ldr

LDCad renders the part correctly, so probably a rendering problem in LeoCad.

**Comment by nathaneltitane** [comment]
@dan-2019 when a part is substituted by a rectangular polygon or 'cube' in Leocad it can mean a couple things:

1-The part is referenced in the model but is not actually in the parts database or directory where you call the ldraw parts from
2-The part is probably an internal reference to the model that is missing (would have been added as a submodel for portability or any other reason(unofficial parts per say))

Make sure your library is complete and properly loaded (do so via edit > preferences and specify the folder path that is your parts library)

**Comment by dan-2019** [comment]
@nathaneltitane After setting the parts path (under View -> Preferences -> General tab ->Part Library) and restarting LeoCad, the aforementioned part now renders as expected. I just wonder where LeoCad was fetching its parts until now.
Issue solved! Thanks!

**Comment by leozide** [comment]
The default parts library depends on your platform, but if you downloaded one of the installers then it comes with a built in library and uses it unless told otherwise.

**Comment by dan-2019** [comment]
In my case it's the installer for Windows 10 (LeoCAD version 19.07.1).
However, I could not find any parts under the program folder %PROGRAMFILES(X86)%\LeoCAD
Nor under the %userprofile%\AppData\Local\LeoCAD Software\LeoCAD unless it's (unlikely) the cache folder in it.

**Comment by leozide** [comment]
Do you have %PROGRAMFILES(X86)%\LeoCAD\library.bin?

**Comment by dan-2019** [comment]
Yes, I have. I found out that although it has the .bin extension it's a compressed zip file... 
Just wondering, is this unaltered LDraw folder that was compressed?

**Comment by leozide** [comment]
Yes. See https://www.leocad.org/docs/library.html
