### ISSUE TITLE
I can't open the parts list

### ISSUE THREAD

**Issue by EkamjeetSingh** [leozide/leocad#487]
I can't open the parts list I accidently crossed out . I've tried almost everything

**Comment by leozide** [comment]
In the main menu: View -> Toolbars -> Parts

**Comment by EkamjeetSingh** [comment]
Hey, leozide/leocad,
Thanks for helping me out with this, I'm able to do it.
I'm very happy now the list has opened up and I will be able to open it if
it closes.
It's all back to normal now.
Thanks again,
Ekamjeet Singh
