### ISSUE TITLE
DISCUSSION: Color picker functionality not as expected?

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#492]
Aside from handling the preview color of parts when a build color is picked, shouldn't the color picker primarily enable the selection and assignment of a color to a model space part when editing?

If not, maybe the feature ought to be reviewed or renamed to something else?

**Comment by nathaneltitane** [comment]
@leozide 

Ah I see.

Coming from a design standpoint, color pickers can also be made to directly apply color to an object via selection.

Example:
1-Select part(s) in model space for edit
2- activate color picker
3- Select desired color on other part in model space
4-color picker attributes selected color to parts selected in step 1

**Comment by mlsomers** [comment]
This confused me as well.
Is there any (other) way to change the color of selected bricks (without removing and replacing them with new bricks)?

**Comment by leozide** [comment]
After the recent changes you can:

- Use the paint tool
- Assign a mouse shortcut
- Select bricks and click on the color list button to paint
- Select bricks and press the keyboard shortcut
- Select bricks and use the properties widget color popup

Please comment/reopen if you think this isn't good enough
