### ISSUE TITLE
Bricks don't connect

### ISSUE THREAD

**Issue by EkamjeetSingh** [leozide/leocad#494]
When I try to build a model, it goes well. But when I try to attach a brick, it stays 1 millimeter away from the brick I want to attach with. But when I try, the brick goes in the one I want to attach!
Please find a solution to this problem.

**Comment by nathaneltitane** [comment]
@EkamjeetSingh make sure you understand how to use grid snapping and increments. You should also make sure to have the previous part you are trying to snap to already selected (blue) as you are inserting the new part, the snapping will happen.

**Comment by nathaneltitane** [comment]
@EkamjeetSingh please close if this has been understood and resolved

**Comment by EkamjeetSingh** [comment]
Thank you for your response, @Nathanel Titane
The situation is resolved.

**Comment by nathaneltitane** [comment]
@EkamjeetSingh close the issue then?

**Comment by EkamjeetSingh** [comment]
Yes, @Nathanel Titane.
The issue is closed.

**Comment by nathaneltitane** [comment]
@leozide  this is resolved. close issue?
