### ISSUE TITLE
Feature request: Main model overlay window/widget

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#495]
@leozide 

When prototyping or even editing complex models and their submodels, I often find myself tabbing back to the main model entry to check changes and validate them.

It could be a great feature to have either a way to split the model space panes and select one of them to show the main build or have some kind of scalable overlay or even widget that can act as a selective model entry viewport that could always remain on top while editing.

Thoughts? 😊

Here's a quick mock-up:

OVERLAY:

![image](https://user-images.githubusercontent.com/5674757/91642554-4364d980-e9fa-11ea-804d-b1d96298cd7b.png)

WIDGET:

![image](https://user-images.githubusercontent.com/5674757/91642672-40b6b400-e9fb-11ea-9e2d-ab5caa0be7bf.png)

**Comment by rsbx** [comment]
I've always thought the **tabs** should be part of the **view** instead of the **views** being part of the **tab** as it is now. If you go this route, I'd also like a button per **view** that's always visible to hide/unhide the **view**'s **tabs**.

**Comment by nathaneltitane** [comment]
#506 might just help with this - thanks @trevorsandy

**Comment by trevorsandy** [comment]
@nathaneltitane with pleasure. 

Certainly not much heavy lifting needed to enable the viewer as a PIP widget - the viewsphere framework already in place does precisely that.

Cheers,
