### ISSUE TITLE
Rendering Issue on Debian 10

### ISSUE THREAD

**Issue by landy3580** [leozide/leocad#496]
I am having issues getting LeoCAD to render bricks properly while running Debian Buster on an HP Pavillion DV6000Z with NVIDIA GeForce Go 7200 on Nouveau NV46.  I get the same issue in LeoCAD 19.07 and 18.02 on Debian 10.05, Mint 20,  Xubuntu 20.04, and Mint 19.3.  Not an issue on Debian Stretch running LeoCAD 19.07 with the same hardware.  Any tips on how to resolve?  Thanks in advance.

![LeoCAD_Setup](https://user-images.githubusercontent.com/70454309/91647347-d700cf00-ea27-11ea-99bc-6593ce104759.png)
![LeoCAD Zoomed Out](https://user-images.githubusercontent.com/70454309/91647348-d9fbbf80-ea27-11ea-9212-f26bbf4e7d3f.png)
![LeoCAD Zoomed In](https://user-images.githubusercontent.com/70454309/91647349-dbc58300-ea27-11ea-9b15-5c49abc181b4.png)

**Comment by leozide** [comment]
Can you try the continuous build?

**Comment by rsbx** [comment]
No problems on my Debian 10 system with Intel integrated graphics.
