### ISSUE TITLE
OBJ Export orientation issue

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#497]
Exporting object files results in a rotated coordinate system upon opening with a viewer.

![image](https://user-images.githubusercontent.com/5674757/91722826-cf950f00-eb68-11ea-8060-2dd67a02c3d1.png)

VS

![image](https://user-images.githubusercontent.com/5674757/91722892-eb98b080-eb68-11ea-8d4e-8b7ddc38f5e1.png)

**Comment by leozide** [comment]
OBJ is just a file format, there's no right or wrong way to choose the orientation. The viewer you're using chose a certain orientation and other viewers have different orientations, if I change this it will "break" something else.

**Comment by nathaneltitane** [comment]
> OBJ is just a file format, there's no right or wrong way to choose the orientation. The viewer you're using chose a certain orientation and other viewers have different orientations, if I change this it will "break" something else.

Understood... just a bummer because i figured they'd be useful under windows to preview file contents using the built-in 3D Viewer.

Any chance you could have an orientation correction/selection dialog built into the exporter?

**Comment by nathaneltitane** [comment]
> OBJ is just a file format, there's no right or wrong way to choose the orientation. The viewer you're using chose a certain orientation and other viewers have different orientations, if I change this it will "break" something else.

turns out that there is no consistency in the axis orientation that leocad seems to specify for exports: at the very least, under a proper case scenario, one would expect leocad to output the model export as it is oriented in model space.

In the case of this ticket, collada respects the orientation but not wavefront - after switching from collada to wavefront due to transparency related issues on a threejs web rendering canvas i wrote for my gallery, none of the paramaters for orientation, position and scale are being respected due to the changes brought by using wavefront exports.

see here via bleander import (no odifications to file whatsoever: take note of placement, scale and orientation...)

![Screenshot_20220417_231632](https://user-images.githubusercontent.com/5674757/163749329-0f0e128a-3804-4f39-9b62-ae1ab95208f8.png)

**Comment by leozide** [comment]
All formats are exported the same way, the lack of consistency is in the importer app.

**Comment by nathaneltitane** [comment]
> All formats are exported the same way, the lack of consistency is in the importer app.

@leozide @Genome36

From a purely engineering standpoint, I understand your perspective on the matter, but if you were to look at it from a user'S perspective (with said user not knowing anything about imports, exports, standards etc) one should expect the result of the export to mimic/duplicate exactly what has been set into leocad's model space.

None of the viewers i have used thus far, when using obj/mtl specify the right orientation ('right' being the same orientation that is specified in leocad)

here is yet another example of a third party online viewer in which i have dropped an obj/mtl exported by leocad without any changes to it whatsoever

![Screenshot_20220419_155914](https://user-images.githubusercontent.com/5674757/164086045-8971f951-5d11-4f1c-8696-dd1cd6468c5b.png)

at the very least:
1 - Since orientation changes for wavefront, could there be an option to specify the up axis on export from within leocad to ensure orientation is respected?
2 - hardcode an orientation correction for wavefront to specify correct Zup axis position and have the model show exactly as it should?
