### ISSUE TITLE
Cannot export images via command line interface (non-zero exit status)

### ISSUE THREAD

**Issue by josch** [leozide/leocad#5]
Consider the following input file:

    1 4 0 0 0 1 0 0 0 1 0 0 0 1 3005.DAT

Then run:

    $ leocad file.ldr --image out.png
    QString::arg: Argument missing: "out.png" , 1
    $ echo $?
    1

The output file is blank.

There might be multiple issues here:

 - the output file being blank could just mean a wrong viewport and there is no way to specify it
 - the `QString::arg: Argument missing` error does not sound good
 - the exit status is non-zero which makes it hard to use leocad from a script

Thanks!

**Comment by leozide** [comment]
I've fixed 2 & 3, I can't get 1 to happen.

**Comment by josch** [comment]
Wow! Thanks a lot for fixing 2 & 3 so quickly!

For issue 1:

 - did you use the input file I provided?
 - did you run leocad multiple times? It happens somehow randomly.

So I run the following command `build/release/leocad --libpath /usr/share/ldraw file.ldr --image out.png` and the output is not the same every time I run it. And I don't just mean the hash. Also the pixel values are different. Here is the histogram for a working version:

    Colors: 3
    Histogram:
          39: ( 51, 51, 51,255) #333333 grey20
          25: (201, 26,  9,255) #C91A09 srgba(201,26,9,1)
      921536: (255,255,255,  0) #FFFFFF00 srgba(255,255,255,0)

It looks like this: https://mister-muffin.de/p/dg9V.png

Other times, the histogram looks like this (just one solid color filling everything):

    Colors: 1
    Histogram:
      921600: (255,255,255,  0) #FFFFFF00 graya(255,0)

On some rare occasions, I get the following output: https://mister-muffin.de/p/H-XP.png This is what looks most right to me. Even its histogram looks more interesting:

    Histogram:
        3240: ( 51, 51, 51,255) #333333 grey20
      252700: (201, 26,  9,255) #C91A09 srgba(201,26,9,1)
      665660: (255,255,255,  0) #FFFFFF00 srgba(255,255,255,0)

This is on Debian unstable with libpng-dev version 1.6.24-2.

For another way to describe the randomness, lets run the whole thing 100 times and have a look at the md5sum of the generated png. So if we run something like this:

    for i in $(seq 1 100); do rm -f out.png && leocad file.ldr --image out.png && md5sum out.png; done

Then we get (first column is the frequency that checksum was encountered):

      1 252d3da58b9ec7d341ee11fe2e90c785  out.png
      1 569263f39534328eddb8b70ba6a3e5f8  out.png
      1 5edd9c9a2aaaa01118ff8a6dfebaa9f0  out.png
      1 5f9503e8f9d36a21352a3e55892f978a  out.png
      1 67d50a0f8c46f2bc6f60d3bb1c72f67f  out.png
      1 7095009e9beba2b526b8d84b68814318  out.png
      1 70f476a18f5f767850852074c675d212  out.png
      1 7f490f4c07db2ec4ca6b09ba3f60d7fe  out.png
      1 b21fb5b5816276a066366c9a2f667d85  out.png
      1 e7306843c7027d3b20604f23bcf50e7d  out.png
      1 f17afdea4764efa0388352278e366ddb  out.png
      8 a6f385782fcf20b0f8b315037a46dc73  out.png
     17 ec42256c3c1a26a24f5cdf30b645ae17  out.png
     64 00b7e41a8cc2a443a86fa3ce8dc8861a  out.png

The last checksum is the one of the image with completely solid color. The second to last one (the one occuring 17 times) is what I'd expect the output to be and all the others are images where the model is extremely tiny.

**Comment by leozide** [comment]
I'm able to repro in release only, debug is consistently the same but in release I get a different zoom every time. I'll track it down.

**Comment by leozide** [comment]
This should be fixed now, the camera position wasn't being initialized correctly.

**Comment by josch** [comment]
Wow, that sounded like a tricky problem! Thanks a ton for fixing it!
