### ISSUE TITLE
FEATURE REQUEST: Submodel Copy

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#502]
It's a common enough task for me when I'm designing to want to make an exact copy of an existing submodel to make changes to it. Creating a new empty submodel, adding the existing submodel it, and inlining do not work for this if the existing model has all parts placed away from the coordinate system origin.

Bonus points for a recursive option.

Bonus points for an easy way to replace 1 submodel with another in a submodel without losing placement information. Easier than editing the file directly.

**Comment by nathaneltitane** [comment]
@leozide @rsbx 

This request actually underlines a point I was about to make by opening another ticket: dropping parts or model entries into a blank submodel often results in the item(s) being sent to astronomical coordinates far away from the origin.

Could there be a way to enable a 'drop to 0' feature? Pressing a modifier while pasting or inserting to ensure said item(s) land at precisely 0,0,0 ?

**Comment by rsbx** [comment]
Drop to 0,0,0 is what I'm trying to avoid. The problematic submodels for me are the ones **NOT** near 0,0,0 for a reason; often with very subtle positioning that I don't want to lose.

**Comment by nathaneltitane** [comment]
@rsbx I understood your statement correctly the first time around. It just made me think of it as an a propos, considering it may be two sides of the same coin...

**Comment by leozide** [comment]
I think for the last point you can replace a submodel with another using the properties widget and selecting the new model from the part id list.

**Comment by nathaneltitane** [comment]
> I think for the last point you can replace a submodel with another using the properties widget and selecting the new model from the part id list.

precisely what I do when models are built using the same 'entry point' (or anchor, or position)

**Comment by rsbx** [comment]
@leozide I was unaware of that capability. But having just tried it, having to scroll through a list of **many thousands** of parts to find the alternative submodel is not a real solution; exiting and editing the file is preferable to that.

**Comment by nathaneltitane** [comment]
@rsbx you can click the part field and type on keyboard the start of the name of the submodel.

I usually organize mine starting with numbers to differentiate, they always end up at the top of the list.
