### ISSUE TITLE
Bug: random step insertion on edit

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#503]
I am experiencing  a series of random step insertions as i am esiting a file and manipulating the order in which certain parts appear in the steps.

I would also like to use this opportunity  to request so.e way to ean a model file of superfluous or empty steps either on save or as an extra option withing leocad.

Thanks

**Comment by leozide** [comment]
I need steps to reproduce this

**Comment by nathaneltitane** [comment]
@leozide open mod model
Go into submodel 
Proceed to Insert new step before or after any other existing step
Select parts from step to rearrange into newly made step entey within timeline from one step to the other

**Comment by leozide** [comment]
I still can't get anything wrong

**Comment by nathaneltitane** [comment]
@leozide so if anything, could you implement a trimming function that removes empty steps and consecutive empty steps (either on save or as an option) ?that would be very nice to have as i now see that a lot of my models contain those ever since you've rewrote the step/fade implementation.
