### ISSUE TITLE
bug: windows dark mode compatibilty

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#504]
Seems the continuous builds don't match windows dark mode... any way to enforce the built in theme?

![image](https://user-images.githubusercontent.com/5674757/92971186-f814e700-f44d-11ea-8d55-572a2bd921fe.png)

**Comment by leozide** [comment]
This is your windows settings, check out notepad and it will be the same

**Comment by nathaneltitane** [comment]
![image](https://user-images.githubusercontent.com/5674757/93024067-72b24380-f5c1-11ea-8288-053df0abbdf4.png)

not sure i follow...dark mode is toggled for both windows and borders

**Comment by leozide** [comment]
scroll down, there's an option to apply the color to the title bar

**Comment by nathaneltitane** [comment]
Ah! gotcha!
