### ISSUE TITLE
enhancement: make children windows workable using wm

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#505]
to alleviate a possible qt bug and permit the actual tiling of *all* of leocad children windows,tools, etc, it would be a good idea (if possible) to make said windows fully regognizable and manipulable by window managers, including win10 aero.

when attempting to place (after undocking) any of the palettes and widgets from the main window, it is impossible to properly fit any of them without playing around and manually settin them in place, albeit imperfectly.

Wmctrl does help when linux based systems are involved but windows and even mac os may not have any savior for this one.

**Comment by nathaneltitane** [comment]
Update: @leozide have tried looking into several methods of WM control overrides but they refuse to abide lol.
Any chance you could look into this and let me know what can be done?

**Comment by nathaneltitane** [comment]
@trevorsandy would the implementation of #506 be related to this as well?

**Comment by trevorsandy** [comment]
#506 includes the following signals and slot which converts the toolbar tabs to windows when they are undocked. 

```c++
connect(mPropertiesToolBar,	SIGNAL (topLevelChanged(bool)), this, SLOT (EnableWindowFlags(bool)));
connect(mTimelineToolBar,	SIGNAL (topLevelChanged(bool)), this, SLOT (EnableWindowFlags(bool)));
connect(mPartsToolBar,		SIGNAL (topLevelChanged(bool)), this, SLOT (EnableWindowFlags(bool)));
connect(mColorsToolBar,		SIGNAL (topLevelChanged(bool)), this, SLOT (EnableWindowFlags(bool)));
connect(mPreviewToolBar,	SIGNAL (topLevelChanged(bool)), this, SLOT (EnableWindowFlags(bool)));
	
void lcMainWindow::EnableWindowFlags(bool Detached)
{
	if (Detached) {
		QDockWidget *DockWidget = qobject_cast<QDockWidget *>(sender());
		DockWidget->setWindowFlags(Qt::CustomizeWindowHint |
										  Qt::Window |
										  Qt::WindowMinimizeButtonHint |
										  Qt::WindowMaximizeButtonHint |
										  Qt::WindowCloseButtonHint);
		DockWidget->show();
	}
}
```

Cheers,

**Comment by nathaneltitane** [comment]
@trevorsandy fire 🔥
