### ISSUE TITLE
missing keyboard shortcuts and menu entries for new preview widget

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#512]
@leozide  as per usual, please add menu entries and keyboard combo options for new widget 👍 
thank you

**Comment by trevorsandy** [comment]
The keyboard shortcut to lock/unlock the preview display is Ctrl+l. I did not add a keyboard shortcut to display, the preview - acutally 2 shortcuts would be needed in this case, one to display the preview window '_Floating_' and another to display it '_Dockable_'.

Cheers,

**Comment by nathaneltitane** [comment]
@leozide bump!

**Comment by leozide** [comment]
@nathaneltitane What shortcut are you referring to? There's one for toggling the dockable preview already.
