### ISSUE TITLE
preview widget submodel selection

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#514]
@leozide 
there is currently no way to detect/select the submodel to be shown within the preview widget when an  mpd model is loaded

**Comment by trevorsandy** [comment]
From the parts selection display, select either '_In Use_' or '_Submodels_' category then double-click the desired submodel image icon.

Cheers,

**Comment by trevorsandy** [comment]
If you click on a submodel does it display in the preview ?

![Screenshot - 12_10_2020 , 18_33_58](https://user-images.githubusercontent.com/13388970/95770504-c9db2f00-0cb9-11eb-81c0-0052aa6dd380.png)

Cheers,

**Comment by nathaneltitane** [comment]
@trevorsandy @leozide 
It does: the intention  behind this ticket was to further development  the idea in possibly having a combo box or list to enable explicit model/submodel selection.

An example usage case would be that when I am working on a submodel in the main view, the changes would reflect  in the preview for the main model in the file, wherever I set the camera to look at.

**Comment by nathaneltitane** [comment]
> From the parts selection display, select either '_In Use_' or '_Submodels_' category then double-click the desired submodel image icon.
> 
> Cheers,

seems that depending on which submodel i am in, there is no way to select whatever is already in use - can some kind of model selection lock be applied? example: select the main model and keep it in preview at all times while working on different submodels in the editor main window?

**Comment by nathaneltitane** [comment]
Guess we'll keep it at that for now.
