### ISSUE TITLE
Option "highlight new parts" not working in master

### ISSUE THREAD

**Issue by ali1234** [leozide/leocad#52]
When exporting to html there is an option to highlight new parts. This used to work in 0.80 but no longer has any effect in master.

**Comment by ali1234** [comment]
I made an attempt to bring this back. My patch highlights pieces in the current step always, even while editing. There is no way to turn it off, but it could be a global option in the render preferences or something. See it here:

https://github.com/ali1234/leocad/commit/61996aea6f5d0ec237959f13e7b9e55e03a4afb3

**Comment by ali1234** [comment]
![screenshot_2017-06-20_02-47-18](https://user-images.githubusercontent.com/651970/27312867-d5016780-5562-11e7-97d1-77a702bea781.png)

**Comment by leozide** [comment]
Thanks for the patch, I've merged it and made it only active when the highlight option is enabled.

**Comment by ali1234** [comment]
Thanks. Could you please re-enable the command line switch for this too? It's still commented out at the moment.

**Comment by leozide** [comment]
It's enabled again.
