### ISSUE TITLE
PATCH: Command-line options to use leocad as an external renderer

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#521]
The attached patch, against 5c5e2d88, adds command-line options to use leocad as an external/scripted renderer.

The new options are:

- --CameraSpec: Specifies camera position, target, up, field of view, and near & far clipping plane distances.
See `common/lc_application.cpp` for details.
- --FadeSteps: Render parts from prior steps faded
- --no-FadeSteps: Do not render parts from prior step faded
- --FadeStepsColor <rgba>: Renderinng color for prior step parts (#AARRGGBB)
- --no-highlight: Do not highlight pieces in the steps they appear
- --highlightColor: Renderinng color for highlighted parts (#AARRGGBB)
- --AASamples <count>: AntiAliasing sample size (1, 2, 4, or 8)

[patch.txt](https://github.com/leozide/leocad/files/5396571/patch.txt)

**Comment by rsbx** [comment]
Bump

**Comment by leozide** [comment]
Thanks for the patch, I split the fov and z planes from the camera spec because they may be useful in other cases.

**Comment by rsbx** [comment]
After some quick testing, I have the following comments:

- The --fov & --zplanes options are remembered and affect later use. My original patch dealt with this by resetting FOV in lcCamera::SetViewpoint and lcCamera::SetAngles to the default of 30. I did not handle resetting the zplanes. An easy way (that does not require the user to know magic constants) to reset these settings is needed. However, having a way to set the FOV for interactive use is a nice side effect.
- The --fov option without setting the camera should do a zoomExtents call.
- Option parse failures are ignored (with a warning). My patch caught them and returned a failure exit code. Since these new command options are primarily for scripted invocation, erroring out on parse failures is a better choice.
- I believe that --camera-position should use LDRAW coords instead of LeoCad coords because the option is primarily useful for scripted operation and the other coords used in that situation are LDRAW coords in the .ldr or .mpd file.

**Comment by leozide** [comment]
- I saw that you were resetting the fov but I thought that wasn't a good place to do it because it would trigger while doing other actions like clicking on the view sphere.
- I changed the order now, so the zoom extents from setting the viewpoint will include the final fov.
- That's true but it was inconsistent, only the new options returned errors.
- I've added --camera-position-ldraw.

**Comment by rsbx** [comment]
- Fair enough. A reset solution for interactive use is still need and adding that while still keeping the ability to set the FOV for interactive is use is beyond me. I don't see a real use for setting the Z-planes for interactive use, though.
- :-)
- I noticed that too but decided to go with the more focused patch and if it was accepted to create a patch covering the other options. If you don't get to it first, I'll create a patch to error on syntax violations for all options.
- Both worlds!

**Comment by rsbx** [comment]
I created a patch to do the option syntax checking; see #550.
