### ISSUE TITLE
Unexplained Image artifacts in small but not large images of the same model

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#524]
I'm having a problem of image artifacts in smaller images of an, admittedly, huge model that I do **not** get in larger images. The simple `bleed_demo.ldr` model, below, will reliably recreate problem in a leocad 'home' view on my systems. The artifacts appear to be the underside studs of the 6x6 while tiles bleeding through the tile top. My initial thought was that I'd reached the z-buffer precision limit but that doesn't explain why it only happens with smaller images and not larger images of the same view.

In an attempt to explore the z-buffer precision theory, I tried changing the `zNear` and `zFar` in `View::GetProjectionMatrix` to be a tighter bounds to the model view with no apparent effect.

I'd like to know what's going on since it's counter intuitive for it to happen in smaller but not larger images.

Steps to reproduce:

0. My system is Debian 10 with a 1080 tall screen and the leocad main view uses most of that height.
1. Open the `bleed_demo.ldr` model and display using a large view pane from the `home` viewpoint with a `perspective` projection and edge-lines set to 1. There are no unexplained images artifacts.
2. Split the view horizontally. Both views appear to have underside studs of the 6x6 while tiles bleeding through the tile top.
3. This effect can also be reproduced using the `-i <image>` option from the command-line; try a 2000x2000 image and a 500x500 image.

> 0 
0 Name: bleed_demo.ldr
0 Author: RSBX
1 4 500 0 -500 1 0 0 0 1 0 0 0 1 3024.dat
1 4 500 -3000 -500 1 0 0 0 1 0 0 0 1 3024.dat
1 4 500 0 500 1 0 0 0 1 0 0 0 1 3024.dat
1 4 500 -3000 500 1 0 0 0 1 0 0 0 1 3024.dat
1 4 -500 0 -500 1 0 0 0 1 0 0 0 1 3024.dat
1 4 -500 -3000 -500 1 0 0 0 1 0 0 0 1 3024.dat
1 4 -500 0 500 1 0 0 0 1 0 0 0 1 3024.dat
1 4 -500 -3000 500 1 0 0 0 1 0 0 0 1 3024.dat
1 15 0 -8 240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 120 -8 240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 240 -8 240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -120 -8 240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -240 -8 240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 0 -8 120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 120 -8 120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 240 -8 120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -120 -8 120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -240 -8 120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 0 -8 0 1 0 0 0 1 0 0 0 1 10202.dat
1 15 120 -8 0 1 0 0 0 1 0 0 0 1 10202.dat
1 15 240 -8 0 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -120 -8 0 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -240 -8 0 1 0 0 0 1 0 0 0 1 10202.dat
1 15 0 -8 -120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 120 -8 -120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 240 -8 -120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -120 -8 -120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -240 -8 -120 1 0 0 0 1 0 0 0 1 10202.dat
1 15 0 -8 -240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 120 -8 -240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 240 -8 -240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -120 -8 -240 1 0 0 0 1 0 0 0 1 10202.dat
1 15 -240 -8 -240 1 0 0 0 1 0 0 0 1 10202.dat

**Comment by leozide** [comment]
Some pictures would help

**Comment by rsbx** [comment]
Images attached:

500x500
![bleed500](https://user-images.githubusercontent.com/533684/96377378-65a1ea80-1153-11eb-8cfe-b9c979ab05ec.png)

2000x2000
![bleed2000](https://user-images.githubusercontent.com/533684/96377379-663a8100-1153-11eb-8d71-d84ccc7dbba1.png)

**Comment by rsbx** [comment]
And here's a screenshot of it in leocad w/ multiple views:
![bleed](https://user-images.githubusercontent.com/533684/96378028-6b99ca80-1157-11eb-94b2-e25ed8f80546.png)

**Comment by rsbx** [comment]
Turned off the edge lines and it cleared. So the "what" is answered but 
not the "why" and the "can it be fixed?".

**Comment by leozide** [comment]
This is because OpenGL draws lines in screen space, to improve this I'd need to use triangles or some sort of post processing to draw lines.

**Comment by rsbx** [comment]
So why does it happen with smaller images when it doesn't happen with 
larger images? That's the counter intuitive part.

**Comment by leozide** [comment]
1 pixel in 500x500 covers more of the world than in 2000x2000

**Comment by rsbx** [comment]
True but not really an explanation of why the lines bleed through in 
smaller images. It's acting like z-depth precision is reduced in smaller 
images compared to larger images. That's the part that doesn't make any 
sense to me.

**Comment by leozide** [comment]
This has nothing to do with zbuffer, it's the lines remaining the same while the triangles shrink

**Comment by rsbx** [comment]
How are the lines placed relative to the quad/triangles they're related 
to? My impression is that the z-buffer is used for lines also.

Possibly related: how are decorated surfaces handled?

**Comment by leozide** [comment]
Lines are drawn using the same coordinates as quads but with depth bias enabled.

Most decorated surfaces remove the base triangles they replace so there's no z fighting.
