### ISSUE TITLE
Customising LeoCAD from Build

### ISSUE THREAD

**Issue by Aiyush-G** [leozide/leocad#528]
Hi there, 

I am a student and would like to modify LeoCAD to create a similar application but with different bricks etc... However, I don't know how to customise certain things like the LeoCAD icon and application name. Other things that I would like to do include changing the menu text. 

<img width="442" alt="image" src="https://user-images.githubusercontent.com/55917505/98446465-7cfe4300-2115-11eb-88fa-61b579e6f709.png">

^^^ I would like to change the text here (for example) and for this specific example also change the link that it leads too ^^^ 

Another example would be here: 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/55917505/98446490-9e5f2f00-2115-11eb-86ae-c25b62593731.png">

^^^ I would like to change this to attribute LeoCAD but also include my own text^^^ 

I hope that this explains everything that I mean.

Thanks

**Comment by trevorsandy** [comment]
The changes you would like to make may not be trivial if you are not conformable with the Qt project framework and navigating the source code.

Anyway, you'll need to add your icons appropriately and edit these files to enable the changes you describe above:

Applicaiton name and icon (Windows): https://github.com/leozide/leocad/blob/master/leocad.pro 
Application name and icon (macOS): https://github.com/leozide/leocad/blob/master/qt/Info.plist
Applicaiton name and icon (Linux): https://github.com/leozide/leocad/blob/master/qt/leocad.desktop
About name and icon: https://github.com/leozide/leocad/blob/master/qt/lc_qaboutdialog.ui 
Additional about text: https://github.com/leozide/leocad/blob/master/qt/lc_qaboutdialog.cpp
Help, Homepage, BugReport: https://github.com/leozide/leocad/blob/master/common/lc_mainwindow.cpp
Help, Homepage, BugReport: https://github.com/leozide/leocad/blob/master/common/lc_commands.cpp

Cheers,

**Comment by Aiyush-G** [comment]
Cheers, I am having an issue with changing on macOS (my platform only one I am trying at the moment). Here is my Info.plist file and I am experimenting changing LeoCAD to SoundCAD and then will focus on changing the icon after I have this working:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>lcd</string>
				<string>soundCAD</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>leocad_document.icns</string>
			<key>CFBundleTypeMIMETypes</key>
			<array>
				<string>application/vnd.soundCAD</string>
			</array>
			<key>CFBundleTypeName</key>
			<string>LeoCAD Project</string>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSTypeIsPackage</key>
			<false/>
			<key>LSHandlerRank</key>
			<string>Owner</string>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>ldr</string>
				<string>dat</string>
				<string>mpd</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>leocad_document.icns</string>
			<key>CFBundleTypeMIMETypes</key>
			<array>
				<string>application/x-ldraw</string>
				<string>application/x-multi-part-ldraw</string>
				<string>application/x-ldlite</string>
			</array>
			<key>CFBundleTypeName</key>
			<string>LDraw Document</string>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>LSTypeIsPackage</key>
			<false/>
		</dict>
	</array>
	<key>CFBundleExecutable</key>
	<string>SoundCAD</string>
	<key>CFBundleIconFile</key>
	<string>leocad.icns</string>
	<key>CFBundleIdentifier</key>
	<string>com.leozide.leocad</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>LCAD</string>
	<key>CFBundleVersion</key>
	<string>19.07.1</string>
	<key>CFBundleDisplayName</key>
	<string>SoundCAD</string>
	<key>CFBundleName</key>
	<string>SoundCAD</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
`

But the name remains as LeoCAD, I am running this via QTCreator, clicking build (hammer) and then run (green arrow).

Cheers
Aiyush

**Comment by trevorsandy** [comment]
set `TARGET = SoundCAD` in leocad.pro

Cheers,

**Comment by Aiyush-G** [comment]
Hi @trevorsandy thanks for the response, where do I add this?

Cheers
Aiyush

**Comment by Aiyush-G** [comment]
@trevorsandy Thanks, I have now gotten all of the above to work, could you help me with one more thing? I would like to add a custom .dat to a custom panel here: 
<img width="343" alt="image" src="https://user-images.githubusercontent.com/55917505/98465802-6c0c0b00-21c3-11eb-8d1d-bbc2f6e5cc94.png">

E.g. I would like a panel called Audio with the model horn.dat 

How would I achieve this? 

Thanks

**Comment by trevorsandy** [comment]
Create a new category from the Preferences dialogue - for example: 

`Audio=^%Audio`

Your parts should follow the LDraw .dat file syntax convention so the category can be properly assigned to your custom parts - for example:

```
0 Audio My First Custom Audio Piece
0 Name: 100000audio.dat
0 Author: Me [MeToo]
0 !LDRAW_ORG Part UPDATE 2020-11
0 !LICENSE <Your distribution license here>
...
```


If you are unsure about the category expression syntax, you can export the categories and review the content.

![Screenshot - 08_11_2020 , 14_35_19](https://user-images.githubusercontent.com/13388970/98466407-aaa7c280-21cf-11eb-8f4b-0aad562d59e6.png)

Cheers,

**Comment by Aiyush-G** [comment]
Ok, thanks I will try that. Also, I have converted .stl to .dat successfully and opened in LeoCAD but it isn't to scale. Any idea why this is, or what scale factor I need to increase by (is there a way to see the physical size of a model in LeoCAD either).

Cheers

**Comment by trevorsandy** [comment]
Download stl2dat source from http://marc.klein.free.fr/lego/stl2dat/stl2dat.html and take a look at the Scale option. 

Perhaps you can apply the algorithm to your conversion script. Alternatively, you could build stl2dat from source for your platform - it's written in `c` I believe. This way, you can use the many conversion options available to tweak your conversion.

Cheers,

**Comment by Aiyush-G** [comment]
I think that is beyond my skillset :( Could you guide me how to build it? It would be really appreciated as I have spent the last 60 minutes trying to find a workaround.

Thanks
Ag

**Comment by Aiyush-G** [comment]
Sorry for the bother @trevorsandy , Is there a way to set custom snapping on custom parts?

Cheers, 
Aiyush

**Comment by trevorsandy** [comment]
> Is there a way to set custom snapping on custom parts?

I'm not aware of any user-configurable behaviour that does this. I imagine you would have to customize the code.

Cheers,
