### ISSUE TITLE
LeoCAD just crashed

### ISSUE THREAD

**Issue by tythera** [leozide/leocad#529]
Dump Summary
------------
Dump File:	leocad.dmp : C:\Users\T8L2\AppData\Local\Temp\leocad.dmp
Last Write Time:	11/9/2020 9:30:51 PM
Process Name:	LeoCAD.exe : C:\Program Files (x86)\LDraw\LeoCAD\LeoCAD.exe
Process Architecture:	x86
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	10.0.19042
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
LeoCAD.exe	C:\Program Files (x86)\LDraw\LeoCAD\LeoCAD.exe	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.2.19041.610
kernel32.dll	C:\Windows\System32\kernel32.dll	6.2.19041.546
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.2.19041.572
comdlg32.dll	C:\Windows\System32\comdlg32.dll	6.2.19041.546
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.19041.546
wininet.dll	C:\Windows\System32\wininet.dll	11.0.19041.546
combase.dll	C:\Windows\System32\combase.dll	6.2.19041.572
ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	6.2.19041.546
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.2.19041.610
SHCore.dll	C:\Windows\System32\SHCore.dll	6.2.19041.610
user32.dll	C:\Windows\System32\user32.dll	6.2.19041.610
win32u.dll	C:\Windows\System32\win32u.dll	6.2.19041.610
gdi32.dll	C:\Windows\System32\gdi32.dll	6.2.19041.546
gdi32full.dll	C:\Windows\System32\gdi32full.dll	6.2.19041.572
msvcp_win.dll	C:\Windows\System32\msvcp_win.dll	6.2.19041.546
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.2.19041.546
shell32.dll	C:\Windows\System32\shell32.dll	6.2.19041.610
comctl32.dll	C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.488_none_11b1e5df2ffd8627\comctl32.dll	6.10.19041.488
ole32.dll	C:\Windows\System32\ole32.dll	6.2.19041.546
imm32.dll	C:\Windows\System32\imm32.dll	6.2.19041.546
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.2.19041.546
advapi32.dll	C:\Windows\System32\advapi32.dll	6.2.19041.610
winspool.drv	C:\Windows\System32\winspool.drv	6.2.19041.546
winmm.dll	C:\Windows\System32\winmm.dll	6.2.19041.546
sechost.dll	C:\Windows\System32\sechost.dll	6.2.19041.546
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.2.19041.546
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.2.19041.546
opengl32.dll	C:\Windows\System32\opengl32.dll	6.2.19041.546
glu32.dll	C:\Windows\System32\glu32.dll	6.2.19041.546
CRYPTBASE.DLL	C:\Windows\System32\CRYPTBASE.DLL	6.2.19041.546
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.2.19041.546
windows.storage.dll	C:\Windows\System32\windows.storage.dll	6.2.19041.610
wldp.dll	C:\Windows\System32\wldp.dll	6.2.19041.546
profapi.dll	C:\Windows\System32\profapi.dll	6.2.19041.546
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.2.19041.546
uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.2.19041.610
DWrite.dll	C:\Windows\System32\DWrite.dll	6.2.19041.546
edputil.dll	C:\Windows\System32\edputil.dll	6.2.19041.546
msctf.dll	C:\Windows\System32\msctf.dll	6.2.19041.572
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10941.16384
dataexchange.dll	C:\Windows\System32\dataexchange.dll	6.2.19041.546
d3d11.dll	C:\Windows\System32\d3d11.dll	6.2.19041.546
dcomp.dll	C:\Windows\System32\dcomp.dll	6.2.19041.546
dxgi.dll	C:\Windows\System32\dxgi.dll	6.2.19041.546
twinapi.appcore.dll	C:\Windows\System32\twinapi.appcore.dll	6.2.19041.546
AppXDeploymentClient.dll	C:\Windows\System32\AppXDeploymentClient.dll	6.2.19041.572
ig9icd32.dll	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a086f01cc7be643a\ig9icd32.dll	27.20.100.8681
dwmapi.dll	C:\Windows\System32\dwmapi.dll	6.2.19041.546
igdgmm32.dll	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a086f01cc7be643a\igdgmm32.dll	27.20.100.8681
igc32.dll	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a086f01cc7be643a\igc32.dll	27.20.100.8681
powrprof.dll	C:\Windows\System32\powrprof.dll	6.2.19041.546
umpdc.dll	C:\Windows\System32\umpdc.dll	0.0.0.0
igdml32.dll	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a086f01cc7be643a\igdml32.dll	27.20.100.8681
textinputframework.dll	C:\Windows\System32\textinputframework.dll	6.2.19041.610
CoreUIComponents.dll	C:\Windows\System32\CoreUIComponents.dll	6.2.19041.546
CoreMessaging.dll	C:\Windows\System32\CoreMessaging.dll	6.2.19041.546
ntmarta.dll	C:\Windows\System32\ntmarta.dll	6.2.19041.546
WinTypes.dll	C:\Windows\System32\WinTypes.dll	6.2.19041.572
WindowsCodecs.dll	C:\Windows\System32\WindowsCodecs.dll	6.2.19041.546
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.2.19041.546
thumbcache.dll	C:\Windows\System32\thumbcache.dll	6.2.19041.546
dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.2.19041.488
dbgcore.dll	C:\Windows\System32\dbgcore.dll	6.2.19041.546
version.dll	C:\Windows\SysWOW64\version.dll	6.2.19041.546
psapi.dll	C:\Windows\SysWOW64\psapi.dll	6.2.19041.546
wow64cpu.dll	C:\Windows\System32\wow64cpu.dll	10.0.19041.546

**Comment by leozide** [comment]
Can you attach the dump? C:\Users\T8L2\AppData\Local\Temp\leocad.dmp
