### ISSUE TITLE
Stud Logo are not working

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#537]
- **Version:** `LeoCAD-Linux-e52ea0a-x86_64.AppImage`

Tried with LeoCAD's built-in parts & with external official LDraw's [`complete.zip`](https://github.com/Symbian9/AWESOME-LDraw#ldraw-official-and-unofficial-parts)

![pic](https://i.imgur.com/CYIeNFs.png)

**Comment by leozide** [comment]
do you have ldrawunf.zip?

**Comment by trevorsandy** [comment]
I originally implemented a check that would disable the stud logo option if the unofficial archive  (or disk library if using that option) was not found but I removed it because LPub3D will always package and load this archive. However, it looks like this update could be good for LeoCAD as LeoCAD does not require ldrawunf.zip and users may not automatically download it.

Cheers,

**Comment by Symbian9** [comment]
> do you have `ldrawunf.zip`?

I just tried LeoCAD set to use external `complete.zip` (+ downloaded `ldrawunf.zip` in same folder where `complete.zip` stored) — Stud Logo now works!

BUT the issue is here is that fact that LeoCAD should detect if there are no Stud Logo parts in loaded libraries are not present then "Preferences > Stud Logo" option should be deactivated.

Otherwise LeoCAD should has built-in stud parts too and use it if there are no external `ldrawunf.zip` loaded on start.

**Comment by leozide** [comment]
I'll disable the option, I can't include the stud logo files from ldrawunf.zip because of their license.

**Comment by Symbian9** [comment]
> I'll disable the option, I can't include the stud logo files from `ldrawunf.zip`

@leozide, Hold on!

Why just not add option to detect is there are studs logo files (`.dat` files with specific names) inside loaded parts libraries or not:

- If there are stud logo parts loaded — Stud Logo option should be available in LeoCAD preferences window;
- If there are no stud logo parts loaded — Stud Logo option should be not shown in LeoCAD preferences window.
