### ISSUE TITLE
relative transform broken on latest builds

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#540]
triggering the relative transform (either via combo or menu) after selecting identical or similar parts does not result in the operation making each part move according to it's own orientation.

**Comment by leozide** [comment]
Works for me

**Comment by nathaneltitane** [comment]
> Works for me

OK - so could it have anything to do with how combo keystrokes are interpreted by a VNC?
Also, it may be relative to keyboard combo duplicates not being managed properly? I may have a dup but haven't checked just yet... see #517

**Comment by leozide** [comment]
Maybe, I think the biggest problem here is that there's no way to see if independent transforms are enabled or not.

**Comment by nathaneltitane** [comment]
> Maybe, I think the biggest problem here is that there's no way to tell if independent transforms are enabled or not.

so can we add a status bar indicator?

#517 is still relevant in the fact that dupes arent monitored either.

**Comment by nathaneltitane** [comment]
@leozide I may be mistaken but i was referring to this function #430

**Comment by nathaneltitane** [comment]
::bump::

**Comment by nathaneltitane** [comment]
@leozide looked into shortcuts etc didn'T see any issue son my side - potential regression.

**Comment by leozide** [comment]
It's working for me, you can try resetting the shortcuts and assigning a new one.

**Comment by nathaneltitane** [comment]
@leozide sorry, mustve been some kind of glitch: I had to remove the assignment, assign a letter a key without modifier accept and then re-edit the combo back to modifier+key for it to work.

All good now.
