### ISSUE TITLE
BUG? Remove step combo does not function?

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#547]
The remove step keyboard combo does not seem to be associated with the timeline step incrementation:

Click on timeline
Select step
Use keyboard shortcut combo to remove step - no difference

**Comment by leozide** [comment]
This is working for me, the shortcut removes the current step when I use it.

**Comment by nathaneltitane** [comment]
Probably linked to the issue I previously had with the local transforms, will check it out.
