### ISSUE TITLE
BUG: Home view does not zoom to model boundary

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#556]
Resetting the Home view does not bring camera back to proper model boundary - model is zoomed in considerably.

See attached, before and after home toggle.

![Screenshot_20201216-171850_VNC Viewer.png](https://user-images.githubusercontent.com/5674757/102413368-ce2a0e00-3fc2-11eb-8b27-5e7b4f2ac1d1.png)

![Screenshot_20201216-171858_VNC Viewer.png](https://user-images.githubusercontent.com/5674757/102413386-d5e9b280-3fc2-11eb-88f1-36d329c46132.png)

**Comment by leozide** [comment]
Works for me, is this only happening with this particular model?

**Comment by nathaneltitane** [comment]
Seems like it...

**Comment by leozide** [comment]
Do you mind sharing the model?

**Comment by nathaneltitane** [comment]
rv-9625-titan-rotor.mpd
<https://drive.google.com/file/d/1zJ26uKSNKJRJ1nhl7ncoJR8rNiTWu-IJ/view?usp=drivesdk>

**Comment by leozide** [comment]
It zooms in correctly for me:

![image](https://user-images.githubusercontent.com/9685066/102673325-859c5d00-4148-11eb-90b5-6769fab95a6d.png)

**Comment by nathaneltitane** [comment]
@leozide no clue then... I'll let you know if it happens again
