### ISSUE TITLE
Small update

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#564]
isNull()  for QSize mPreferredSize in lcViewWidget always evaluates to false because width and height initializes to (-1, -1). isNull() will only evaluate to true if these values are 0. 

![Screenshot - 21_12_2020 , 14_37_02](https://user-images.githubusercontent.com/13388970/102783457-40239e00-439b-11eb-81bc-0ec2b1dcaf66.png)

isEmpty() evaluates to true if width and height is less than or equal to 0.

Cheers,

**Comment by leozide** [comment]
Good catch.
