### ISSUE TITLE
ENHANCEMENT: Toolbar button the toggle the base grid & studs

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#567]
Doing this via the menus is 6 clicks.

**Comment by leozide** [comment]
You can assign shortcuts if you want. I don't think these are used enough to get a toolbar button but maybe a menu entry is ok.

**Comment by rsbx** [comment]
It's not clear to me how to assign shortcut to toggle them and the menu 
method is 6 mouse clicks.

This is something I do annoying frequently with some projects I work on. 
Particularly when switching between the different sub-models.

**Comment by leozide** [comment]
I could swear there was one, I'll have to add it.

**Comment by leozide** [comment]
I've added shortcut support to toggle the grid. To assign a shortcut:

- Go to Preferences -> Keyboard
- Type grid in the search field
- Select Grid from the list
- Click on the 'Key sequence' field
- Press the shortcut you want to use (ie Ctrl+G)
- Click Assign
- Click Ok

**Comment by rsbx** [comment]
Just the grid or both the grid and (grid) studs together? The later is 
what I'm looking for. I'll test after xmas.

**Comment by rsbx** [comment]
Works!

You might want to change keyboard preferences text form 'Grid' to 'Base Grid' since it's toggling what's checked in the Preferences -> Interface -> 'Base Grid' section.
