### ISSUE TITLE
Preview behaviour

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#571]
[Derive preview from view](https://github.com/leozide/leocad/commit/e27b2359361684ee622be6749cf5a381baa63497) launches the view context menu for preview - presenting menu items that are not applicable to the preview context. 

Additionally, show axes and viewsphere preferences are no longer available but the options remain in the Preferences dialogue.

Cheers,

**Comment by trevorsandy** [comment]
View overlays are rendered in Preview.

![Screenshot - 26_12_2020 , 20_59_41](https://user-images.githubusercontent.com/13388970/103158398-9179c600-47bd-11eb-9cd1-05dc4e3ec786.png)

**Comment by trevorsandy** [comment]
Preview viewsphere preference is ignored. Display is always enabled.

![Screenshot - 27_12_2020 , 00_45_16](https://user-images.githubusercontent.com/13388970/103161074-23dd9200-47dd-11eb-873b-b2dbe67a12dc.png)

Cheers,

**Comment by leozide** [comment]
These should be fixed now.
