### ISSUE TITLE
LeoCAD crashing upon loading the animals list

### ISSUE THREAD

**Issue by awambawamb** [leozide/leocad#576]
Hello,

straight to the point: I open LeoCAD, select "animals" from the menu on the right, and LeoCAD crashes.

Win10 Pro, Nvidia Quadro k2100m

dump file on my google drive: https://drive.google.com/file/d/1BjHWX9v_V__5t1E2G8ua8xADU3hegMXH/view?usp=sharing

Cheers

**Comment by leozide** [comment]
This crash has already been fixed in a87a19f9c95c72e7460beb5293424f33dfee7f36, you can download the continuous build from https://github.com/leozide/leocad/releases/tag/continuous/.

**Comment by awambawamb** [comment]
I see!
I've installed LeoCAD using the all-in-one installer LDraw_AIOI_2020-02_setup_32bit_v1 from Ldraw.org
