### ISSUE TITLE
Warning sharing GL contexts

### ISSUE THREAD

**Issue by leozide** [leozide/leocad#577]
When using MSAA:

Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.

**Comment by j6t** [comment]
Maybe a related issue: When Anti-aliasing is enabled, the UI is *very* slow. For example, click the *File* menu and move the mouse over the menu quickly: the highlighted entry stays behind.

This issue happens only since commit 4e6cbca31c5260c (Switch to QOpenGLWidget).

**Comment by leozide** [comment]
I'm not seeing any performance changes, can you post the contents of your About Dialog?

**Comment by j6t** [comment]
This is the About box:

> Qt Version 5.9.7 (compiled with 5.9.7)
> 
> OpenGL Version 3.3.0 NVIDIA 340.108 (GLSL 3.30 NVIDIA via Cg compiler)
> GeForce 210/PCIe/SSE2 - NVIDIA Corporation
> 
> Color Buffer: 24 bits
> Depth Buffer: 24 bits
> Stencil Buffer: 0 bits
> 
> GL_ARB_vertex_buffer_object extension: Supported
> GL_ARB_framebuffer_object extension: Supported
> GL_EXT_framebuffer_object extension: Not supported
> GL_EXT_blend_func_separate: Supported
> GL_EXT_texture_filter_anisotropic extension: Supported (max 16)

I'm on openSUSE Linux 15.1 using the Nvidia driver.

I've also compiled on Windows/MinGW64:

> Qt Version 5.15.2 (compiled with 5.15.2)
> 
> OpenGL Version 4.6.0 NVIDIA 432.00 (GLSL 4.60 NVIDIA)
> GeForce GTX 1060 6GB/PCIe/SSE2 - NVIDIA Corporation
> 
> Color Buffer: 32 bits
> Depth Buffer: 24 bits
> Stencil Buffer: 8 bits
> 
> Buffers: Supported
> Shaders: Supported
> Framebuffers: Supported
> TexImage2DMultisample: Supported
> BlendFuncSeparate: Supported
> Anisotropic: Supported (max 16)


Here, I do not see the slow-down. If the slow-down is related to OpenGL, then that is not a surprise as on Windows I have full hardware support. On Linux, OTOH, a lot of OpenGL seems to be done in software (rendering is slow for large models).

Let me repeat: the issue I want to bring to attention is *not* slower rendering of models, the issue is a slower user-interface. But it looks like I have to investigate myself. Nevertheless, a hint where the cause could be would be appreciated.

**Comment by j6t** [comment]
Looks like fixing this case will not change my issue. I hard-coded the `QSurfaceFormat::setDefaultFormat()` call before `lcApplication` is created (as the docs suggest), but it does not make a difference. The UI remains slow.

**Comment by leozide** [comment]
I can only speculate to what could be happening but would it be possible to compile with a newer Qt version to rule out any bugs on their side?

You could also try calling setFormat on the widgets instead of changing the default QSurfaceFormat so it doesn't affect the UI surfaces.

**Comment by j6t** [comment]
Will do and report back, but it'll take a while (need new hardware).

**Comment by j6t** [comment]
Just for completeness and to let you know: I've now new hardware and an updated OS (openSUSE 15.2), and I do not observe the slowness anymore. The About box says:

> Qt Version 5.12.7 (compiled with 5.12.7)
> 
> OpenGL Version 4.5 (Compatibility Profile) Mesa 19.3.4 (GLSL 4.50)
> Radeon 550 Series (POLARIS12, DRM 3.40.0, 5.10.12-1.ga3c8888-default, LLVM 9.0.1) - X.Org
> 
> Color Buffer: 24 bits
> Depth Buffer: 0 bits
> Stencil Buffer: 0 bits
> 
> Buffers: Supported
> Shaders: Supported
> Framebuffers: Supported
> BlendFuncSeparate: Supported
> Anisotropic: Supported (max 16)
