### ISSUE TITLE
Unable to render image from the command line

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#579]
Works at commit 2ccdc85f (prior to Switch to "QOpenGLWidget").

The simplest example invocation would be of the form:
  leocad -i foo.png bar.ldr

I'm trying to retest some of the command line rendering options that I care about.

**Comment by leozide** [comment]
It's working for me now.

**Comment by rsbx** [comment]
Sorry. I had tested it but forgot to close the issue.
