### ISSUE TITLE
Segfaults with commit 1367a5d6

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#583]
Attempting to open a project via File -> Open segfaults immediately. However, if I specify the project from the command line there is no immediate segfault. Rendering images from the command line works.

Testing performed on a Debian 10 (updated) VM.

**Comment by rsbx** [comment]
Also happens on the host Debian 10 (updated) system.

And the following warning happens if AA is enabled:
> Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.

**Comment by leozide** [comment]
It's not crashing for me, do you have a callstack?

**Comment by rsbx** [comment]
No but if you show me how to do a full qmake/make with debugging, I'll 
see what I can get for you.

**Comment by rsbx** [comment]
It seems that you enable debugging info normally so the attached file is from a valgrind run on the VM. Hope it helps.

[trace.gz](https://github.com/leozide/leocad/files/5752144/trace.gz)

**Comment by rsbx** [comment]
Note: when run under valgrind, it did NOT crash. But wasn't really usable either.

**Comment by rsbx** [comment]
After reconfiguring the system to generate core files and installing gdb, here's the stack trace:

#0  0x000055bb0e4a5003 in lcTexture::Upload (this=0x55bb12114a20, Context=Context@entry=0x55bb112a4930) at common/lc_texture.cpp:207
#1  0x000055bb0e43bc6b in lcPiecesLibrary::UploadTextures (this=0x55bb1009df30, Context=0x55bb112a4930) at common/lc_library.cpp:1518
#2  0x000055bb0e497a64 in lcScene::Draw (this=0x7ffd8985eb50, Context=0x55bb112a4930) at common/lc_application.h:126
#3  0x000055bb0e49045e in lcPartSelectionListModel::DrawPreview (this=0x55bb110dabd0, InfoIndex=0) at common/lc_partselectionwidget.cpp:435
#4  0x000055bb0e4907ac in lcPartSelectionListModel::RequestPreview (this=0x55bb110dabd0, InfoIndex=<optimized out>) at common/lc_partselectionwidget.cpp:366
#5  0x000055bb0e4907f1 in lcPartSelectionItemDelegate::paint (this=0x55bb1108c940, Painter=0x7ffd8985edd0, Option=..., Index=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h:62
#6  0x00007ff7d71b47db in QListView::paintEvent(QPaintEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ff7d6f6e4d8 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ff7d7011cde in QFrame::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ff7d71831eb in QAbstractItemView::viewportEvent(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ff7d63ca19b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ff7d6f304b1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ff7d6f37970 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ff7d63ca489 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ff7d6f670ca in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ff7d6f67987 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ff7d6f3fa37 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ff7d6f3fe19 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ff7d6f569d5 in QWidgetPrivate::syncBackingStore() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ff7d6f6e608 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ff7d7074dd4 in QMainWindow::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ff7d6f304c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ff7d6f37970 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ff7d63ca489 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ff7d63cd46b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ff7d641c103 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ff7d547ef2e in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ff7d547f1c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ff7d547f25c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ff7d641b727 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ff7d2f4e491 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#31 0x00007ff7d63c915b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ff7d63d1132 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x000055bb0e3faa75 in main (argc=<optimized out>, argv=<optimized out>) at qt/qtmain.cpp:196

**Comment by leozide** [comment]
80adb54acfc5a42462e4e84ba17e36ee2d2c4f4b

**Comment by rsbx** [comment]
Concur!
