### ISSUE TITLE
Stud style of pieces used in the current model does not change sometimes

### ISSUE THREAD

**Issue by j6t** [leozide/leocad#608]
After switching the stud style to _Plain_ while pieces are in use in the model, switch to a different style does not change the style of the used pieces anymore.

1. Go to _Preferences_, _Rendering_. Switch to _Rounded Top Logo_.
2. Insert a Brick 1 x 1 in an empty model.
3. Observe the correct style.
4. Go to _Preferences_, _Rendering_. Switch to _Plain_.
5. Observe the changed style in the model and in the Parts list.
6. Go to _Preferences_, _Rendering_. Switch to _Rounded Top Logo_.
7. Observe that the style was not changed for the piece in the model nor in the Parts list, but it was changed for other pieces in the Parts list.
8. Repeat steps 2 to 7, but with a type of piece that is not in the model so far, for example, a Brick 1 x 1 Round with Solid Stud.

Clearly, the style should have been changed after the last operation.

This is a screenshot before step 4 in the second round:
![image](https://user-images.githubusercontent.com/14810926/105608192-ca985c80-5da2-11eb-8b90-d3ce7ce63e7f.png)

Version:
 - OS: openSUSE 15.1
 - LeoCAD Version 21.01, commit 0c03fd3feab9e8 (Fixed crash using the --stud-style option)

About box:
> Qt Version 5.9.7 (compiled with 5.9.7)
> 
> OpenGL Version 3.3.0 NVIDIA 340.108 (GLSL 3.30 NVIDIA via Cg compiler)
> GeForce 210/PCIe/SSE2 - NVIDIA Corporation
>
> Color Buffer: 24 bits
> Depth Buffer: 24 bits
> Stencil Buffer: 0 bits
> 
> Buffers: Supported
> Shaders: Supported
> Framebuffers: Supported
> BlendFuncSeparate: Supported
> Anisotropic: Supported (max 16)

**Comment by rsbx** [comment]
This issue does not appear to completely fixed.

1. Starting the program with a stud style of plain and changing to high contrast (no logo) the brick 1 x 1 in the brick parts list is not high contrast.
2. Changing back to plain, some brick in the parts list display still have high contrast.
3. If I continue to toggle between plain & high contrast, I continue to get some bricks with studs inconsistent with the style setting.

**Comment by leozide** [comment]
I can't repro, are they only inconsistent in the parts list or are they wrong in the main view as well?

What happens when you change colors?

**Comment by rsbx** [comment]
Main view as well. Usually some, but not all, studs.

**Comment by rsbx** [comment]
Interestingly, after deleting the cache directory (not running at the time), it's appears to be behaving as expected.

**Comment by leozide** [comment]
Cache has nothing to do with this, are you sure it wasn't the second fix?

**Comment by rsbx** [comment]
I had the issue after compiling 03c9b7 until I deleted the cache. I have 
not had the issue since, but my testing has been limited.

**Comment by j6t** [comment]
I could reproduce the problem once with the most recent version (03b9c75d9e5be), but not anymore.

However, now I observe unreproducable crashes during startup, not very frequent, but still. There's a heisenbug somewhere... At first I thought it happened when the stud style is _Plain_ when the session begins, but that isn't it.

I did not clear the cache as you say that it does not matter, @leozide.

**Comment by leozide** [comment]
I've never seen a startup crash but any information would be helpful.

Cache only matters as there can be a bad cache entry from before the fix but should be fine if you try to repro after the fix.
