### ISSUE TITLE
Qt5 main view broken (old commit)

### ISSUE THREAD

**Issue by CableGuy67** [leozide/leocad#61]
I don't know if this has to do with my upgrade to Debian Stretch or if I just haven't built this since this was done. As of https://github.com/leozide/leocad/commit/6491d15bb3061fd0f43a3e9646c5bd50e6d4f940 the mail view is pretty much borked. I can see it if I split the view but otherwise it just paints through whatever was behind when opened. I can drop elements there from the picker etc but there is no active view.

Compiled on Debian 9 and Qt 5.3.2

Compiling against Qt4 works fine up to the current commits this afternoon.

I'm using SVN for my local copy so the log of the commit before (the one that still works) is this,

r928 | leonardo.zide | 2017-03-27 04:28:31 +0300 (Mon, 27 Mar 2017) | 2 lines
Fixed synth parts adding the wrong mesh to the scene when in a submodel. Fixes #42.
https://github.com/leozide/leocad/commit/49a88e1ab4a92d5a0ef672098683dd13f75d9f91

**Comment by CableGuy67** [comment]
Actually it seems I am Using Qt version 5.7.1 in /usr/lib/x86_64-linux-gnu but for some reason Creator is still reporting the version from before the OS upgrade. It seems like it is just wrong on my creator tab name. It points at the 5.7.1 qmake. Sorry about the confusion.

**Comment by leozide** [comment]
Does it work If you go back 1 revision earlier?

What do you have set for anti aliasing? Can you try disabling?

Can you copy and paste the contents of the About dialog?

**Comment by CableGuy67** [comment]
Yes it does. At this commit, https://github.com/leozide/leocad/commit/49a88e1ab4a92d5a0ef672098683dd13f75d9f91 everything works fine. This is the info from that version:

my local svn stuff:
```
Repository Root: https://github.com/leozide/leocad.git
Repository UUID: 6b26b618-02d0-9b70-f35b-ce57b7db7bff
Revision: 928
Node Kind: directory
Schedule: normal
Last Changed Author: leonardo.zide
Last Changed Rev: 928
Last Changed Date: 2017-03-27 04:28:31 +0300 (Mon, 27 Mar 2017)
```

about dialog:
LeoCAD Version 17.02
```
OpenGL Version 2.1 Mesa 13.0.6 (GLSL 1.20)
Mesa DRI Intel(R) Ironlake Mobile  - Intel Open Source Technology Center

Color Buffer: 24 bits RGBA double buffered
Depth Buffer: 24 bits
Stencil Buffer: 8 bits

GL_ARB_vertex_buffer_object extension: Supported
GL_ARB_framebuffer_object extension: Supported
GL_EXT_framebuffer_object extension: Supported
GL_EXT_texture_filter_anisotropic extension: Supported (max 16)
```
Moving one revision forward to here https://github.com/leozide/leocad/commit/6491d15bb3061fd0f43a3e9646c5bd50e6d4f940 :

my local svn stuff:
```
Repository Root: https://github.com/leozide/leocad.git
Repository UUID: 6b26b618-02d0-9b70-f35b-ce57b7db7bff
Revision: 929
Node Kind: directory
Schedule: normal
Last Changed Author: leonardo.zide
Last Changed Rev: 929
Last Changed Date: 2017-03-27 09:12:05 +0300 (Mon, 27 Mar 2017)
```

About dialog:
LeoCAD Version 17.02
```
OpenGL Version 2.1 Mesa 13.0.6 (GLSL 1.20)
Mesa DRI Intel(R) Ironlake Mobile  - Intel Open Source Technology Center

Color Buffer: 24 bits RGBA 
Depth Buffer: 24 bits
Stencil Buffer: 8 bits

GL_ARB_vertex_buffer_object extension: Supported
GL_ARB_framebuffer_object extension: Supported
GL_EXT_framebuffer_object extension: Supported
GL_EXT_texture_filter_anisotropic extension: Supported (max 16)
```
Okay, I had anti-aliasing set at x8
I disabled and restarted then the view is shown normally.
Turned it back on at x2 and the view is bad again.

There you have it. Nice troubleshooting there Boss.
updating svn back to current and rebuilding from qmake -qt=5 ; make

Okay, updated to current, -r989 for me, and it works with anti-aliasing turned off but not with it on. It is weird since it looks like the commit was just you moving a small bit of code from one file to another.

Anyhow, thanks for looking at this so quickly Leo. I'll watch for any updates.

**Comment by leozide** [comment]
My guess here is that there's a Qt or driver problem with MSAA, you could try updating both (but they seem to be somewhat recent versions). I can't repro the problem on any of my computers so I can't help fixing it but from what I noticed while debugging, it falls back to the lowest level of MSAA supported if I request something invalid.

The change didn't just move code from one file to another, it changed the order of operations so MSAA was set before the first widget was created. If you go back to the old version and enable MSAA it will only enable it for the 2nd and later views created.

**Comment by CableGuy67** [comment]
Yeah, I wouldn't have noticed that order of operations if it hit me with a shovel. That does explain why it worked after splitting the view. As for the rest of it I will see if I can find out anything. Or just leave anti-aliasing off for now.
Thanks for the help and the overall package. I'll close this since you can't reproduce it. Maybe my aging laptop (and choice of OS) are the real factor here.
