### ISSUE TITLE
copying parts between submodels does not retain building step information anymore

### ISSUE THREAD

**Issue by omichalek** [leozide/leocad#612]
**Describe the bug**
In the previous version one could copy group of parts between two submodels and they would keep their timeline properties -- if there were enough building steps in the timeline, parts would be pasted into their original step numbers.

**To Reproduce**
1. select parts using mouse (rectangular selection)
2. ctrl+C
3. switch to another submodel (new or existing)
4. create sufficient number of (empty) building steps in the timeline
4. ctrl+V

Now all parts irrespective of their original building step are pasted into only one, the currently selected step.

**Expected & proposed behavior**
- Either the inserted parts are pasted to their original building step number (as in the previous version)

or better yet a more flexible solution to work with the timeline would be welcome, eg.:
- Pasted parts are placed into consecutive steps, starting with the selected one, then continuing onto next steps (in their original order). Missing steps if any would be created automatically. In this way one can append parts at the end of the model instructions to for example merge submodels or their parts.

**Additional context**
I used such copy-pasting to iterate on submodels and while this functionality could be introduced with a welcome "clone submodel" button, the proposed solution would be more flexible and I believe intuitive.

**Version (please complete the following information):**
 - Windows 10
 - continuous version (LeoCAD-Windows-6fe393d1.exe)

**Comment by leozide** [comment]
This change was requested by some users, I'll add an option or a different paste action for this

**Comment by nathaneltitane** [comment]
> This change was requested by some users, I'll add an option or a different paste action for this

different paste action +1
