### ISSUE TITLE
[BUG] Submodel is confusingly saving to a new file

### ISSUE THREAD

**Issue by hfiguiere** [leozide/leocad#616]
**Describe the bug**
Submodule is very confusing. I'll skip #181 is one major issue and focus on creating a submodel in an existing model.

**To Reproduce**
1. In an empty model Add a brick.
2. Ctrl-S to save the model. The file dialog appears, give it a name (with .ldr extension). I used `test.ldr`
3. Add another brick. Ctrl-S to save. Just checking. It is saved.
4. [this can also work with an existing model]
5. Select Submodel > New Submodel. Click OK
6. There is a new tab for the submodel. The window title still say `test.ldr`
7. Ctrl-S to save the model.

**Expected behavior**
I expect simple to save.
Instead I get a file dialog to ask for a name,

**More steps**
1. The file saved contain both models.
2. The window title has the new file name (`test2.ldr` in my case)
3. Ctrl-S to save the model
4. Again it ask for a filename.

**Screenshots**
n/a

**Version (please complete the following information):**
 - OS: Fedora 33
 - LeoCAD Version 21.01 from Flatpak or git master.

**Comment by hfiguiere** [comment]
I think I see what's happening. Leocad expect a `.mpd` as soon as there is a submodel.

So there are several issues here:
- the user isn't informed
- leocad will still save a `.ldr`

Not sure what exactly is the best solution. Maybe defaulting to `.mpd` ?

**Comment by leozide** [comment]
Probably just keep saving as ldr, I think all apps can handle it

**Comment by hfiguiere** [comment]
If that works seems to be a simple solution.

**Comment by nathaneltitane** [comment]
mpd spec is made to handle that. saving to ldr would lead to confusion or file type issues with other editors?

I believe I had brought that up some time ago in another bug entry.

**Comment by leozide** [comment]
We did talk about this but I don't remember what the conclusion was. I'll remove the code that tries to change the file extension and leave that responsibility to the user.
