### ISSUE TITLE
Pieces misplaced from lxf file

### ISSUE THREAD

**Issue by hfiguiere** [leozide/leocad#626]
**Describe the bug**
In the attached file, the pieces are not properly positionned. The bone should be horizontal, and, with the bowl, on the base

**To Reproduce**
1. Import the attached .lxf file. [60024-3 Dog and bowl.zip](https://github.com/leozide/leocad/files/5948226/60024-3.Dog.and.bowl.zip) (it is inside the zip, thanks Github)

**Expected behavior**
Pieces are in the proper place.

**Observed**
The bone is vertical (should be flat)
Both the bone and the bowl should be on the ground level.

**Screenshots**

**Version (please complete the following information):**
 - OS: Linux
 - LeoCAD Version git master

**Comment by hfiguiere** [comment]
Another file:
https://bricksafe.com/files/stephan3321/LDD%20models/Aircraft.lxf

The 2x2 plate with hole holding the pin for the propeller is misplaced and rotated wrong.
The 1x1 next to it are also misplaced.
See rendered version https://bricksafe.com/files/stephan3321/LDD%20models/Aircraft%20klein.png

**Comment by leozide** [comment]
The importer table doesn't have entries for all parts, there was a better converter somewhere in the LDraw forums.

**Comment by hfiguiere** [comment]
Can't the missing pieces be added?

**Comment by leozide** [comment]
Sure, the parts are in resources/ldraw.xml
