### ISSUE TITLE
BrickLink export need proper part remapping

### ISSUE THREAD

**Issue by hfiguiere** [leozide/leocad#630]
**Describe the bug**
Exporting to BrickLink inventory use part number that Bricklink doesn't recognize.

**To Reproduce**
1. Open the attached .ldr (inside a zip, sorry, github's fault) 
[bricklink.zip](https://github.com/leozide/leocad/files/6016652/bricklink.zip)
2. Export to bricklink (XML)
3. Go to BrickLink, Want > Upload > Upload bricklink XML format
4. Copy / paste the conent of the XML file and click "Proceeed to..."
5. See error about incorrect part number :

**Expected behavior**
The proper part numbers are used.

**Screenshots**
![Screenshot from 2021-02-20 16-37-51](https://user-
[bricklink.zip](https://github.com/leozide/leocad/files/6016651/bricklink.zip)
images.githubusercontent.com/114441/108609278-e0e20a00-739a-11eb-9ea7-45fd43582fcd.png)

**Version (please complete the following information):**
 - OS: Linux
 - LeoCAD Version 21.01 Flaptak or git master.

**Crash information:**

**Additional context**

**Comment by hfiguiere** [comment]
Changing the part number to the Bricklink part number where appropriate works.

**Comment by nathaneltitane** [comment]
that's also an issue with LDraw and bricklink databases using completely distinct entries in some cases.

I made a bash script to that effect to correct some part IDs before pasting

**Comment by hfiguiere** [comment]
> I made a bash script to that effect to correct some part IDs before pasting

I have a working solution, but I need a bigger "map" to remap more.

**Comment by hfiguiere** [comment]
Also I think normalizing parts that are `~Moved to` would go a long way.

**Comment by hfiguiere** [comment]
Not sure how to deal with minifig arms and hands.

**Comment by nathaneltitane** [comment]
> Not sure how to deal with minifig arms and hands.
> 
> 

they all have proper BL part IDs. what's the issue?

**Comment by hfiguiere** [comment]
Uh. It was not trivial to find. Rebrickable doesn't have them, etc. Solved.

**Comment by hfiguiere** [comment]
See also #441

**Comment by hfiguiere** [comment]
This is fixed with #632 

There is probably more parts that can be added though.
