### ISSUE TITLE
Investigate minifig head lighting

### ISSUE THREAD

**Issue by leozide** [leozide/leocad#641]
![image](https://user-images.githubusercontent.com/9685066/110226194-f890b680-7ea1-11eb-9f3c-31caff9ab60c.png)

**Comment by leozide** [comment]
Also on heads:

![image](https://user-images.githubusercontent.com/9685066/111052783-ff27ac80-8412-11eb-98a2-e6f1242de655.png)

3626cpx3.dat in ldrawunf.zip

**Comment by rsbx** [comment]
Looking at torso 973 and head 3626a using wireframe shading with LC_DEBUG_NORMALS enabled, it appears that the normals of the affected areas don't point where I'd expect them to. BTW, the torso also has the issue on the "neck".

**Comment by rsbx** [comment]
Hmmm; if I disable my BFC code, 3626a and the neck of 973 are fine. But, 973 still has issues where the arms go.

**Comment by rsbx** [comment]
Another OFFICIAL part with normal issues: 14769, Tile 2x2 Round with Round Underside Stud. Specifically the areas by the notches.

**Comment by rsbx** [comment]
Attached is a detail image of part 14769, Tile 2x2 Round with Round Underside Stud, showing the vertex normals in _wireframe_ mode using _orthographic_ projection from above. There are a number of triangles & quads with vertex normals that do match the normal of their triangle/quad in the area that I highlighted. I suspect the issue affecting minifig torsos, e,g, 973.dat, is related to what is going on here.

![tile_14769](https://user-images.githubusercontent.com/533684/111210596-cd921b00-85a3-11eb-998f-9165824b6a25.png)

To get this view, I made the following changes to the code at commit  b10d8953:
- Defined `LC_DEBUG_NORMALS` to 1 in common/lc_scene.cpp
- Changed the calls to `MeshLoader()` in common/lc_library.cpp and pieceinf.cpp to disable vertex optimization and normal averaging
- Deleted all of the cache files via `rm -rf`

**Comment by leozide** [comment]
These are a pain to track down but you need to do it with smoothing enabled

**Comment by rsbx** [comment]
This is showing the _inputs_ to the smoothing and explains why the 
smoothed normals are wrong. But I'm not understanding why the unsmoothed 
normals are wrong.

The area around torso, 973.dat, arm holes also has wrongly pointed 
unsmoothed normals so I think it's the same issue. I find it easier to 
see with the wireframe of the tile than the wireframe of the torso.

**Comment by rsbx** [comment]
I'm pretty sure the bad input normals are caused by shear components in the transformation matrices in the definitions of 973 (torso) and 14769 (round tile). For example, the follow matrix, from the outer, left side, 4-4ndis.dat primitive of 973, appears to ONLY have shear and scale components.

`-0.85     0    0`
` 4.925   1    0`
` 0     0    5`

I have not investigated 3626cpx3 since it's an unofficial part and I don't have them loaded but, from the image, it appears that the normals are inverted for 1/2 the head.

**Comment by rsbx** [comment]
Here's the patch to fix the issue:

[normalfix.patch.txt](https://github.com/leozide/leocad/files/6152873/normalfix.patch.txt)

For those interested: normals need to be transformed by the transpose of the inverse of the transform matrix.

**Comment by rsbx** [comment]
It looks like a couple of the shaders need to be fixed also but that's beyond me.

**Comment by leozide** [comment]
I think you're on the right track, I tried to orthonormalize instead and it looks like the Minifig torso is fixed. I don't think transposing the inverse is really needed, it may be fixing the matrix as a consequence of the inverse operation.

**Comment by Symbian9** [comment]
Also happen with eyes on many heads parts:

![pic.1](https://i.imgur.com/BHKpkmM.png)

![pic.2](https://i.imgur.com/UKUtp3m.png)

**Comment by rsbx** [comment]
No, the transpose(inverse()) is needed. Do a search using "computer 
graphics transform normals" as the terms for the reasons (likely in the 
textbooks also).

Thinking about the shaders some more: they're OK as is if the world 
matrix is _only_ composed of rotations and _uniform_ scaling.

**Comment by leozide** [comment]
Both methods are removing non uniform scaling so the results will be equivalent for orthogonal matrices.

Shaders don't need to change because the world matrices are affine transforms.

**Comment by rsbx** [comment]
Shears are _not_ orthogonal matrices. Not sure about scaling.

Shears & non-uniform scaling _are_ affine transforms.

**Comment by leozide** [comment]
Ok, the transforms are orthonormal

**Comment by rsbx** [comment]
@Symbian9 what are the part IDs for those heads you found with issues?

**Comment by Symbian9** [comment]
> what are the part IDs for those heads you found with issues?

That was `3626bp61.dat` and `3626bpa1.dat`.

FTR, In latest *LeoCAD* https://github.com/leozide/leocad/commit/b548e1f4d24437e5fe062ecc638fea5686625e2a build (I use `
LeoCAD-Linux-b548e1f-x86_64.AppImage`) it **seems like issue already fixed**:

![pic.1](https://i.imgur.com/uNvgPpe.png)

**Comment by rsbx** [comment]
Great! Likely caused by the normals calculation issue that was just fixed.

I see you found the High Contrast stud style option.

**Comment by rsbx** [comment]
Can this issue be closed?

**Comment by rsbx** [comment]
The shading discontinuity with 3626cpx3 is cause by the texture coordinates not matching where the front and back textures meet. Since the compare fails, a new vertex in add and the there's no normal smoothing.

**Comment by rsbx** [comment]
That should fix 3626cpx3 & friends:
[addvertex.patch.txt](https://github.com/leozide/leocad/files/6208824/addvertex.patch.txt)

**Comment by rsbx** [comment]
Improved patch:

[addvertex.patch.txt](https://github.com/leozide/leocad/files/6214066/addvertex.patch.txt)
