### ISSUE TITLE
Preview color lock does not match inserted piece color

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#643]
**Describe the bug**
Selecting a color for parts preview in the parts widget does not keep the color on part insertion

**To Reproduce**
1. Go to Parts widget and use gear context menu to lock color for parts in preview
2. Drag any part in newly created document
3. Inserted part has a different color

**Expected behavior**
Locked to or selected color should match color of part being inserted until changed with properties or color picker

**Screenshots**
![Screenshot_20210307-122706_VNC Viewer.png](https://user-images.githubusercontent.com/5674757/110248912-650ec280-7f41-11eb-9a55-450964e846ae.png)

**Version (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu, macOS]
 - LeoCAD Version [e.g. 19.07 or continuous]

**Crash information:**
Some versions of LeoCAD will show a message that they saved a minidump file when they crash, if you see this message please attach the file.

**Additional context**
Add any other context about the problem here. If you're seeing a graphical issue, adding a screenshot of the About Dialog may help.

**Comment by j6t** [comment]
I think that *Lock Preview Color* is not intended to freeze the color of inserted pieces, but only to ensure that the previewed pieces always have the same color. This is useful when the color has little contrast with the background.

IMO, LeoCAD is working as designed and there is no bug.

**Comment by nathaneltitane** [comment]
> I think that *Lock Preview Color* is not intended to freeze the color of inserted pieces, but only to ensure that the previewed pieces always have the same color. This is useful when the color has little contrast with the background.
> 
> IMO, LeoCAD is working as designed and there is no bug.

preceding a certain release, the insertion color would match the lock preview.

in this case, we can state then that we are missing a way to specify (easily) a color for parts prior to inserting them I'd the preview is locked

**Comment by rsbx** [comment]
Not at all. I use locked preview color so I can actually see the details 
of the parts no matter what color I've currently selected. You can 
change the color of the next, and following, insert just by clicking a 
color in the color panel.

**Comment by leozide** [comment]
I don't think this is a bug either, if you lock the preview color it's because you want to be able to change the insertion color without affecting the preview.

**Comment by app4soft** [comment]
> preceding a certain release, the insertion color would match the lock preview.

FTR, in latest LeoCAD, "Colors" widget has a line button (acted same as "Paint" button) with an actual color preview icon, so when color locked for icons in "Parts", just take a look on "Colors" first line color.

![LeoCAD-color-preview](https://github.com/user-attachments/assets/67fdf2f9-9677-45b7-a65d-785ccd824d21)
