### ISSUE TITLE
Lots of weird lines appearing

### ISSUE THREAD

**Issue by lzandman** [leozide/leocad#646]
**Describe the bug**
When loading a model in the latest version (4a50ac6) of LeoCAD strange lines are appearing. I played with the rendering preferences and they go away when I uncheck either Edge Lines or Conditional Lines. So they appear when both are checked. I don't know if this is normal behavior, but I'm sure I didn't see it in the previous version of LeoCAD I ran (21.01). So either these rendering preference checkboxes got checked during the version upgrade or they should be checked and LeoCAD is rendering wrongly.

**To Reproduce**
Just start LeoCAD.

**Expected behavior**
A normal model, without the lines.

**Screenshots**
<img width="1289" alt="LeoCAD-BugLines" src="https://user-images.githubusercontent.com/3685378/110285356-701a2f00-7fe3-11eb-93a1-16647616e9cf.png">

**Version (please complete the following information):**
 - OS: macOS 11.2.2 (MacBook Air M1)
 - LeoCAD Version 4a50ac6

**Comment by leozide** [comment]
Can you try the latest continuous please?

**Comment by lzandman** [comment]
It looks like it is fixed in the latest release. I don't see the lines appearing anymore.

In fact I don't see anything change when I switch Conditional Lines on/off. What does it even do? The Edge Lines checkbox does seem to work.

**Comment by leozide** [comment]
Look for the lines on the sides of the studs:

![Screen Shot 2021-03-10 at 7 58 58 PM](https://user-images.githubusercontent.com/9685066/110733735-52afb580-81db-11eb-8236-755cec54d811.png)
