### ISSUE TITLE
Very strange behaviour

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#647]
**Describe the bug**
Opening a file with the name 'csi.ldr' triggers an automatic orientation adjustment when the part is rendered  - tested with part 32532.dat.

**To Reproduce**
1. Create 3 files '_csi.ldr_', '_pli.ldr_',  and '_sm.ldr_' with the line `1 15 0 0 0 1 0 0 0 1 0 0 0 1 32532.dat`.
2. Launch LeoCAD
3. Drag and drop pli.ldr onto the viewport to correctly render part 32532 as follows...
![Screenshot - 09_03_2021 , 07_11_25](https://user-images.githubusercontent.com/13388970/110426588-af5d8400-80a6-11eb-8e69-8cae05d9c9c7.png)
4. Drag and drop csi.ldr onto the viewport and you will see the orientation of part 32532 is automatically adjusted...
![Screenshot - 09_03_2021 , 07_13_35](https://user-images.githubusercontent.com/13388970/110426817-05322c00-80a7-11eb-8ce0-91d777b682f2.png)
5. To validate the unexpected behaviour above, drag and drop sm.ldr onto the viewport. Part 32532 will be rendered with the orientation as expected - i.e. the same as pli.ldr.
![Screenshot - 09_03_2021 , 07_17_35](https://user-images.githubusercontent.com/13388970/110427166-a15c3300-80a7-11eb-825e-75ca1fd85be8.png)
6. Repeat several time in any order to see that part 32532 in csi.ldr will consistently be rendered adjusted.

**Expected behavior**
There should be no difference in the orientation of rendered part 32532 for each file.

**Version:**
 - OS: [Windows 10]
 - LeoCAD Version [21.01 built from source at commit de3a3adf345c19c3146d77648b75f5aaba47108d]

**Additional context**
Changing as little as a single letter in the csi.ldr name resolves the unexpected behaviour. 
I am also able to reproduce this behaviour using the open file dialogue.

Cheers,

**Comment by rsbx** [comment]
I'm not seeing the reported behavior on Linux using the openfile dialog 
(drag-n-drop doesn't work with my window manager). And a quick "grep -ir 
csi" of the source tree does not find anything not a substring of 
something unrelated.

Now I'm REALLY curious.

**Comment by trevorsandy** [comment]
No. Unchecking 'Restore tab layout' appears to reset the application to the expected state. So it seems this behaviour is triggered by some sort of corruption of the saved tab state. Particularly opening more than one instance of LeoCAD at the same time may also be a contributing factor.

Anyway, perhaps it's unique to my environment, preferences dialog crashes on accept  in the latest continuous build. 

![Screenshot - 10_03_2021 , 00_09_07](https://user-images.githubusercontent.com/13388970/110551053-19246f00-8135-11eb-8a57-c0423d45a847.png)

![Screenshot - 09_03_2021 , 23_56_43](https://user-images.githubusercontent.com/13388970/110551068-217caa00-8135-11eb-8cd0-5daf9d0fe798.png)

Cheers,

**Comment by leozide** [comment]
Restoring tabs also restores the cameras so the original issue is not a bug.

I saw the preferences crash happen, I don't know what it is.

**Comment by trevorsandy** [comment]
> Restoring tabs also restores the cameras so the original issue is not a bug.
Understood. Thx.

Cheers,

**Comment by leozide** [comment]
Let me keep this open to remind me to look at the crash

**Comment by trevorsandy** [comment]
In _leocad\qt\lc_qpreferencesdialog.ui_ the `<tabstop>tabWidget</tabstop>` element should be first child of `<tabstops>`; instead, it's the last element.

Update the tab order placing `tabWidget` first will resolve the abnormal end.

Cheers,

**Comment by trevorsandy** [comment]
Closed per discussion #652.

Cheers,

**Comment by trevorsandy** [comment]
Oops, closed the wrong ticket.

**Comment by leozide** [comment]
Thanks for looking this up.
