### ISSUE TITLE
Relative move of rotated pieces with mouse is confusing for new users

### ISSUE THREAD

**Issue by PetteriAimonen** [leozide/leocad#655]
**Describe the bug**
When relative move is enabled (as by default), rotated pieces move in unexpected direction when dragged with mouse.

**To Reproduce**
1. Verify that relative move toolbar button is on, as it is by default.
2. Add a brick
3. Drag on blue rotation arrow to rotate piece by 90 degrees
4. Click and drag on piece (mouse cursor on the piece but not on any arrow or plane)
5. Observe that when you move mouse right, piece moves up, and when you move mouse down, piece moves right.
6. Turn off relative move on toolbar and piece moves as expected.

**Expected behavior**
I expected the piece to follow mouse regardless of the relative move setting.

However, I do not know if relative move is supposed to work this way - I understand that it changes the direction of the arrows and the direction of the keyboard movements, but I wouldn't expect it to change how mouse coordinates map to movement. If it is supposed to work this way, maybe it could be disabled by default in new installations until users find the button :)

**Screenshots**
In this recording I first try to move piece right, but it moves up. Then I try to move it down, but it moves right.
https://jpa.kapsi.fi/stuff/other/leocad_move.mp4

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - LeoCAD Version 21.01 x86_64 AppImage

**Comment by leozide** [comment]
Fixed in 249fa26
