### ISSUE TITLE
Conditional Lines issue

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#668]
Similar to #646, I'm seeing "wierd lines" if conditional lines are enabled, using the orthographic projection, one of the **F**, **B**, **L**, **R** views, on my host system (Intel integrated graphics) but not in the VMs ((LLVM rendering), starting at commit `9db8a011`, "Better Conditional line math". Commit `6ef3f355`, "Updated version", does not exhibit the issue.

![condlines](https://user-images.githubusercontent.com/533684/111525808-6061bf80-8734-11eb-885d-20c7c26e559f.png)

All models I've tried with conditional lines have exhibited the issue.

**Comment by rsbx** [comment]
And here's a fix:

[condshader.patch.txt](https://github.com/leozide/leocad/files/6159356/condshader.patch.txt)

This fix leaves the updated math but reverts the non-draw case to what commit `6ef3fe55` did.

**Comment by Symbian9** [comment]
JFTR, @rsbx, May I ask you are you use some custom settings or custom 'tube' primitives? Why are they all are black?

![pic.1](https://i.imgur.com/DvnG1FQ.png)

**Comment by rsbx** [comment]
High Contrast studs.

**Comment by rsbx** [comment]
@leozide  Bump

**Comment by leozide** [comment]
I can't repro the problem but I don't see how this change fixes this issue. You're just moving the lines to the center of the screen and adding a divide by 0, which is undefined.

**Comment by rsbx** [comment]
I don't know either. I pulled that line from your original conditional line shader in commit c3ad14ac and it worked for me.

I just tested the latest fix and I'm not seeing issues in either environment.

I don't understand how any of the conditional line shaders signal OGL to not draw the line.

**Comment by leozide** [comment]
You can't skip a primitive in a VS, best you can do is have it be clipped
