### ISSUE TITLE
Some resources missed in OBS builds

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#67]
@pbartfai, I just test latest build from OBS
* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb

This DEB not include "leocad.png", should be placed in
```
/usr/share/icons/hicolor/32x32/apps/leocad.png
```

I test also build from Launchpad, that include this icon
* https://launchpad.net/ubuntu/artful/amd64/leocad/17.02-1

**Comment by Symbian9** [comment]
Also, some 'mime' files missed too.

**Comment by pbartfai** [comment]
@Symbian9 
file /usr/share/icons/hicolor/32x32/apps/leocad.png added on OBS

What mime files are missing?

**Comment by Symbian9** [comment]
> What mime files are missing?

@pbartfai, This one missed too

* `/usr/share/mime/packages/leocad.xml`

It included in builds on Launchpad

* https://launchpad.net/ubuntu/+source/leocad/17.02-1

Here is code of 'leocad.xml'
```
<?xml version="1.0"?>
<mime-info xmlns='http://www.freedesktop.org/standarts/shared-mime-info'>
    <mime-type type="applicatio/vnd.leocad">
        <comment>LeoCAD Project</comment>
        <magic priority="90">
            <match type="string" offset="0" value="LeoCAD 0.">
                <match type="string" offset="10" value=" Project\0\0"/>
            </match>
        </magic>
        <glob pattern="*.lcd"/>
        <glob pattern="*.leocad"/>
    </mime-type>
    <mime-type type="application/x-ldraw">
        <comment>LDraw File</comment>
        <glob pattern="*.ldr"/>
        <glob pattern="*.dat"/>
    </mime-type>
    <mime-type type="application/x-multi-part-ldraw">
        <comment>Multi-part LDraw File</comment>
        <glob pattern="*.mpd"/>
    </mime-type>
<mime-info>
```
But need little udate this MIME file to actual state (I will try do it now)

@leozide, what you think on it?

**Comment by pbartfai** [comment]
Found a typo in debian.rules on OBS, fixed, but the .xml file disappears from debian package although it is present during building phase..

```[  150s] install -m 644 qt/leocad.xml /usr/src/packages/BUILD/debian/leocad/usr/share/mime/packages/leocad.xml
[  150s] pwd
[  150s] /usr/src/packages/BUILD
[  150s] ls -l qt/leocad.xml /usr/src/packages/BUILD/debian/leocad/usr/share/mime/packages/leocad.xml
[  150s] -rw-r--r-- 1 root root 690 Aug  1 16:01 /usr/src/packages/BUILD/debian/leocad/usr/share/mime/packages/leocad.xml
[  150s] -rw-rw-r-- 1 root root 690 Jul 30 21:18 qt/leocad.xml
```

**Comment by Symbian9** [comment]
> but the .xml file disappears from debian package although it is present during building phase..

@pbartfai, so could you fix it?

**Comment by Symbian9** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870596

**Comment by pbartfai** [comment]
Reorganized mime package installation in debian scripts. The file gets copied, but disappear in final .deb file. No idea why.
```
[  168s] dh_installmime
[  168s] 	install -p -m0644 debian/leocad.sharedmimeinfo debian/leocad/usr/share/mime/packages/leocad.xml

```

**Comment by pbartfai** [comment]
Tested debian packaging system on standalone Debian 9 and leocad.xml was part of the generated package. It seems this is an OBS issue/bug.

**Comment by Symbian9** [comment]
But in same folder package **lpub3d-*.deb** include mime `lpub3d.xml` that is similar case

* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/lpub3d_2.0.20.711_amd64.deb

Could you compare your build scripts for lpub3d and leocad?

Also, please, report this issue to OBS developers too

**Comment by Symbian9** [comment]
@pbartfai, why inside builds, produced during August, all data dated on 31 July?

* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/leocad_17.07_amd64.deb

OBS must use 'master' branch state at the momoment when start binary packages.

**Comment by pbartfai** [comment]
OBS uses 'master' branch...

**Comment by Symbian9** [comment]
> OBS uses 'master' branch...

So, why inside latest DEB (built on 12 August 2017) all data dated on 31 July 2017?

There are few changes and additions in 'master' since 31 July, that not yet included in OBS build produced on 12 August

* https://github.com/leozide/leocad/commits/master

**Comment by pbartfai** [comment]
Opened ticket at bugzilla, but no progress

https://bugzilla.opensuse.org/show_bug.cgi?id=1052751

Also specified master branch in _service file.

**Comment by Symbian9** [comment]
@pbartfai, its look like OBS still use code dated on 31 July (before patch applied?)
* https://github.com/leozide/leocad/issues/111

**Comment by pbartfai** [comment]
Checked debian build on private OBS instance and file /usr/share/mime/packages/leocad.xml is present. File date is even older...

**Comment by Symbian9** [comment]
> File date is even older...

@pbartfai, read also this comment

* https://github.com/leozide/leocad/issues/111#issuecomment-325787671
