### ISSUE TITLE
Source build documentation makes no mention of Pov-Ray as a build dependency

### ISSUE THREAD

**Issue by herbygillot** [leozide/leocad#678]
**Describe the bug**
On macOS, when building LeoCAD from source via the instructions here:

https://www.leocad.org/docs/compiling.html

No mention is made of Pov-Ray, which, if not present in the build directory, causes the build to fail with:

```
make: *** No rule to make target `povray', needed by `build/release/LeoCAD.app/Contents/MacOS/povray'.  Stop
```

**To Reproduce**
1. On macOS, download LeoCAD source
2. Follow instructions here: https://www.leocad.org/docs/compiling.html
3. Start build process up until running `make`
4. `make` fails because of the missing `povray` binary

**Expected behavior**
The build succeeds and produces a working `LeoCAD.app`

**Version (please complete the following information):**
 - OS: macOS Cataline 10.15.7
 - LeoCAD Version: 21.03

**Comment by Symbian9** [comment]
@leozide, Guess there should be an optional flag to compile LeoCAD with `povray` via importing next submodule:

- https://github.com/leozide/povray

**Comment by herbygillot** [comment]
> @leozide, Guess there should be an optional flag to compile LeoCAD with `povray` via importing next submodule:
> 
> * https://github.com/leozide/povray

May not need to be a git submodule, if that's what you're referring to.

I didn't realize @leozide was using his own fork of `povray`.  I tried to using an externally-built official version of `povray`, and that didn't work very well, so I'll look to try with the fork you linked and see how well that works.

**Comment by leozide** [comment]
Just download https://github.com/leozide/povray/releases/download/continuous/povray, I'll update the docs

**Comment by herbygillot** [comment]
> Just download https://github.com/leozide/povray/releases/download/continuous/povray, I'll update the docs

So I'm seeing the same issue where this binary is referencing libraries in `/usr/local` - these libraries are not present by default on macOS, and they don't get installed with the LeoCAD.app bundle DMG.  I'll try to build `povray` seperately.

**Comment by leozide** [comment]
Something changed then, it used to work. The mac version doesn't get a lot of testing, my MBP died a few years ago and I only got access to a mac again last month.

**Comment by herbygillot** [comment]
Maybe the right thing here are simple tests using a macOS image with Github Actions.
