### ISSUE TITLE
Rendering fails on macOS 10.15

### ISSUE THREAD

**Issue by herbygillot** [leozide/leocad#679]
**Describe the bug**
LeoCAD fails to start Pov-Ray when attempting to render a scene in macOS 10.15.

**To Reproduce**
1. Download "LeoCAD for macOS" from the [LeoCAD download page](https://www.leocad.org/download.html)
2. Install it into the Applications folder
3. Start LeoCAD from the Applications folder
4. Make a simple scene
5. Click the File menu, then click "Render..."
6. On the Render window that comes up, leave the options to their default values and click the "Render" button
7. See error messages pop up

**Expected behavior**
Expected that LeoCAD renders the scene

**Screenshots**
<img width="676" alt="Screen Shot 2021-03-22 at 7 49 54 AM" src="https://user-images.githubusercontent.com/618376/111986053-cd35da80-8ae3-11eb-88e7-00e3e9770630.png">

**Version (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - LeoCAD Version 21.03

**Comment by herbygillot** [comment]
From what I can see, there are 2 issues:

1. The `povray` binary in _/Applications/LeoCAD.app/Contents/MacOS_ doesn't have the executable bit set.
2. The `povray` binary isn't statically compiled, attempting to load libraries from _/usr/local_:
   ```
    dyld: Library not loaded: /usr/local/lib/libtiff.5.dylib
    Referenced from: /Applications/LeoCAD.app/Contents/MacOS/povray
    Reason: image not found
    ```

**Comment by Symbian9** [comment]
It may be the same in both DMG (macOS) & AppImage (Linux) builds.

AppImage also does not include POV-Ray binary (there are no `AppImage:/squashfs-root/usr/bin/povray`) — instead AppImage expects that there is already installed POV-Ray on Linux as `/usr/bin/povray`.

**Partial solution:**

- install Pov-Ray separately;
- in LeoCAD's *"Preferences > General > POV-Ray Executable: `[path]`"* settings set `[path]` to installed Pov-Ray binary.

**Comment by leozide** [comment]
I'll recompile with static libs once I remember how I did it in the first place

**Comment by trevorsandy** [comment]
Here's an alternative to statically compiling POV-Ray, which will be quite a piece of work considering its dependencies.

**Required POVRay libraries on macOS - versions may vary**

-ZLib 1.2.11, Copyright 1995-2012 Jean-loup Gailly and Mark Adler
-LibPNG 1.6.26, Copyright 1998-2012 Glenn Randers-Pehrson
-LibJPEG 9c, Copyright 1991-2016 Thomas G. Lane, Guido Vollbeding
-LibTIFF 4.0.9, Copyright 1988-1997 Sam Leffler, 1991-1997 SGI
-Boost 1.67, http://www.boost.org/
-OpenEXR 2.2.0 and IlmBase 2.2.1, Copyright (c) 2002-2011 Industrial Light & Magic - this may be optional based on how Leo compiled povray.

For the libraries above that you do not have follow the below guidance:

- XQuartz
  https://www.xquartz.org 
```
  /opt/X11/lib/libXpm.4.dylib (compatibility version 16.0.0, current version 16.0.0)
  /opt/X11/lib/libSM.6.dylib (compatibility version 7.0.0, current version 7.1.0)
  /opt/X11/lib/libICE.6.dylib (compatibility version 10.0.0, current version 10.0.0)
  /opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
```
- LibPNG version 1.6.35 or above
  http://www.libpng.org
  `/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 52.0.0, current version 52.0.0)`

- LibTIFF version 3.6.1 or above
  http://www.libtiff.org
  `/usr/local/opt/libtiff/lib/libtiff.5.dylib (compatibility version 9.0.0, current version 9.0.0)`

- OpenEXR version 1.2 or above
  http://www.openexr.com
 ```
	/usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib (compatibility version 23.0.0, current version 23.0.0)
	/usr/local/opt/ilmbase/lib/libImath-2_2.23.dylib (compatibility version 24.0.0, current version 24.0.0)
	/usr/local/opt/ilmbase/lib/libHalf.23.dylib (compatibility version 24.0.0, current version 24.0.0)
	/usr/local/opt/ilmbase/lib/libIex-2_2.23.dylib (compatibility version 24.0.0, current version 24.0.0)
	/usr/local/opt/ilmbase/lib/libIexMath-2_2.23.dylib (compatibility version 24.0.0, current version 24.0.0)
	/usr/local/opt/ilmbase/lib/libIlmThread-2_2.23.dylib (compatibility version 24.0.0, current version 24.0.0)
 ```

**Install brew (if not already installed)**

- `$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

**Install libraries**

- `$ brew update`
- `$ brew install libpng libtiff openexr`

**Check installed libraries - using libPNG as an example**

- `$ otool -L $(brew list libpng | grep dylib$)`
    `/usr/local/Cellar/libpng/1.6.35/lib/libpng.dylib:`
        `/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 52.0.0, current version 52.0.0)`
        `/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)`
        `/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)`

**Reference: Treating “dyld image not found” return**

-See the steps from this excellent post: [Fixing dyld image not found on Mac OS](http://droolfactory.blogspot.com/2012/07/fixing-dyld-image-not-found-on-mac-os.html).

Cheers,

**Comment by herbygillot** [comment]
Thanks @trevorsandy. I'm actually putting together a port of LeoCAD for [MacPorts](https://www.macports.org), so I'll be building against the MacPorts packages for all these dependencies.

**Comment by leozide** [comment]
I've recompiled povray with static libs, I tested the new build and I think it's good now but let me know if there are any issues still.

**Comment by Symbian9** [comment]
> I've recompiled povray with static libs

@leozide, Are you mean that DMG & AppImage has bundled POV-Ray binary now?
