### ISSUE TITLE
Redesign LeoCAD logic for project files (.mpd/.ldr)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#68]
Have an idea how improve LeoCAD in saving muilty-parts documents and models.

Ideas:
* NOW: LeoCAD from start create "New Project.ldr" with `Model #1.ldr` model inside it.
  * NEED: LeoCAD by default must create "New_Project.mpd" with `Model_#1.ldr` inside it.
* NOW: general "File -> Save" option not clear for multy-parts documents and models
  * NEED: for save multi-parts documents (.mpd) use "File -> Save", for save single model (.ldr) from project use "Model -> Models... -> Save"
* ...

P.S.: I will add more details and mocups soon

**Comment by Symbian9** [comment]
Think, this is related - https://github.com/leozide/leocad/issues/69
* http://www.f-lohmueller.de/pov_tut/lego/lg2pov160e.htm

> **Import and export file formats** (load/save):
> * .lcd - LeoCAD Projects
> * .dat - old LDraw format
> * .ldr - single-part LDraw file ( im-/export also in LEGO Digital Designer ® ! )
> * .mpd - multi-part LDraw file

**Comment by leozide** [comment]
5f582f7fd1c155cd97d846394761982119837545 takes care of this
