### ISSUE TITLE
Add Joint Feature/handle

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#680]
**Is your feature request related to a problem? Please describe.**
ENHANCEMENT: 
Add a joint feature / handle to enable submodel/part group free or parametered movement along specified axis.

**Describe the solution you'd like**
The ability to specify, for a group of parts or a submodel assembly the part to use a joint (free, linear or other) and facilitate posability, either through free motion push/pull (animation style) or by specifying angles in the properties panel.

**Describe alternatives you've considered**
n/a

**Additional context**

Blender model rigging:

https://youtu.be/f2pTkW-1JkE

**Comment by leozide** [comment]
I don't understand, how's this different than using the focused piece as the pivot?

**Comment by nathaneltitane** [comment]
> I don't understand, how's this different than using the focused piece as the pivot?

It would be different in where this 'function' would identify the part as an actual joint and permit free movement of the identified group or submodel - that could go hand in hand with some sort or collision detection.

The idea is to facilitate positioning and animation in the same manner you can rig a model in Blender and use the positional vectors/handles to set the desired movments or posture.
