### ISSUE TITLE
it's a bug

### ISSUE THREAD

**Issue by madameraul** [leozide/leocad#681]
**Describe the bug**
when I go in leoCAD I can't see the pieces or block it's just black

**To Reproduce**
1. Go to 'leoCAD...'

**Expected behavior**
I want too see the plates

**Screenshots**
![image](https://user-images.githubusercontent.com/81356203/112450418-0e84ef00-8d5d-11eb-9327-9f964c0b4e19.png)

**Version (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu, macOS]
 - LeoCAD Version [e.g. 19.07 or continuous]

**Crash information:**
Some versions of LeoCAD will show a message that they saved a minidump file when they crash, if you see this message please attach the file.

**Additional context**
Add any other context about the problem here. If you're seeing a graphical issue, adding a screenshot of the About Dialog may help.

**Comment by leozide** [comment]
Can you add a screenshot of the About Dialog please?

**Comment by WeeGeeDaOne** [comment]
View > Preferences > Views
Ensure that Draw studs and Draw studs every x studs is enabled.
