### ISSUE TITLE
Documentation on the !LEOCAD META commands

### ISSUE THREAD

**Issue by TobyLobster** [leozide/leocad#69]
Is there documentation on LeoCAD's added commands in the ldraw file format? I'm thinking of the "0 !LEOCAD ..." lines. I'd like to add support for them in [ImportLDraw](https://github.com/TobyLobster/ImportLDraw).

**Comment by Symbian9** [comment]
@TobyLobster, its look like this part of own fileformat of LeoCAD Project file - **.lcd**
* http://www.f-lohmueller.de/pov_tut/lego/lg2pov160e.htm

> **Import and export file formats** (load/save):
> * .lcd - LeoCAD Projects
> * .dat - old LDraw format
> * .ldr - single-part LDraw file ( im-/export also in LEGO Digital Designer ® ! )
> * .mpd - multi-part LDraw file

**Comment by Symbian9** [comment]
Its look like **.lcd** is 'legacy' fileformat since LeoCAD 0.81
* http://www.leocad.org/docs/history.html

> Version 0.81 (18/1/2015)
> * Changed save file format to ldr/mpd (loading lcd is still supported).

Here are few examples of LeoCAD Projects
* http://www.joesdiner.org/lego/cg.html

**Comment by leozide** [comment]
There was some documentation in the old wiki but I never moved it to the website:

https://github.com/leozide/test/wiki/MetaCommands

It's missing a couple of things but should be enough to get you started.

**Comment by TobyLobster** [comment]
Thanks @leozide I'll take a look.

**Comment by leozide** [comment]
Updated and moved to http://www.leocad.org/docs/meta.html

**Comment by Symbian9** [comment]
> There was some documentation in the old wiki but I never moved it to the website:
> 
> https://github.com/leozide/test/wiki/

@leozide, where sources of current website (`http://www.leocad.org/docs/`) located? How pull reqest in it? Because I already sew few mistakes in documentation section.

**Comment by Symbian9** [comment]
> Updated and moved to http://www.leocad.org/docs/meta.html

Fix header part of this subpage, because it has same header as "Texture Mapping" subpage
> #Texture Mapping
> 
> LeoCAD supports texture mapped primitives through the LDraw TEXMAP extension.
> 
> ###Model
> ...

**Comment by leozide** [comment]
The gh-pages branch

**Comment by TobyLobster** [comment]
The documentation at http://www.leocad.org/docs/meta.html shows "0 !LEOCAD CAMERA FOV <angle>" as a separate command from ZNEAR and ZFAR commands, but in practice I see these all three on a single line, as "0 !LEOCAD CAMERA FOV <angle> ZNEAR <distance> ZFAR <distance>". Similarly ORTHOGRAPHIC and HIDDEN are not separate commands, but options within NAME, like so: "0 !LEOCAD [HIDDEN] [ORTHOGRAPHIC] CAMERA NAME <name>"

**Comment by leozide** [comment]
They can be in the same line or in any order, I'll make a not to make this more clear.

**Comment by TobyLobster** [comment]
Do they all have to be present? Does NAME have to be last?

**Comment by leozide** [comment]
They don't need to be present, name has to be last.

**Comment by TobyLobster** [comment]
Thanks. If a parameter isn't present, what are their default values?

**Comment by leozide** [comment]
I've updated the docs with the defaults

**Comment by TobyLobster** [comment]
Thanks, all looks good.
