### ISSUE TITLE
Save MPD to LDR files

### ISSUE THREAD

**Issue by trymeouteh** [leozide/leocad#705]
Please allow you to open MPD files and save these files as LDR files.

**Comment by j6t** [comment]
Why? What is the problem?

**Comment by trymeouteh** [comment]
I want to convert a MPD file to a LDR file.

**Comment by j6t** [comment]
But there is no practical difference between the two file formats, just rename `.mpd` to `.ldr`.

**Comment by rsbx** [comment]
Inline everything and save-as...

**Comment by leozide** [comment]
Like the other posters said, you can already do that so there's no need to add anything new.

**Comment by trymeouteh** [comment]
Now I understand. I am using the flatpak on Linux and maybe the flatpak does not allow you to change the file extensions when going to Save As. Maybe add an option to set the file extension to LDR or MPD when saving for less confusion. I assumed LDR files are different than MPD files
