### ISSUE TITLE
Implement parts palettes

### ISSUE THREAD

**Issue by sheepo99** [leozide/leocad#708]
**Suggestion**
Perhaps an easy but worthwhile feature to implement would be parts palettes, like they have on Stud.io. Parts palettes are parts lists with a limited number of predetermined parts. Stud.io in particular allows you to load and import official models as parts palettes so you can build them sequentially, instead of loading all parts on the screen at the same time. This is particularly useful for people who enjoy creating alternate builds and prevents the screen from getting cluttered when importing official models.

Here are some screenshots on how it works on Stud.io:

![image](https://user-images.githubusercontent.com/3621746/116881578-b70f5400-ac23-11eb-9957-7a08649712a7.png)

I've loaded the official set 31058 Mighty Dinosaurs as a parts palette. It display all parts in the set with a number indicating the amount the set contains.

![image](https://user-images.githubusercontent.com/3621746/116881712-e1f9a800-ac23-11eb-8dc5-e79b8c8e0a94.png)

Here I placed a 1 x 2 green brick. The parts list subtracts one brick from the 1 x 2 green brick stack. Once all bricks from a stack are depleted, the stack is removed altogether.

**Comment by nathaneltitane** [comment]
> **Suggestion**
> Perhaps an easy but worthwhile feature to implement would be parts palettes, like they have on Stud.io. Parts palettes are parts lists with a limited number of predetermined parts. Stud.io in particular allows you to load and import official models as parts palettes so you can build them sequentially, instead of loading all parts on the screen at the same time. This is particularly useful for people who enjoy creating alternate builds and prevents the screen from getting cluttered when importing official models.
> 
> Here are some screenshots on how it works on Stud.io:
> 
> ![image](https://user-images.githubusercontent.com/3621746/116881578-b70f5400-ac23-11eb-9957-7a08649712a7.png)
> 
> I've loaded the official set 31058 Mighty Dinosaurs as a parts palette. It display all parts in the set with a number indicating the amount the set contains.
> 
> ![image](https://user-images.githubusercontent.com/3621746/116881712-e1f9a800-ac23-11eb-8dc5-e79b8c8e0a94.png)
> 
> Here I placed a 1 x 2 green brick. The parts list subtracts one brick from the 1 x 2 green brick stack. Once all bricks from a stack are depleted, the stack is removed altogether.

Though the idea sounds interesting, I believe this goes beyond the integration of such a feature into LeoCAD (speaking for myself) - Stud.io is much more tightly woven into the official Lego/Bricklink scheme of things and ti seems almost natural that such a feature does exist.

LeoCAD does provide a 'palette' feature: said palette(s) are used to load often used or preferred parts/pieces/models quickly rather than having to browse for them continuously.

**Comment by sheepo99** [comment]
Well, but this doesn't need to be woven into Bricklink/Lego databases for that matter nor does it relate to it. Suppose when you load an .ldr, instead of loading the model on screen, it simply makes a parts inventory and puts them on a separate list of its own.

**Comment by nathaneltitane** [comment]
> This is a duplicate request from #431. You can already import a palette from Bricklink, but it won't limit by quantity or color.

I was looking for the ticket! Thanks @leozide

**Comment by sheepo99** [comment]
Ah, alright, I see this one is on progress then. I will close this feature request now.
