### ISSUE TITLE
Program freezes on random occasions - and very often

### ISSUE THREAD

**Issue by dedif** [leozide/leocad#710]
**Describe the bug**
Program freezes on random occasions - and very often

**To Reproduce**
1. open LeoCAD
2. do just anything for a few seconds to 5 minutes, like opening a file (for example: https://drive.google.com/file/d/1XwqLk4OWmfCN7sj47xEOr2AqBE-yc1m0/view) and try to enter the minifig menu.
3. it crashes. It leaves a dump in AppData\Local\Temp\leocad.dmp

**Expected behavior**
No crashing

**Screenshots**

**Version (please complete the following information):**
 - OS: Windows 10 20H2
 - LeoCAD Version 19.07 and 21.03

**Crash information:**
See file at https://drive.google.com/file/d/1M7MOqlbZab14hGAX9eb0SLZcW3A07zDi/view

**Additional context**
Could not think of any. Please tell me if you require more information

**Comment by leozide** [comment]
Where did you download this from?

**Comment by dedif** [comment]
I believe I got the 21.03 version from leocad.org. The 19.07 version was from the LDraw All-In-One installer 2020-03

**Comment by dedif** [comment]
Last week I reinstalled my computer. I just played around in LeoCAD for over an hour and it did not crash. So there's a good chance the problem was in my old, very buggy Windows installation.

**Comment by leozide** [comment]
That's good news.
