### ISSUE TITLE
Parts list does not list all available submodels in submodels category

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#711]
**Describe the bug**
Parts list does not list all available submodels in submodels category:
When in a specific submodel, going into the 'Submodels' part list category, i was unable to find the 'cockpit' submodel related to the submodel i was editing (head).
I had to go back to the main model entry for 'cockpit' to appear in the list to then lock it in preview and go back to editing the head.

**To Reproduce**
1. open any model containing submodels
2. select any submodel to edit (A)
3. scroll to parts list 'submodels' category - observe that related submodel entry B which contains A is not listed
4. Cannot select B from within A during edit to lock into preview.

**Expected behavior**
All submodels should be made available in submodel part category to at least be able to quickly select and lock them into preview window.

**Screenshots**
![Screenshot_20210504-210134_VNC Viewer.png](https://user-images.githubusercontent.com/5674757/117087267-e9e94300-ad1c-11eb-99a3-d76d069ad1da.png)

**Version (please complete the following information):**
 - OS: Ubuntu 20.04.2 Arm64 chroot
 - LeoCAD Version : git continuous

**Comment by rsbx** [comment]
I believe this is to prevent users from attempting to create recursively 
defined submodels (from within LeoCAD).

But I don't that's the real issue here; it seems that what you really 
want is for different views to be able to display/manipulate different 
submodels simultaneously. I think there's already an issue for this.

**Comment by leozide** [comment]
From your description of the problem it sounds like this is on purpose like @rsbx mentioned above.
