### ISSUE TITLE
Flatpak application | Missing developer/project/organisation name mention

### ISSUE THREAD

**Issue by Ricky-Tigg** [leozide/leocad#713]
Hello. As noticeable the worth mentioning **developer/project/organisation** name is missing at your application path under https://flathub.org/apps/. As a result it is then dully reported as "_Unknown_" when exhibited by Flatseal '`flatpak run com.github.tchx84.Flatseal`'. This value is part of the application [metadata](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer_name).

![LeoCAD_flatseal](https://user-images.githubusercontent.com/26058215/118257858-cad67800-b4b7-11eb-8a3e-4a93bc999016.png)

**Comment by Ricky-Tigg** [comment]
That 47124cf had no effect | `flatpak --system -y update`

**Comment by leozide** [comment]
That's because the flatpak doesn't include that change
