### ISSUE TITLE
Latest Ubuntu (21.04) still offers old version of LeoCAD (19.07.1)

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#714]
**Is your feature request related to a problem? Please describe.**
Although many bugs and features have been taken care of and added, Ubuntu 21.04 still seems to offer an older ('stable') version of LeoCAD

**Describe the solution you'd like**
Create some kind of dynamic updater or PPA archive to have the Ubuntu packages repo servers fetch and build a git or latest up to date version of the code and make it available for users to install via the distribution archives.

**Describe alternatives you've considered**
Update git Travis CI to offer latest version as deb?

**Additional context**

![Screenshot_20210515-124822_Chrome.png](https://user-images.githubusercontent.com/5674757/118371843-6a5d3e80-b57c-11eb-961b-469f0ae7488d.png)

**Comment by Symbian9** [comment]
@pbartfai has an OBS repo with daily builds, but it seems like it still provides *LeoCAD* `18.02`:

- https://software.opensuse.org/download.html?project=home%3Apbartfai&package=leocad
  - https://download.opensuse.org/repositories/home:/pbartfai/

**Comment by leozide** [comment]
I've sent a pull request https://salsa.debian.org/debian-lego-team/leocad/-/merge_requests/2

You can get the latest from snap
