### ISSUE TITLE
AppImage builds not provided anymore?

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#715]
**Describe the bug**

There are NO `*.AppImage` nightly builds as assets to `continuous` pre-release:

- https://github.com/leozide/leocad/commit/47124cf1ca89db8be3dc3c93cdcc9c0bfa64316f

**Expected behavior**

Check Travis CI & resetup (if needed) to fix it.

**Version (please complete the following information):**

 - OS: Linux (AppImage)
 - LeoCAD Version: continuous

**Additional context**

Please, check latest Travis CI notes:

- https://travis-ci.org/
> Please be aware https://travis-ci.org will be shutting down in several weeks, with all accounts migrating to https://travis-ci.com . Please stay tuned here for more information.

**Comment by leozide** [comment]
Fixed

**Comment by Symbian9** [comment]
I wont create separate issue on, but it seems like since https://github.com/leozide/leocad/commit/23a93b4afbfeb2c22c294e7188402b6aaab9e2bd Travis CI not provide checks & artifacts, right?

Please, @leozide, fix it again.
