### ISSUE TITLE
Crashing on ver 21.03

### ISSUE THREAD

**Issue by WeeGeeDaOne** [leozide/leocad#716]
**Describe the bug**
Trying to select a specific plate will cause LeoCAD to crash for no reason.

**To Reproduce**
1. Open LeoCAD
2. Select all parts.
3. Type plate 4

**Version (please complete the following information):**
 - OS: Windows 10 20H2
 - LeoCAD Version: 21.03

[testing and minidump.zip](https://github.com/leozide/leocad/files/6488939/testing.and.minidump.zip)

**Comment by leozide** [comment]
The minidump you sent is from 21.01, can you try downloading the latest version to see if this is fixed?

**Comment by WeeGeeDaOne** [comment]
This is from 21.03, and I can confirm this
![image](https://user-images.githubusercontent.com/84267593/118495693-bb5b6700-b723-11eb-8b76-04afc7f55ba2.png)

**Comment by leozide** [comment]
I believe this has been fixed already, you have to check the continuous build: https://github.com/leozide/leocad/releases/tag/continuous
