### ISSUE TITLE
LeoCAD AppImage does not work

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#718]
**Describe the bug**

AppImage does not work.

**To Reproduce**

1. Download latest AppImage build (i.e., `LeoCAD-Linux-f69ecf7-x86_64.AppImage`);
2. Set it as executable (i.e., `$ chmod a+x ./LeoCAD-Linux-f69ecf7-x86_64.AppImage`);
3. Try to launch it (i.e., `$ ./LeoCAD-Linux-f69ecf7-x86_64.AppImagee`);
4. See error.

**Expected behavior**

LeoCAD should be launched.

**Screenshots**

**Version (please complete the following information):**

- OS: Debian 10 buster
- LeoCAD Version: `continuous` ~ https://github.com/leozide/leocad/commit/f69ecf7fc03ff7f7437c8687acadc3e4894fc2a7

**Crash information:**

```Shell
$ ./LeoCAD-Linux-f69ecf7-x86_64.AppImage
execv error: No such file or directory
```

**Comment by leozide** [comment]
Fixed
