### ISSUE TITLE
Crashing on ver 21.03

### ISSUE THREAD

**Issue by 3dhype** [leozide/leocad#719]
Describe the bug
Trying to select a specific library folder will cause LeoCAD to crash for no reason.

To Reproduce

    Open LeoCAD
    Go to: View > Preferences > Rendering
    Shading Mode: Rounded Top Logo
    Select Part Library: Boat

Version (please complete the following information):

    OS: Windows 10 20H2
    LeoCAD Version: 21.03
[leocad.zip](https://github.com/leozide/leocad/files/6517312/leocad.zip)

**Comment by leozide** [comment]
I think this bug has already been fixed, can you try the latest continuous release?

**Comment by 3dhype** [comment]
He Leonardo

I will try!

I was looking for it but couldn’t find at first. 
https://github.com/leozide/leocad/releases/tag/continuous

Nevertheless, keep up the good work! It’s an amazing piece of software!

Met vriendelijke groet,
Edwin van het Bolscher

3D Artist - Developer
3ddy - 3dhype
