### ISSUE TITLE
Export/Save as .lxf

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#72]
Propose use "lxf2ldr" as start point, because it already include all needed resources
* http://www.eurobricks.com/forum/index.php?/forums/topic/150480-announcing-lxf2ldr/
* https://gitlab.com/sylvainls/lxf2ldr
  * https://gitlab.com/sylvainls/lxf2ldr/blob/master/README.md
* http://www.eurobricks.com/forum/index.php?/forums/topic/137193-more-up-to-date-ldrawxml-lddldraw-conversion-file/

**Comment by leozide** [comment]
I think lxf is pretty dead at this point, plus it's a closed format.
