### ISSUE TITLE
crushed

### ISSUE THREAD

**Issue by Alter21** [leozide/leocad#720]
**Version :**
 - OS:  Windows 10
 - LeoCAD Version 21.03 
**Crash information:**
Some versions of LeoCAD will show a message that they saved a minidump file when they crash, if you see this message please attach the file.

![Screenshot (1)](https://user-images.githubusercontent.com/85166171/120311336-09ee3100-c2e0-11eb-88be-ef84005664a3.png)
[leocad.md](https://github.com/leozide/leocad/files/6575662/leocad.md)

**Additional context**
Add any other context about the problem here. If you're seeing a graphical issue, adding a screenshot of the About Dialog may help.

**Comment by leozide** [comment]
I believe this has been fixed already, you can try installing the latest build from https://github.com/leozide/leocad/releases/tag/continuous
