### ISSUE TITLE
No respect for users

### ISSUE THREAD

**Issue by licensechecker** [leozide/leocad#722]
The license under which the program is distributed is not indicated anywhere, neither in the "about the program" window, nor in the installer, nor in the project properties of the page on the github. From here we can conclude that it is shareware and open source for review.

only the 64-bit version is compiled and this is not noted anywhere. At least the installer notes that this is a 64-bit version. Just a mockery of users.

Your application to add a program has been rejected. You can close the ticket, there will be no response.

**Comment by sheepo99** [comment]
1st: If you checked the website you would find the license available here https://www.leocad.org/docs/license.html

2nd: Even if the license was missing you will not get any sympathy by treating other people like this. Funny to claim the developer is disrespectful towards users while approaching him in a very disrespectful manner.
