### ISSUE TITLE
Corrupted vertices since bf7a382d

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#727]
Testing the latest I'm seeing corrupted vertices information on some specific textured parts when rendered:
- 3960p0b
- 19201p01
- 19204p01

![71626](https://user-images.githubusercontent.com/533684/122950999-ef413200-d34a-11eb-8808-7e138f9ea70d.png)

This is reproducible on my Debian 10 "Buster", amd64 systems using locally built executables and the cache cleared between each test.

Commit d48d8 does not exhibit the issue.

**Comment by rsbx** [comment]
This fixed 19204p01 but 3960p0b and 19201p01 still have bad vertices.

**Comment by leozide** [comment]
Those look correct to me, can you post a screenshot?

**Comment by rsbx** [comment]
![3960p0b](https://user-images.githubusercontent.com/533684/123556302-6ebe6f00-d758-11eb-8ab0-c3e8e59e4c47.jpg)
![19201p01](https://user-images.githubusercontent.com/533684/123556303-6f570580-d758-11eb-8474-af1f8755b4a4.jpg)

**Comment by leozide** [comment]
I've seen something like that when the texture file was missing, is it the case here?

**Comment by rsbx** [comment]
That appears to be the case for both of them. Interesting that I'm using 
the complete.zip downloaded from ldraw.org and they're not included.

**Comment by rsbx** [comment]
Here's with a9971b0:
![3960p0b](https://user-images.githubusercontent.com/533684/123557132-2fdee800-d75d-11eb-9c1b-288a3acea816.png)
![19201p01](https://user-images.githubusercontent.com/533684/123557133-2fdee800-d75d-11eb-8233-a4e9b8911263.png)

**Comment by leozide** [comment]
Maybe clear the cache

**Comment by rsbx** [comment]
5decefcb seems to have fixed things.
