### ISSUE TITLE
Import...Set Inventory (75893 for example) does not work for me....

### ISSUE THREAD

**Issue by SergiLego** [leozide/leocad#728]
**Describe the bug**
Problem using Import...Set Inventory (75893 for example)
Not all the expected inventory imported, only partially.
No error, no warning,...

**To Reproduce**
Import...Set Inventory 
Select set 75893

**Expected behavior**
Import all the inventory of set 75893

**Screenshots**
![image](https://user-images.githubusercontent.com/86289461/123063834-0ac14100-d40e-11eb-9664-117d898a38a4.png)

**Version (please complete the following information):**
Win 7
LeoCAD 21.06

**Crash information:**
No crash info detected....

**Additional context**
Please help. Thanks.

**Comment by leozide** [comment]
What parts are missing?

**Comment by SergiLego** [comment]
Most of them...
The red ones
The yellow ones....
From the 3660 in ligth bluish gray to forward.

Thanks.
