### ISSUE TITLE
3D-View and Top-View look show placement of bricks differently

### ISSUE THREAD

**Issue by d029940** [leozide/leocad#740]
**Describe the bug**
3D View and Top view do not show the model consistently. It seems that top view is the culprit.
[ErrorPlateBrickTopView.ldr.txt](https://github.com/leozide/leocad/files/7072772/ErrorPlateBrickTopView.ldr.txt)

**To Reproduce**
1. Load attached model consisting of a plate and a brick (remove the txt extension)
2. Switch to 3D-View (if not already done): The plate and brick are aligned on the right side.
3. Switch to top view: It looks that the brick is half a stud beyond the right side of the plate.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - OS: MacOS 11.5.2
 - LeoCAD Version: 21.06

**Crash information:**
Some versions of LeoCAD will show a message that they saved a minidump file when they crash, if you see this message please attach the file.

**Additional context**
Add any other context about the problem here. If you're seeing a graphical issue, adding a screenshot of the About Dialog may help.

**Comment by nathaneltitane** [comment]
images of respective views?
have you tried toggling orthographic and perspective modes? it helps.
This may just be due to how lego ldraw parts are drawn and oriented within their respective dat files.

**Comment by d029940** [comment]
You are right. Switching to orthographic view gives me the expected result.
