### ISSUE TITLE
Build AppImage (releases & 'unstable')

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#75]
AppImage should be official LeoCAD binary for Linux (with LDraw Library included), as for now it's EXE for Windows or DMG for Mac.

Build 'stable' AppImage for each release
* https://bintray.com/probono/AppImages/LeoCAD#files
  * https://github.com/leozide/leocad/issues/13#issuecomment-273271764

Also, build 'unstable' AppImage using OBS from 'master'
* http://download.opensuse.org/repositories/home:/pbartfai/AppImage/
  * https://github.com/leozide/leocad/pull/63#issuecomment-315181404

Cast @probonopd, @pbartfai

**Comment by leozide** [comment]
I'll start uploading appimages on the next release

**Comment by probonopd** [comment]
How is the progress here? Do you need some help? Thanks.

**Comment by leozide** [comment]
I believe this script will work: https://github.com/leozide/leocad/blob/master/tools/setup/appimage.sh

I haven't released a new version since it was created

**Comment by probonopd** [comment]
OK, looking forward to your release. :+1:
