### ISSUE TITLE
CRITICAL : llvm and software rendering issues

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#753]
**Describe the bug**
when a desktop environment (linux) has no option to control compositing over LLVM/software rendering, the model space canvas becomes transparent and leocad also tends to slow down drastically in terms of performance resulting in crashes or unusable CAD sessions.

**To Reproduce**
1. Use old computer or mobile device with linux installed and Enlightenment DE, KDE, or XFCE (all with compositing enabled)
2. Open Leocad
3. Look at model space
4. See desktop through app window and other applications...

**Expected behavior**
The model space should not be transparent or look like some overlay. It should show as its own overdrawn canvas on the application UI when in focus.

(see screenshots of Leocad over Freecad and notice model space rendering method and difference and Leocad over bare desktop wallpaper)

**Screenshots**

![Screenshot_20211115-225016_Remotix](https://user-images.githubusercontent.com/5674757/141895351-3818b6f9-ddb6-48e1-b46c-3b5bfaf8ee9f.png)

![Screenshot_20211115-225655_Remotix](https://user-images.githubusercontent.com/5674757/141897014-bc4189fb-6cf8-4662-b329-4733a794b510.png)

**Version (please complete the following information):**
 - OS: Ubuntu ARM64 - linux all
 - LeoCAD Version [stable and continuous - all]

**Crash information:**
Some versions of LeoCAD will show a message that they saved a minidump file when they crash, if you see this message please attach the file.

**Additional context**
Add any other context about the problem here. If you're seeing a graphical issue, adding a screenshot of the About Dialog may help.

**Comment by nathaneltitane** [comment]
Additional screenshot for model space rendering difference:

![Screenshot_20211115-230001_Remotix](https://user-images.githubusercontent.com/5674757/141899175-b6f59f00-a778-4b12-a939-b7af5381aa51.png)

**Comment by nathaneltitane** [comment]
Additional screenshots showing leocad vs freecad rendering and leocad with scene background color changed.
Seems like there is an aplha mask on the model space?

![Screenshot_20211115-230249_Remotix](https://user-images.githubusercontent.com/5674757/141901635-aa6fda73-5641-46c8-b099-4d255923cabd.png)
![Screenshot_20211115-230001_Remotix](https://user-images.githubusercontent.com/5674757/141901660-38e9def3-c1be-4a72-b7b9-0a9552758dba.png)

**Comment by nathaneltitane** [comment]
@leozide bump?

**Comment by leozide** [comment]
This is a bug somewhere else, maybe Qt. Does it still happen if you set the background mode to gradient?

**Comment by nathaneltitane** [comment]
> 

seems alright when i toggle gradient mode and keep colors identical...

**Comment by nathaneltitane** [comment]
closing for now.
