### ISSUE TITLE
Precise Rotation of Parts

### ISSUE THREAD

**Issue by aeronautomat** [leozide/leocad#759]
When using bent technic beams, I cannot rotate by the exact angle the beam is bent (e.g., 53.13 degrees) and thus cannot use the part.

Please provide a way to enable precise rotations/make bent beams fully usable.

**Comment by j6t** [comment]
I suggest to use the *Properties* tab to rotate the piece precisely. I do that all the time.

Note that the piece angles are not the only irrational angles that occur in (Technic) models. Having a database of piece angles would get us nowhere.

If you have to rotate several pieces, construct them un-rotated first, then do a multi-selection and make sure to select the piece with the pivot point last. (I often insert a helper piece just for that purpose, usually an axle.) Then modify the angles in the *Properties* tab.

**Comment by aeronautomat** [comment]
Thank you so much for help!

**Comment by leozide** [comment]
There's a tutorial for rotation centers here: https://www.leocad.org/docs/rotation.html
