### ISSUE TITLE
LeoCAD-LiveUSB.iso (based on Puppy Linux)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#76]
Have an idea make **LiveUSB based on some Puppy Linux** distributive, that will include LeoCAD and few other related tools needed for modeling using LDraw.
* http://puppylinux.org/
* http://puppylinux.com/
* http://www.murga-linux.com/puppy/index.php?f=35

**Target**: make little cutted alternative for "All-In-One-Installer" for Linux users, that could run on any PC throw "boot from USB" option.
* http://www.ldraw.org/article/104.html
* http://www.murga-linux.com/puppy/viewtopic.php?t=22883

**Storage for user created files**: All data will be stored on this USB stick, so can be used on PC without harddrive.

**Size of ISO image**: should be smaller than 200 Mb.

**Platform support**:
* i386/i686 (x86, 32bit)
* amd64 (x86_64, 64bit)

P.S.: artwork for USB stick
* http://www.instructables.com/id/Lego-USB-Stick/
  ![DIY LEGO case for USB](https://cdn.instructables.com/F9N/5BOK/2P6EP281NIB/F9N5BOK2P6EP281NIB.MEDIUM.jpg)
  ![Live USB plugged](https://cdn.instructables.com/F4K/2KJK/JSEEP281NL8/F4K2KJKJSEEP281NL8.MEDIUM.jpg)
* http://wonderfulengineering.com/make-use-of-legos-in-these-10-awesome-ways/
  ![LEGO USB mini with cap](http://cdn.wonderfulengineering.com/wp-content/uploads/2014/02/7.-Lego-USB.jpg)
* https://brickset.com/sets/2856028-1
  ![2856028-1: LEGO Minifigure 2GB USB Flash Drive](https://images.brickset.com/sets/images/2856028-1.jpg?201103030319)

**Comment by nitrofurano** [comment]
please include lots of .ldr examples there! :) (i don’t know how okay is to add those from official instructions, including those classics from 60’s, 70’s and 80’s)

**Comment by probonopd** [comment]
Could also just install a Live ISO of your choice there (e.g., using SystemImageKit) plus the LeoCAD AppImage. AppImages are specifically made for this purpose 👍

**Comment by Symbian9** [comment]
@probonopd, AppImage is awesome, but this task related to stich all related and usefull ipen-source tools (such as LPub3d, LeoCAD, LDview, Blender, POV-Ray and few more).

AppImage good thing for one-two apps, that not use same libs.

But LeoCAD-LiveUSB will include many apps that use same libs, so for decriase size of this ISO need its much better make special distro. And Puppy Linux is best choise fir such things, because can run on old & new PC very fast.

**Comment by probonopd** [comment]
The beauty of AppImages is that they do not depend on each other, and that you can copy them over from machine 1 to machine 2 effortlessly. The duplication of libraries is the price to pay; a very reasonable price in my opinion.

**Comment by Symbian9** [comment]
> Each application should have its own AppImage.

Especially for "LeoCAD+LPub3D+LDglite+LDview" it would be complete toolbox for design models & create instructions. LPub3D depend on LeoCAD, LDview and/or LDglite. So in this situation 4 apps in 1 AppImage would be good choice.

**Comment by Symbian9** [comment]
@probonopd, Hm, I has a question related to AppImage: what is minimal size of Linux-based LiveUSB distributive for run AppImage?

Could you try construct it using as base Puppy Linux?

* http://puppylinux.com/woof-ce.html

* http://puppylinux.org/wikka/remastering

**Comment by probonopd** [comment]
The Fedora, Ubuntu, openSUSE Live CDs is what we test against, not "exotic" ones like Puppy Linux. As long as you include these libraries it might work:

- https://github.com/AppImage/AppImages/blob/master/excludelist
- https://github.com/AppImage/AppImages/blob/master/excludedeblist

**Comment by trevorsandy** [comment]
This is an old post but I would like to add that since v2.1.0, the LPub3D AppImage bundles LPub3D, LeoCAD(LPub3D 3DViewer), LDView, LDGLite and POV-Ray.

Cheers,
