### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by purplebonsai** [leozide/leocad#78]
What is the license of this software?

**Comment by leozide** [comment]
GPL2
http://www.leocad.org/docs/license.html

**Comment by ataalik** [comment]
Hello, why not create a LICENSE file to make it easier for people to see the license at first glance. Github would display the license at the top of the page like this image: 
![image](https://user-images.githubusercontent.com/5862754/51477868-c17eea00-1d9a-11e9-9361-c6fb1a81a25d.png) 

Also it would be filterable by license in search results.
