### ISSUE TITLE
Export obj quality

### ISSUE THREAD

**Issue by THEb0nny** [leozide/leocad#781]
Hello, there is a need for a choice of quality while saving. Now the model has a very large detail.

It turns out a lot of vertices and triangles.

**Comment by nathaneltitane** [comment]
> Hello, there is a need for a choice of quality while saving. Now the model has a very large detail.
> 
> It turns out a lot of vertices and triangles.

this is because part faces are conjoined due to how lego pieces are put together, making said vertices 'doubled'... that's just how the models are made and they need to be reprocessed afterwards for simplification - you can use blender to do that

**Comment by leozide** [comment]
you'll need to use an external program to reduce the polygons
