### ISSUE TITLE
CLI rendering shows tile spacing

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#792]
**Describe the bug**
programatically asking leocad to create view renders using coordinates generates render with visible tile spaces with atest leocad continuous build.

see attached render result:

![ag-01s-brynhildr-back](https://user-images.githubusercontent.com/5674757/158000612-234fef85-8b1d-4401-b28d-56d62573ab95.png)

**Comment by leozide** [comment]
works for me, you need to post the command line so I can repro

**Comment by nathaneltitane** [comment]
line 650 of[ l2cu](https://raw.githubusercontent.com/nathaneltitane/l2cu/main/l2cu):

`
	model_path="${1}"
	coordinates="${2}"

	height="4096"
	width="4096"

	antialias_samples="8"

	extension="png"

	leocad																		\
		--height "${height}"													\
		--width "${width}"														\
		--camera-angles ${latitude[$coordinates]} ${longitude[$coordinates]}	\
		--shading "${shading}"													\
		--line-width "${line_width}" 											\
		--aa-samples "${antialias_samples}" 									\
		--image "${model_name}-${view[$coordinates]}.${extension}"				\
																				"${model_path}" > /dev/null 2>&1

	wait
}
`

executed with bash l2cu -mpd -render -full -directory /path/to/models

**Comment by nathaneltitane** [comment]
Also just tested with a plain CLI (to make sure l2cu is not the culprit) directly in termal as follows: 

`leocad --image ./outfile.png  -w 4096 -h 4096 --viewpoint home --aa-samples 8 ./ag-01s-brynhildr.mpd `

output:

![outfile](https://user-images.githubusercontent.com/5674757/158087723-ab57fdcd-514e-4e42-986c-8c738436b62f.png)

**Comment by nathaneltitane** [comment]
I found where the issue comes from: if the color background is set to gradient in leocad.conf, the tiles issue appears
Once i set it back to single solid color the render came out properly

That being said, the CLI options/arguments need to reflect ALL the options available that woudl affect renders being called through CLI (i.e.: background color / transparency)

 I believe this has also been brought up in a similir ticket regarding cli option (cannot recall exact number, sorry)
