### ISSUE TITLE
Ldraw colors are not rendered accurately

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#795]
**Describe the bug**
Leocad does not render part colors accurately. a proper example would be the Tan color.
Specifying LDconfig.ldr does not change anything.

**To Reproduce**

**Expected behavior**
Rendered colors should match specified hex colorspace as defined at https://www.ldraw.org/article/547.html

**Screenshots**
Color comaprison in between actual render vs hex color spec: 

![Screenshot_20220327_122114](https://user-images.githubusercontent.com/5674757/160291281-d9f01e8c-9344-40b6-a651-9930238285b6.png)
![Screenshot_20220327_123004](https://user-images.githubusercontent.com/5674757/160291288-6923b9cc-eb7d-4a99-b63a-5083e3e8431f.png)

Effectively speaking, 'Dark Tan' looks more like the specified LDraw.org 'Tan' than what Leocad actually renders!

Top of unit is Dark Tan, feet are Tan:

![Screenshot_20220327_123322](https://user-images.githubusercontent.com/5674757/160291376-2b9dd471-8ede-473d-b841-356867062777.png)

Moreover, once the ldconfig.ldr or ldconfigalt.ldr is specified, Leocad does not update the contents of the model or the rendering to reflect the actual color changes:

the leocad color palette tool shows the updated scheme but the model needs to be updated manually, andf the color still does not match what is shown in the color palette - see below (lighter is ldconfig 'Tan' once reselcted and reappllied manually from color palette panel/tool) - see below:

![Screenshot_20220327_124112](https://user-images.githubusercontent.com/5674757/160291662-e0cd5063-5575-4f11-8954-fb2a07098374.png)

**Version (please complete the following information):**
all - continuous

**Comment by leozide** [comment]
the screenshots have lighting enabled, you can't expect them to match the unlit colors

**Comment by nathaneltitane** [comment]
@leozide screen caps may be showing lights, but i assure you that besides the 'expectation' of what'S to be seen, the color palette and model had a color attribution mismatch, even in flat shading.

I toggled the submodel properties and color configurations many times before submitting this bug.

Maybe having a look at what causes the palette update mismatch of failure to update entirely when ldconfig is loaded on a live model...

**Comment by leozide** [comment]
![image](https://user-images.githubusercontent.com/9685066/161406122-1e8fefd9-d255-4d6d-b6e2-ca035f299e05.png)

red brick is the expected color from ldconfig
