### ISSUE TITLE
MIssing faces on collada exports

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#796]
**Describe the bug**
using the collada export feature results in parts missing faces
part in question is 30324.dat

**Expected behavior**
all faces should export and render adequately when using hte collada export feature

**Screenshots**
![Screenshot_20220331_163611](https://user-images.githubusercontent.com/5674757/161145037-39d3ba2a-0ca4-445c-85e9-6b05d87dc40a.png)

**Version (please complete the following information):**
continuous - all

**Comment by leozide** [comment]
looks like this viewer has backface culling enabled, try to set the material to double sided or disable backface culling

**Comment by nathaneltitane** [comment]
FYI: BFC verification for that part renders correctly.
See attached image and message...

![Screenshot_20220404-141010_Messages.jpg](https://user-images.githubusercontent.com/5674757/161605411-424c1970-a56b-449d-aa23-06288a13b1be.jpg)
