### ISSUE TITLE
lxfml/ldd file support

### ISSUE THREAD

**Issue by tansiret** [leozide/leocad#799]
Currently only ldd file format is supported for import. Can lxfml be added as well?

**Comment by leozide** [comment]
ldd is lxfml inside a zip file, I don't understand what you're looking for. What app saves lxfml directly?

**Comment by yutyo** [comment]
> ldd is lxfml inside a zip file, I don't understand what you're looking for. What app saves lxfml directly?

Lego Universe client uses lxfml models in the game. I need it for that.

Lego Digital Designer and stud.io seem to be supporting import/export of lxfml directly.

**Comment by yutyo** [comment]
Is it possible to add ldd export support then?
