### ISSUE TITLE
Export obj of all bricks individually

### ISSUE THREAD

**Issue by tansiret** [leozide/leocad#808]
Export obj of all bricks individually like in stud.io

**Comment by nathaneltitane** [comment]
for what purpose does stud.io do that @yutyo ?

**Comment by craftnetics** [comment]
@yutyo Please check our LeoCAD fork and you will find an option in the export menu as AutoPrint. That option will allow you to export the geometries individually. We created this fork to test Lego models with our on-going AutoPrint project. Please feel free to reach for any questions. We also provide an explanation of how to import existing LDraw dataset to LeoCAD. Without that dataset it is quite challenging to import Lego models. I hope that will be useful for you. 
PS: For now the export asks the name of the individual object and you can simply press okay to confirm. We will update that naming method in the future.
