### ISSUE TITLE
No parts after installation 

### ISSUE THREAD

**Issue by L-Dlbcq** [leozide/leocad#825]
Hi everyone, 

When I try to use the program, there's no parts inside. So I can't use it.

Is there a solution ?

**Comment by nathaneltitane** [comment]
@leozide again a documentation issue maybe?

@L-Dlbcq you need to install the ldraw library and show leocad where your zip files or the uncompressed folder path is...

**Comment by L-Dlbcq** [comment]
@nathaneltitane i have already try to install the LDraw library but same issue. So I just move to LDraw complete package and the LeoCAD inside does not work but LDraw works
