### ISSUE TITLE
Move AppImage & DMG workflows to AppVeyor

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#828]
**Is your feature request related to a problem? Please describe.**

Travis-CI does not provide free service for opensource projects, so LeoCAD's `.travis.yml` is obsolete:

- ~~https://github.com/leozide/leocad/blob/master/.travis.yml~~

**Describe the solution you'd like**

As AppVeyor already supports Linux & Mac, and LeoCAD's Windows already built on AppVeyor, move `*.AppImage` & `*.dmg` workflows to AppVeyor too.

See next `appveyor.yml` as examples for Linux & Mac configuration:

- https://github.com/moonlight-stream/moonlight-qt/blob/master/appveyor.yml
- https://github.com/TASEmulators/fceux/blob/master/appveyor.yml

**Describe alternatives you've considered**

**Additional context**

**Comment by leozide** [comment]
Can you try the new appimage and let me know if it's working?

**Comment by Symbian9** [comment]
> Can you try the new appimage and let me know if it's working?

Are You mean ` LeoCAD-Linux-37dd02ee-arm64.zip`?

If so, I just tried it — it launched! But there was initial issue with missed dependency:

```
$ ./leocad
./leocad: error while loading shared libraries: libQt5Gamepad.so.5: cannot open shared object file: No such file or directory
```

After additionally install `libqt5gamepad5` package (**guess, it should added into AppImage**) it runs as next:

There was warning message before GUI started that there is no installed LDraw Parts Library detected, so it would use stripped built-in set, and after closing warning message window GUI starts as expected:

![Screenshot_2022-10-08_02-05-41](https://user-images.githubusercontent.com/13188580/194673918-6e02fbf5-7a4d-40b8-ab21-8831b6d7f17d.png)

Here is terminal log of successful launch, opening "Preferences" dialog and then closing app via "Exit" (without crashes), but there are still some minor issues with Xfce & XCB:

```
$ ./leocad
/usr/share/themes/Greybird-dark-mx/gtk-2.0/apps/xfce-panel.rc:7: error: unexpected keyword 'bg', expected string constant
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 544, resource id: 19851400, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1326, resource id: 19913937, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4083, resource id: 19919414, major code: 40 (TranslateCoords), minor code: 0
```

N.B. I'm successfully launched it on `amd64`, but just curios why this `continuous` AppImage is now named as targeted for `arm64` — is it cross-compiled for few architectures, including `amd64`?

**Comment by leozide** [comment]
Looks like continuous is working again
