### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [leozide/leocad#83]
I would like to point out that identifiers like “[`_LC_QSELECTDIALOG_H_`](https://github.com/leozide/leocad/blob/6d483252c5ac36d0a55115b311670816a175aa99/qt/lc_qselectdialog.h#L1 "Update candidate")” and “[`_LC_QUTILS_H_`](https://github.com/leozide/leocad/blob/8ed7e0d6c8c0620867413f181e9dd34a41fa06a8/qt/lc_qutils.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by leozide** [comment]
I've replaced them with pragma once

**Comment by elfring** [comment]
[This construct is also not standard compliant](https://stackoverflow.com/questions/1695807/why-isnt-c-cs-pragma-once-an-iso-standard "Why isn't C/C++'s “#pragma once” an ISO standard?").

**Comment by leozide** [comment]
I know, but pretty much all compilers support it.
