### ISSUE TITLE
Letter Bricks "S" is smaller than others

### ISSUE THREAD

**Issue by jalapenopuzzle** [leozide/leocad#831]
**Describe the bug**
I am building words using the letter bricks appearing in the brick section of the part palate.
The letter "S" appears significantly smaller than the other letters.

**To Reproduce**
1. Start a new document
2. Using arrow tool
3. Select brick section of part palate.
4. Drag 1x1 letter bricks to the building area and line them up to form a word including the letter "S"
5. The letter "S" appears smaller than all the other letters.
The other letters all align at their top and bottom boundaries.
The letter "S" bottom line is above the bottom line of all the other letters.
The letter "S" top line is below the top line of all the other letters.

**Expected behavior**
I expected the letter "S" to appear the same size, and with the same top and bottom lines, as all the other letters.

**Screenshots**
![20221017_Alphabet_Wall](https://user-images.githubusercontent.com/8386278/196169334-cacdb8c8-863a-452b-97cd-852f1f344861.png)

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - LeoCAD Version Built from source git commit 37dd02ee08612274ac28e105e7e707d7ec1194d4

**Additional context**
Add any other context about the problem here. If you're seeing a graphical issue, adding a screenshot of the About Dialog may help.
* Brick library.bin file downloaded from https://github.com/leozide/leocad/releases/download/v21.06/Library-20.03.zip

I expect you are going to tell me it's an issue with the library.zip, but I don't know what to do about that.

**Comment by nathaneltitane** [comment]
not a leocad issue @jalapenopuzzle  - go over to ldraw.org an file a report
