### ISSUE TITLE
doesnt fit

### ISSUE THREAD

**Issue by tzdfjklkjhztra** [leozide/leocad#832]
can you please make it work because if i try to build something with lego technic then  the axle doesnt fit into the holes of the beams.

**Comment by j6t** [comment]
You do not describe sufficiently what is broken and what must be fixed. A screenshot can help.

A shot in the dark: Switch Z-snapping to 1/2 stud.

**Comment by nathaneltitane** [comment]
Ref #253

**Comment by nathaneltitane** [comment]
not a bug
