### ISSUE TITLE
Using leocad as SDK

### ISSUE THREAD

**Issue by tytuseczek** [leozide/leocad#838]
Given 3 pieces i want to create every possible connections between them. How can leocad help me?

**Comment by nathaneltitane** [comment]
leocad can't do much unless there's some way to identify stud holes and studs in a programmatically correct way to begin with.

second, could you define 'every possible connection between them'? @tytuseczek

**Comment by jerzyorlowskimim** [comment]
<Writing from my second account>
1. Identifying studs and holes: I thought about about simple elements like technik bars and pins for a start. Have you heard of some tool in this area.

2. This is a graph generation algorithm with some contraint verification. shouldn't be too dificult.

So as far as I understand, I wuld need to programatically set the x,y and z and rotations of the blocks.
If I do it, can I use leocad to determine libraries, whether there are some collisions between blocks?
Or to generate some visialisations?
