### ISSUE TITLE
Packaging and LDRAW_LIBRARY_PATH

### ISSUE THREAD

**Issue by SylvainCorlay** [leozide/leocad#845]
Hey there! I am working on packaging leocad for conda-forge. The pull request for adding the package (only on Linux for now) is available [here](https://github.com/conda-forge/staged-recipes/pull/21818), and the resulting build works beautifully.

One outstanding issue before merging concerns the detection of the parts library, which is packaged in the `ldraw-parts` conda-forge package. I am specifying the location of the parts library when building leocad with the `LDRAW_LIBRARY_PATH` argument to qmake.

 - ldraw-parts installs the parts files in `$PREFIX/share/ldraw`, with the same layout as the Debian package.
 - this is also the value passed to `LDRAW_LIBRARY_PATH` when building leocad.

Still, I am seeing the warning "LeoCAD could not find a compatible Parts Library" although specifying the same `$PREFIX/share/ldraw` in the leocad preferences works as expected.

Debugging this a bit seems to indicate that `lcPiecesLibrary::Load` (through `OpenDirectory()`) returns `false`.

**Comment by leozide** [comment]
Is it passing -DLC_LDRAW_LIBRARY_PATH=/path/.../ correctly to gcc when compiling?

**Comment by SylvainCorlay** [comment]
> Is it passing -DLC_LDRAW_LIBRARY_PATH=/path/.../ correctly to gcc when compiling?

Yes, adding a few statements in the code when compiling shows that it is set at the correct value at runtime.

**Comment by leozide** [comment]
So where does it fail in OpenDirectory? It's just looking for parts/*.dat, which should be present

**Comment by SylvainCorlay** [comment]
I figured it out. The problem comes from the binary relocation done by conda.

conda allows to install binary packages in any "installation prefix"
this is made possible by doing the binary relocation of the produced binaries, and then string replacement of the build prefix in text files.
the way we deal with the case of the prefix path being used in compiled binaries is by using a long (255 chars) installation path at build time, and replace it at installation time by the (zero-padded) installation prefix. A warning is issued to packagers that binary replacement has to be done for relocation.
In the case of leocad, the LDRAW_LIBRARY_PATH is such an instance of the build prefix being present in the compiled binary. I had foreseen that, although I did not realize that the compiler would also put the first characters of this value in the beginning of the small-string-optimization buffer of the QString where it is stored.

The way I could fix it is by preventing this optimization by creating and intemediary `volatile const char*` holding the value of LDRAW_BINARY_PATH to be copied into the QString.

I will post another issue proposing another solution to deal with the LDRAW_LIBRARY_PATH in a way that prevents jumping through these hoops.

**Comment by SylvainCorlay** [comment]
> I will post another issue proposing another solution to deal with the LDRAW_LIBRARY_PATH in a way that prevents jumping through these hoops.

Closing this issue as I will open a separate ticket on proposing another way of specifying the default library path.

**Comment by leozide** [comment]
You can also add -l to the command line or set the LEOCAD_LIB env var
