### ISSUE TITLE
website: stale link to parts library

### ISSUE THREAD

**Issue by KJ7LNW** [leozide/leocad#858]
**Describe the bug**

The link on the website is no longer valid: 
https://www.leocad.org/docs/library.html points at http://www.ldraw.org/library/unofficial/ldrawunf.zip which is a 404.

The new link is https://library.ldraw.org/updates?latest or maybe https://library.ldraw.org/library/updates/complete.zip

Also, the documentation says this:
```
 $ set LEOCAD_LIB=C:\User\Downloads\complete.zip 
```
which doesn't work, but first _extract the zip_ and then it does:
```
$ set LEOCAD_LIB=C:\User\Downloads\ldraw
```

Actually in Linux I did this, but kept the Windows example above:
```sh
# Doesn't work:
LEOCAD_LIB=/usr/share/leocad/ldraw/complete.zip leocad 

# *Does work* after extracting:
LEOCAD_LIB=/usr/share/leocad/ldraw/ leocad 

```

**Comment by leozide** [comment]
the env var works for me

**Comment by KJ7LNW** [comment]
It works if you pass the .zip in the environment?
