### ISSUE TITLE
Plugin for V-REP (LeoCAD + ev3dev + V-REP for design & simulating EV3 robots)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#86]
More details on this idea coming soon
* http://www.coppeliarobotics.com/helpFiles/en/pluginTutorial.htm

Use V-REP PRO EDU
* http://www.coppeliarobotics.com/downloads.html
  * https://github.com/simondlevy/vrep-ubuntu
  * http://www.coppeliarobotics.com/helpFiles/en/compilingVrep.htm
  * https://m.youtube.com/channel/UCDbPdIbFs_TQfOCQNkgbGmQ

# Reference

* https://riuma.uma.es/xmlui/bitstream/handle/10630/12980/Alberto%20Martin%20DominguezMemoria.pdf?sequence=1
  * https://github.com/albmardom/EV-R3P
  * https://m.youtube.com/channel/UCD-2ZPnIeJpyBLv_phqZMwQ
* https://github.com/ev3dev
  * http://www.ev3dev.org/docs/programming-languages/

**Comment by Symbian9** [comment]
As alternative to V-REP there is Blender Game Engine and its forks

* https://wiki.blender.org/index.php/Community:Science/Robotics
* https://www.openrobots.org/morse/doc/latest/what_is_morse.html
* http://www.blensor.org

**Comment by j6t** [comment]
Can you please be a bit more specific what V-REP and EV3 is and how it helps Lego builds? A list of links is not very helpful.
