### ISSUE TITLE
Tool panels loose quilt-in QT grip once undocked on Debian 12 [WAYLAND SPECIFIC]

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#879]
**Describe the bug**
Cannot reinsert panels once undocked on LeocAD (Debian 12) - continuous build

**To Reproduce**
1. build latest leocad from source
2. open leocad
3. drag any panel
4. qt win toggles disappear

**Expected behavior**
qt win toggles should remain and panels should be able to be reinserted anywhere within the main leocad window

**Screenshots**
![image](https://github.com/leozide/leocad/assets/5674757/6780c567-92fb-4109-acdb-29f8839f9780)

**Version (please complete the following information):**
 - OS: debian 12 bookwork 64bit
 - LeoCAD Version cont.

Context: Gnome Dsktop

EDIT:

Upon verification, this seems to only happen when Wayland is selected Ted as the session display server. Under X11, panels still function as expected.

**Comment by leozide** [comment]
looks like a qt bug
