### ISSUE TITLE
Export pieces' pivot points

### ISSUE THREAD

**Issue by AlexGustafsson** [leozide/leocad#90]
Right now exporting to .obj or .3ds does not keep the pivot points within LeoCAD. The expected behaviour is to export these as well. The current behaviour is that all pieces have their pivot point / origin in the world origin (0, 0, 0).

Both .3ds and .obj supports pivot points.

I took a look at both of the file specifications but I could not quite wrap my head around it enough to submit a PR.

**Comment by leozide** [comment]
I've looked into the 3ds pivots when I first added the exporter but couldn't get it to work correctly.

I didn't know there was support for it in obj files but I'm not sure how many applications support, it may be safer to keep things the way they are.

**Comment by Symbian9** [comment]
> I didn't know there was support for it in obj files but I'm not sure how many applications support

As I know, V-REP simulator could import OBJ with pivots points.

* https://github.com/leozide/leocad/issues/86

But, as for me, for such things would be much better add "Export -> AC3D..."

* https://sites.google.com/view/ac3dfileformat/home

* https://github.com/NikolaiVChr/Blender-AC3D

**Comment by Symbian9** [comment]
> I tried it, it works with the OBJ format, but the export loses the object names, for example, if I export one object composed of several parts, the OBJ file contains only a single mesh object and unfortunately for applications that want to interface (the open-source project for flight simulation named Flightgear) it is important that the individual parts have their own name. My idea is to figure out if it makes sense to to make a program to export to AC3D.
> 
> * https://forum.freecadweb.org/viewtopic.php?t=11951&p=95975#p95975

**Comment by leozide** [comment]
Collada exports files correctly and most applications support it, I'll leave the legacy formats alone.
