### ISSUE TITLE
LeoCAD consistently crashes when trying to use Replace

### ISSUE THREAD

**Issue by Zordid** [leozide/leocad#901]
**Describe the bug**
Whenever I start to try to replace some parts using the "Replace" feature, LeoCAD just freezes and I need to force close it.

**To Reproduce**
1. Load my model
2. Open Replace function
3. Select parts
4. Crash...

**Expected behavior**
Well, it should not crash...

**Screenshots**

**Version (please complete the following information):**
 - OS: Windows 11
 - LeoCAD Version 23.03
 
**Crash information:**
Some versions of LeoCAD will show a message that they saved a minidump file when they crash, if you see this message please attach the file.

**Additional context**
Add any other context about the problem here. If you're seeing a graphical issue, adding a screenshot of the About Dialog may help.

**Comment by gerw** [comment]
I am currently trying to reproduce. If you search (or replace) a part, which is not currently visible (it is in a later step), then leocad freezes.

I also managed to produce a segfault while using 'replace', but I am not able to reproduce it.
