### ISSUE TITLE
Scroll Wheel function

### ISSUE THREAD

**Issue by zackous** [leozide/leocad#907]
Hi, I use CAD programs (Solidworks, Onshape) and they allow the use of the scroll wheel or other button to pan. In LeoCAD I have to manually switch tools even though my mouse has 2 buttons (left click and scroll wheel click) that perform the same function which seems unnecessary. 

What I am asking for is the selection, pan, and 3D rotate functions to be assigned to left click/left click + drag, scroll wheel click + drag, and right click + drag as outlined below

Left click = Select
Left click + drag = Selection box
Scroll wheel click + drag = Pan
Right click + drag = 3D Rotate

Thank you for your time

**Comment by zackous** [comment]
I just found the mouse preferences (View > Preferences > Mouse), but I still think the default should be changed. Also, when I say "3D Rotate", I mean Orbit.

**Comment by leozide** [comment]
The defaults are the same as Maya
