### ISSUE TITLE
The asterisk indicating project modification is not updated until after some additional user activity

### ISSUE THREAD

**Issue by felipesanches** [leozide/leocad#913]
If I am working on a model and it has an asterisk indicating modifications, then I would expect that the asterisk should disappear upon saving (such as by pressing **Ctrl+S**). But it doesn't. It only happens after I change the camera angle with some mouse interaction.

Maybe other user actions can also trigger the update. But the issue is that absolutely no user input should be needed. The asterisk should be immediately updated upon saving.

**Comment by leozide** [comment]
works for me, the title bar gets update after ctrl+s
