### ISSUE TITLE
Impossible d'ouvrir une ressource sous Ubuntu

### ISSUE THREAD

**Issue by loursjura** [leozide/leocad#924]
Under Ubuntu 22.04.4, it is impossible to navigate to open a directory on a second disk.
You must enter the full path of the directory

Other concerns; the ldraw library is only accessible if it is in the user's Home directory, which poses the problem of access by another user, the obligation to copy the directory X times.

[Bug-leocad.pdf](https://github.com/user-attachments/files/16636966/Bug-leocad.pdf)
Cordialement

**Comment by leozide** [comment]
there's no bug here, this is just how the file picker looks, you can browse to / and then find the folder from there or type in the folder
