### ISSUE TITLE
Replace QMake with CMake

### ISSUE THREAD

**Issue by Elshid** [leozide/leocad#926]
Back in 2019, the Qt Group has decided to retire QMake step by step (See here: https://www.qt.io/blog/2019/08/07/technical-vision-qt-6). The first step was to phase out QMake internally, which is already done, AFAIK.
While QMake is still supported and also will be for some time, the reason for the decision of the Qt group is obvious: QMake isn't widely supported, both by external libraries and tooling, while at the same time having quite some "quirks" (to use the wording of the Qt Group).

Therefore, I think that it is time that this project follows the example of the Qt Group. It will make working on this project a lot easier, especially for the Issues #921 (which is mine) and #65.

I will write the CMake-File, so I can compile with it on both on Linux and Windows. I would be happy if someone else could take care of getting things done on MacOS. Concerning the CI-Pipline: I think that that would have to be done by @leozide.

**Comment by leozide** [comment]
I think qmake is good enough for our needs, there's no need to add an extra dependency on cmake and do all the extra work to switch to it
