### ISSUE TITLE
Save Scalable Vector Graphics... (.svg)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#94]
Save current view to SVG

* https://www.opengl.org/discussion_boards/showthread.php/166795-export-opengl-3d-scene-to-SVG
  * http://www.geuz.org/gl2ps/

It could be separate entry in "File" menu or as one of variants in "Save Image..." submenu.

Also as option save all steps in single animated SVG (since SVG has support for animation)

* https://www.w3.org/TR/SVG/animate.html
* https://www.sarasoueidan.com/blog/svg-vs-gif/
* https://en.m.wikipedia.org/wiki/SVG_animation

P.S.: More details coming soon

**Comment by leozide** [comment]
I don't think there's a need for svg, it has no advantages over the already supported formats.
