### ISSUE TITLE
Implement GLTF 2.0 as an export format

### ISSUE THREAD

**Issue by AlexGustafsson** [leozide/leocad#98]
I'll leave this article to explain why:

https://godotengine.org/article/we-should-all-use-gltf-20-export-3d-assets-game-engines

**Comment by Symbian9** [comment]
Also added request for COLLADA 1.5 export

* https://github.com/leozide/leocad/issues/100

> I'll leave this article to explain why

Here is presentation about COLLADA & glTF from SIGGRAPH2017

* https://www.youtube.com/watch?v=xAvyTvtUEX0

**Comment by leozide** [comment]
I've just added a collada exporter which fixes the limitations we had with the obj and 3ds exporters.

I'm not a big fan of collada but I don't think glTF has any advantages over it, most of the problems listed in that article don't apply to our use case here. Do you have any particular reason to want it?
